package io.openems.edge.heater.chp.viessmann;

public enum ErrorPossibilities {
    STANDARD_ERRORS(new String[]{
            "Lüfter gestört",
            "Kühlwasserpumpe gestört",
            "Abgasgegendruck max.",
            "Einspeiseschalter",
            "Externe Störung",
            "Überdrehzahl",
            "Kühlwassertemperatur",
            "Abgastemperatur max.",
            "",
            "Not-Stopp",
            "Ölstand min.",
            "Kühlwasserdruck min.",
            "Gasdruck min.",
            "Sicherheitstemperatur",
            "Generatortemperatur",
            "Schallhaubentemperatur",
            "Zuschaltung gestört",
            "Synchronisierung gestört",
            "Drehzahl < 50",
            "Ölstand max.",
            "Temperatur Pt100_2 max.",
            "Temperatur Pt100_3 max.",
            "Leistung max.",
            "Rückleistung",
            "Abgastemperatur min.",
            "Öldruck min.",
            "Gasdruck max.",
            "Heizwasserpumpe gestört",
            "Anlassdrehzahl < 50 Upm",
            "Zünddrehzahl",
            "Drehzahlfenster",
            "Drehzahl < 1200 Upm",
            "Schaltuhr Abwahl Meldung",
            "Schaltuhr Freigabe Meldung",
            "Netzstörung F < nicht",
            "Netzstörung F > nicht",
            "Netzstörung U+F <> nicht",
            "Klopfen Leistung Min.",
            "Klopfen Leistung Max.",
            "Netzkuppelschalter",
            "Leistungsregler gestört",
            "Lambdaregler gestört",
            "Generatorschütz gestört",
            "Zündung gestört",
            "Öldruck gestört",
            "Lambda Startposition",
            "Klopfen EIN",
            "Klopfen AUS",
            "Batterie Unterspannung",
            "Generator Unterspannung",
            "Generator Überspannung",
            "Generator Überstrom",
            "Generator Schieflast",
            "Dichttest gestört",
            "Netzschutz gestört",
            "Sensoren gestört",
            "Klopfen Störung",
            "Netz o.k. Meldung",
            "Netzstörung Warnung",
            "Temperatur Abwahl Meldung",
            "Temperatur Freigabe Meldung",
            "Wartung überschritten",
            "Sicherheitsabschaltung",
            "Motor steht nicht",
            "Abgastemp. Differenz A/B",
            "Reserve",
            "Temp. Rücklauf max PT100/2",
            "Temp. Heizwasser max PT100/3",
            "Temp. Motoröl max",
            "Temp. Gasgemisch max",
            "Temp. Gemischkühlwasser max",
            "Reserve",
            "Abgastemperatur A max",
            "Abgastemperatur A min",
            "Abgastemperatur B max",
            "Abgastemperatur B min",
            "Abgastemperatur C max",
            "Abgastemperatur C min",
            "Abgastemperatur D max",
            "Abgastemperatur D min "});

    private String[] errors;

    ErrorPossibilities(String[] errors) {
        this.errors = errors;
    }

    public String[] getErrorList() {
        return this.errors;
    }


}
