package io.openems.edge.ess.mr.gridcon;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "ESS MR Gridcon PCS", //
		description = "Implements the FENECON MR Gridcon PCS system")
@interface Config {
	String service_pid();

	String id() default "ess0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	@AttributeDefinition(name = "Modbus-Unit-ID", description = "Unit ID of Modbus brige.")
	int unit_id() default 1;

	@AttributeDefinition(name = "Battery-IDs", description = "IDs of Batteries.")
	String[] battery_ids();

	@AttributeDefinition(name = "Batteries target filter", description = "This is auto-generated by 'Battery-IDs'.")
	String batteries_target() default "";

	String webconsole_configurationFactory_nameHint() default "ESS MR Gridcon PCS [{id}]";
}