package io.openems.edge.controller.ess.limittotaldischarge;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Ess Limit Total Discharge", //
		description = "Limits total discharge for an Ess.")
@interface Config {

	String service_pid();

	String id() default "ctrlLimitTotalDischarge0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id();

	@AttributeDefinition(name = "Min-SoC", description = "Discharging is blocked while State of Charge is below Min-SoC.")
	int minSoc() default 15;

	@AttributeDefinition(name = "Force-Charge-SoC", description = "Charging is forced while State of Charge is below Force-Charge-SoC.")
	int forceChargeSoc() default 10;

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "";

	String webconsole_configurationFactory_nameHint() default "Controller Ess Limit Total Discharge [{id}]";

}