package io.openems.edge.evse.chargepoint.voltie.enums;

import io.openems.common.types.OptionsEnum;

/**
 * Charge stop reason (register 0x0012) as reported by the Voltie charge-point.
 *
 * <p>
 * Source: Voltie Modbus API documentation v1.4 (2026-09-23). Only the codes
 * listed in that document are enumerated here; the codes it marks as reserved
 * (19 and 20) are not generated by the firmware and are left out.
 */
public enum ChargeStopReason implements OptionsEnum {
	UNDEFINED(-1, "Undefined"), //
	NONE(0, "None, charging in progress"), //
	UNSPECIFIED(1, "Unspecified reason"), //
	DURATION_REACHED(2, "Preset charge duration reached"), //
	ENERGY_REACHED(3, "Preset energy amount charged"), //
	STOPPED_BY_USER(4, "Stopped by the user"), //
	ERROR_RESIDUAL_CURRENT(5, "Error: residual current detected"), //
	CHARGER_DISABLED(6, "Charger disabled, out of order"), //
	FIRMWARE_RESTART(7, "Firmware restart"), //
	SLEEP_MODE(8, "Charger in sleep mode, out of order"), //
	ERROR_NO_OUTPUT_VOLTAGE(9, "Error: no voltage on the output"), //
	VEHICLE_DISCONNECTED(10, "Vehicle disconnected"), //
	VEHICLE_NOT_ACCEPTING(11, "Vehicle not accepting charge"), //
	ERROR_I2C_BUS(12, "Error: I2C bus fault"), //
	ERROR_RCD_SENSOR_TEST(13, "Error: residual current sensor test failed"), //
	ERROR_OVER_TEMPERATURE(14, "Error: over temperature"), //
	ERROR_CONTROL_PILOT(15, "Error: control signal (CP)"), //
	ERROR_STUCK_RELAY(17, "Error: stuck relay"), //
	ERROR_OVER_CURRENT(18, "Error: over current"), //
	ERROR_OVER_HUMIDITY(21, "Error: over humidity"), //
	ERROR_PHASE_MISCONNECTED(22, "Error: phase misconnected"), //
	DLM_NO_BUILDING_CURRENT(100, "Not enough free building current available (dynamic load management)"), //
	ECO_NO_SOLAR_CURRENT(101, "Not enough solar current available (eco/green mode)"), //
	GRID_VOLTAGE_LOW(102, "Grid voltage is not high enough (grid-controlled mode)"), //
	CURRENT_LIMIT_ZERO(103, "Charge current limit set to zero"), //
	ERROR_OVERVOLTAGE(105, "Error: overvoltage"), //
	ERROR_VEHICLE(106, "Error: vehicle fault"), //
	ERROR_UNDERVOLTAGE(107, "Error: undervoltage on AC supply"), //
	STATE_D_DISABLED(108, "Vehicle in state D while state D is disabled"), //
	ERROR_UNKNOWN_POWER_BOARD(109, "Error: unknown power board");

	private final int value;
	private final String name;

	private ChargeStopReason(int value, String name) {
		this.value = value;
		this.name = name;
	}

	@Override
	public int getValue() {
		return this.value;
	}

	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public OptionsEnum getUndefined() {
		return UNDEFINED;
	}
}
