= OpenEMS Edge Core LDAP bundle

OpenEMS Edge implementation for LDAP user service.

Allows authentication and authorization through a LDAP server for edges.

== LDAP example structure

----
dc=test
 +-- ou=groups [defines the global role of the users]
 |    +-- cn=openems_admin
 |    |   objectclass: groupOfNames
 |    |   member: uid=username1,ou=users,dc=test
 |    |
 |    +-- cn=openems_guest
 |    |   objectclass: groupOfNames
 |    |   member: uid=username2,ou=users,dc=test
 |    |   member: uid=username3,ou=users,dc=test
 |    |
 |    +-- cn=openems_installer
 |    |   objectclass: groupOfNames
 |    |   member: uid=username4,ou=users,dc=test
 |    |
 |    +-- cn=openems_owner
 |    .   objectclass: groupOfNames
 |    .   member: uid=username5,ou=users,dc=test
 |    .   member: uid=username6,ou=users,dc=test
 |
 +-- ou=users [defines users, configuration: Users ou]
     +-- uid=username1
     |   objectclass: inetOrgPerson
     |   (memberOf: cn=openems_admin)
     |   displayname: firstname lastname
     |   preferredlanguage: de
     |   userPassword: XXX
     |
     +-- uid=username2
     |   ...
     |
     +-- uid=username3
     |   ...
     .
     .
     .

----

*Note:* In my LDAP the memberOf overlay is installed. It creates and updates the memberOf attribute automatically. If you do not have this overlay (which is the default), you need to maintain this attribute on your own, meaning you have to add and maintain it by hand.

I have been running my LDAP for ages, but afaik memberOf overlay is deprecated for some time now. Unfortunately I did not have time to think of alternatives yet ... dynlist overlay might be a good try.

== Licence

Copyright (C) 2024 Christian Poulter <devel(at)poulter.de>

This program and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at https://www.eclipse.org/legal/epl-2.0