#!/bin/sh
echo -n 7 >/sys/class/gpio/unexport
echo -n 46 >/sys/class/gpio/unexport
echo -n 30 >/sys/class/gpio/unexport
echo -n 31 >/sys/class/gpio/unexport
echo -n 15 >/sys/class/gpio/unexport
echo -n 42 >/sys/class/gpio/unexport
echo -n 43 >/sys/class/gpio/unexport
echo -n 5 >/sys/class/gpio/unexport
echo -n 44 >/sys/class/gpio/unexport
echo -n 72 >/sys/class/gpio/unexport
echo -n 24 >/sys/class/gpio/unexport
echo -n 25 >/sys/class/gpio/unexport
echo -n 10 >/sys/class/gpio/unexport
echo -n 74 >/sys/class/gpio/unexport
echo -n 26 >/sys/class/gpio/unexport
echo -n 27 >/sys/class/gpio/unexport
echo -n 4 >/sys/class/gpio/unexport
echo -n 70 >/sys/class/gpio/unexport
echo -n 22 >/sys/class/gpio/unexport
echo -n 23 >/sys/class/gpio/unexport
echo -n 6 >/sys/class/gpio/unexport
echo -n 36 >/sys/class/gpio/unexport
echo -n 37 >/sys/class/gpio/unexport
echo -n 40 >/sys/class/gpio/unexport
echo -n 41 >/sys/class/gpio/unexport
echo -n 38 >/sys/class/gpio/unexport
echo -n 39 >/sys/class/gpio/unexport