= Manually Configurable

This bundle provides manually configurable time-of-use-tariffs.

Implementations:

== Fixed Grid-Sell

Implementation of a grid-sell tariff with a fixed grid-sell price.

== EEG 2025

Implementation of a grid-sell tariff according to the EEG 2025 policy.
It uses the ENTSO-E Transparency Platform to retrieve day-ahead electricity prices for European bidding zones.
While the tariff is generally fixed, if the day-ahead market price is negative for a given period, the grid-sell price for that period is set to 0.

== Octopus Go

Calculates the quarterly prices for the next 36 hours based on the standard and low-price details from the user's contract. 
For a detailed overview of the tariff structure, please refer to: https://octopusenergy.de/octopus-go

== Octopus Heat

Calculates the quarterly prices for the next 36 hours based on the high, standard and low-price details from the user's contract. 
For a detailed overview of the tariff structure, please refer to: https://octopusenergy.de/octopus-heat

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.timeofusetariff.manual[Source Code icon:github[]]