= Emergency Mode Controller
	
 Main idea is to control Block Heat Power Plant(BHKW) RUN/STOP state, MSR Heating System, ON-Off Grid Indication Controller via sending a signal to WAGO fieldbus. 
 Controller will be in process based on "Grid Mode" of the inverter and under the consideration of "state of charge" (soc).
 
 
== Logic And Discussed Situations 


. **Grid Mode variations**

	.. `Undefined`: Grid-Mode is undefined -> Needs to wait till gets clear information.

	.. `Off-Grid`: Grid-Mode is Off-Grid ->

	... As soon as it is detected as Off-grid mode, BHKW must be stopped and wait until the system restarts. 
	... Once the system has entered the START mode: It should assess the Soc level and decide which state it is in, and also whether or not hysteresis is to be administered.
	... A detailed states documentation will follow in **States according to Soc level** section.

	.. `On-Grid`: Grid-Mode is On-Grid ->

	Table 1.Switch state will be as given below in On-Grid Mode.
|===
		|Keep Block Heat Power Plant ( BHKW ),|RUN
		|MSR Heating System Controller,|OFF
		|On Grid Indication Controller,|ON
		|Off Grid Indication Controller,|OFF
		|===


. **States according to Soc level**

	.. `UNDEFINED`: Unknown state on first start. At the beginning, after getting in Off-Grid Mode havent decide yet on which situtation needs to be switches. So that following condtions will check. 

    ... First of all it checks whether soc is bigger than or not. If soc bigger than the threshold, State needs to be ABOVE_THRESHOLD and break here. And, next steps needs to handle in ABOVE_THRESHOLD state.

	... Secondly, it evaluates if hysteresis is necessary while comparing between soc and difference between threshold and hysteresis. If soc is smaller than the subtraction of threshold and hysteresis will not apply hysteresis.

	... Another condition to decide to apply hysteresis can be check via comparing soc with threshold. if soc equal or bigger than threshold, controller will not apply hysteresis.
			
	... If previous state was PASS_THRESHOLD_COMING_FROM_ABOVE and if it should apply hysteresis, state needs to be on PASS_THRESHOLD_COMING_FROM_ABOVE and break it here.

	... If condition iv. doesn't supplied and if charge state is on discharge and also if it should apply hysteresis state needs to be on PASS_THRESHOLD_COMING_FROM_ABOVE and break here. Proccess will be handle on that state. 

	... Till here if haven't supplied any conditions, but still needs to apply hysteresis that means system is in standby or charge mode so that it needs RUN BHKW.
	Then it could check whether its coming from below or not with looking at equality between soc and summation of threshold and hysteresis.If soc has bigger value state needs to be in  PASS_THRESHOLD_COMING_FROM_BELOW. Or it doesn't needs to apply hysteresis but soc could be equal or higher than threshold, it could also enter in the same state as PASS_THRESHOLD_COMING_FROM_BELOW.

	... And at the end of this state, if none of the condition supplied which means state will be on BELOW_THRESHOLD_AND_HYSTERESIS.


	..`BELOW_THRESHOLD_AND_HYSTERESIS`: Value is lower than the threshold - hysteresis
		
		To Do: Run BHKW.

	..  `ABOVE_THRESHOLD`:  Value is bigger than the threshold.

		To Do:  Stop BHKW. 


		
== Configuration 

Component-ID Unique ID of this Component (id), e.g. "ctrlEmergencMode0", "ctrlEmergencMode1"

Alias Human-readable name of this Component: Defaults to Component-ID (alias)

* `Block Heat Power Plant Permission Signal`: Default configuration has set as DigitalOutputM1C1. Which means its first channel of first module of Wago.

* `MSR Heating System Controller`: Default configuration has set as DigitalOutputM1C2. Which means its second channel of first module of Wago.
    
* `On Grid Indication Controller`: Default configuration has set as DigitalOutputM2C1. Which means, its first channel of second module of Wago.

* `Off Grid Indication Controller`: Default configuration has set as DigitalOutputM2C2. Which means its second channel of second of Wago.

* `Threshold`:

* `Hysteresis`: The hysteresis is applied to threshold to avoid continuous switching.

== Terms 

* `Boundary/Interval`: To decide where take part in condtion of applying Hysterissis. 

	... It's called out of the boundary if soc is lower than subtraction of Threshold and hysterissis.
	... It's called inside of the boundary if soc is higher than subtraction of Threshold and hysterissis.













