package io.openems.edge.system.fenecon.industrial.l;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.system.fenecon.industrial.l.envicool.Envicool;

@ObjectClassDefinition(//
		name = "System FENECON Industrial L", //
		description = "Implements the FENECON Industrial L core component")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "system0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Battery IDs", description = "IDs of battery devices.")
	String[] batteryIds();

	// Envicool AC related config parameters

	@AttributeDefinition(name = "AC: Enabled?", description = "Start or stop the AC")
	Envicool.Mode acMode();

	@AttributeDefinition(name = "AC: Modbus-ID", description = "ID of Modbus bridge of the AC.")
	String acModbus_id() default "modbus0";

	@AttributeDefinition(name = "AC: Modbus Unit-ID", description = "The Unit-ID of the Modbus device of the AC.")
	int acModbusUnitId() default 1;

	@AttributeDefinition(name = "AC: Cooling Temperature", description = "The Cooling temperature in Celsius. Must be between 10 °C and 35 °C")
	int acCoolingSetPoint() default 30;

	@AttributeDefinition(name = "AC: Heating Temperature", description = "The Heating temperature in Celsius. Must be between 10 °C and 35 °C")
	int acHeatingSetPoint() default 20;

	@AttributeDefinition(name = "AC: Modbus target filter", description = "This is auto-generated by 'AcModbus-ID'.")
	String AcModbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "System FENECON Industrial L [{id}]";

}