package io.openems.edge.WagoTest;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "WAGOTEST", //
		description = " WAGOTEST")
@interface Config {
	String service_pid();

	String id() default "wagotest0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "FtpPort", description = "Ftp Port")
	int ftpPort() default 21;

	@AttributeDefinition(name = "Username", description = "Username")
	String username() default "admin";

	@AttributeDefinition(name = "Password", description = "Password")
	String password() default "wago";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "WAGOTEST [{id}]";
}