package io.openems.edge.pytes.battery;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Pytes Battery", //
		description = "Implements the Pytes Battery.")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "battery0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "Pytes Battery";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Max. charge/discharge current [A]", description = "Maximum battery charge/discharge current")
	int max_current() default 10;

	@AttributeDefinition(name = "Pytes ESS-ID", description = "ESS-ID to which the battery is connected to")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "pytes ESS target filter", description = "This is auto-generated by 'Pytes ESS '.")
	String Ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	@AttributeDefinition(name = "Debug", description = "Enable debug mode?")
	boolean debugMode() default false;

	String webconsole_configurationFactory_nameHint() default "Pytes Battery [{id}]";
}
