package io.openems.edge.pytes.battery;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Pytes Battery", //
		description = "Implements the Pytes Battery.")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "battery0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "Pytes Battery";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Max. charge current [A]", description = "Additional EMS-side upper limit for the battery charge current. The smallest of this value, the BMS limit and the inverter's own setting (reg 43117, app 'max. charge current') is used. Only enforceable while the inverter follows the EMS set-point - with an active grid feed-in limit the inverter charges autonomously up to its own setting, so do not configure a value below the inverter setting.")
	int maxChargeCurrent() default 40;

	@AttributeDefinition(name = "Max. discharge current [A]", description = "Additional EMS-side upper limit for the battery discharge current. The smallest of this value, the BMS limit and the inverter's own setting (reg 43118, app 'max. discharge current') is used. Only enforceable while the inverter follows the EMS set-point.")
	int maxDischargeCurrent() default 40;

	@AttributeDefinition(name = "Capacity [Wh]", description = "Nominal battery capacity, e.g. 100 Ah x 51.2 V = 5120 Wh. The Pytes BMS does not report it via the inverter (BMS extension block 34345-34364 is empty, reg 43387 is a fixed 3.0 kWh placeholder that cannot be set in the app - verified 2026-09-18). 0 = unknown.")
	int capacity() default 0;

	@AttributeDefinition(name = "Pytes ESS-ID", description = "ESS-ID to which the battery is connected to")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "pytes ESS target filter", description = "This is auto-generated by 'Pytes ESS '.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	@AttributeDefinition(name = "Debug", description = "Enable debug mode?")
	boolean debugMode() default false;

	String webconsole_configurationFactory_nameHint() default "Pytes Battery [{id}]";
}
