= Water meter

Water meter that communicate over M-Bus and Wireless M-Bus. Data record addresses of several meter models included.
Allows manual entering or automatic searching of data record addresses for any meter model not in the list.

== Wireless M-Bus
WM-Bus devices regularly send radio messages in an interval that is defined by the device. An active WM-Bus bridge
listens to these messages. The messages contain some identification information in the header and a usually encrypted
message body called the variable data structure. Part of the identification information is the radio address of the
device, that is usually printed on the meter.

This module uses the radio address of the meter to identify it's radio messages. The radio address is registered with
the WM-Bus bridge, who then assigns any received messages from this radio address to this device. If a decryption key
is entered when configuring the module, this key is used to decrypt the messages.

== M-Bus
M-Bus devices are polled by the M-Bus bridge in an interval configured by the module. This done to preserve battery
energy on battery powered meters. Meters are identified by their primary address, which needs to be entered at
configuration.

== Processing of data
The data in a Wireless M-Bus or M-Bus message is organized as numbered data records that contain a value and a unit.
The basic case is that volume of consumed water is on record number 0, and the timestamp is on record number 1. On which
record number which data is stored depends on the meter model. Some meters even have dynamic addresses/positions.

Data values are transferred to channels by assigning a channel to a data record address. So you need to know on which
record position your meters stores which data. Since the data records have units, an autosearch function is possible
that compares the data record's unit with the channel unit until it finds a match. The units comparison is also used
to automatically scale the value to the channel unit. If that is not possible because of unit mismatch, an error
message is written in the error message channel.

This module includes a list of meters with their data record positions for volume and timestamp. If your meter is not
in that list, you can manually enter the record positions for volume and timestamp or use the autosearch function. It
is also possible to let OpenEMS create the timestamp instead of reading it from the meter.

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.watermeter[Source Code icon:github[]]