package io.openems.edge.simulator.controller.ess.csvfrequency;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Simulator Controller Ess CSV Frequency", //
		description = "Reads frequency values from CSV and applies stacked FCR + FFR1 + Recharge power to an ESS.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlCsvFrequency0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id();

	@AttributeDefinition(name = "Datasource-ID", description = "ID of CSV Datasource component.")
	String datasource_id();

	@AttributeDefinition(name = "Frequency Column Name", description = "Name of the column in CSV containing frequency values in Hz")
	String frequencyColumnName() default "FREQUENCY";

	// --- Power Rating ---

	@AttributeDefinition(name = "Total Power Rating [W]", description = "Total rated power in Watts. FCR=50%, FFR=25%, IDM=25%.")
	int power() default 176000;

	// --- FCR Parameters ---

	@AttributeDefinition(name = "Nominal Frequency [Hz]", description = "Nominal grid frequency")
	double nominalFrequency() default 50.0;

	@AttributeDefinition(name = "FCR Max Frequency Deviation [Hz]", description = "Frequency deviation that maps to full FCR power")
	double fcrMaxFrequencyDeviation() default 0.2;

	@AttributeDefinition(name = "FCR Frequency Deadband [Hz]", description = "Deadband around nominal frequency for SOC-aware FCR behavior")
	double fcrFrequencyDeadband() default 0.01;

	@AttributeDefinition(name = "FCR SOC Target [%]", description = "Target SOC for FCR deadband logic")
	double fcrSocTarget() default 50.0;

	// --- FFR1 Parameters ---

	@AttributeDefinition(name = "FFR1 Threshold Frequency [Hz]", description = "Frequency below which FFR1 activates")
	double ffr1ThresholdFrequency() default 49.5;

	@AttributeDefinition(name = "FFR1 Droop Coefficient k", description = "Droop coefficient for FFR1 response")
	double ffr1K() default 0.05;

	@AttributeDefinition(name = "FFR1 Support Duration [s]", description = "Duration of FFR1 power support in seconds")
	double ffr1SupportDuration() default 30.0;

	@AttributeDefinition(name = "FFR1 Recovery Period [s]", description = "Recovery period after FFR1 event in seconds")
	double ffr1RecoveryPeriod() default 300.0;

	// --- Recharge Parameters ---

	@AttributeDefinition(name = "IDM Transaction Time [s]", description = "Interval in seconds for recharge SOC decisions")
	long rechargeIdmTransactionTime() default 900;

	@AttributeDefinition(name = "Recharge SOC Min [%]", description = "Below this SOC, recharge strategy charges")
	double rechargeSocMin() default 20.0;

	@AttributeDefinition(name = "Recharge SOC Max [%]", description = "Above this SOC, recharge strategy discharges")
	double rechargeSocMax() default 80.0;

	// --- Ramp Rate ---

	@AttributeDefinition(name = "Enable Ramp Rate", description = "If true, power changes are ramped gradually. If false, calculated power is applied directly.")
	boolean rampEnabled() default true;

	@AttributeDefinition(name = "Ramp Rate [W]", description = "Maximum power change per ramp interval in Watts.")
	int rampRate() default 5000;

	@AttributeDefinition(name = "Ramp Cycle Interval", description = "Number of cycles between each ramp step. e.g. 5 means power adjusts every 5 cycles.")
	int rampCycleInterval() default 5;

	// --- Reference Filters ---

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
	String datasource_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Simulator Controller Ess CSV Frequency [{id}]";
}
