package io.openems.edge.battery.soltaro.multirack;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.battery.soltaro.BatteryState;

@ObjectClassDefinition( //
		name = "BMS FENECON Soltaro MultiRack", //
		description = "Implements the Soltaro multi rack battery system.")
@interface Config {
	String service_pid();

	String id() default "bms0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige; ! Soltaro MultiRack needs baudrate of 57600 !")
	String modbus_id();
	
	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 0;
	
	@AttributeDefinition(name = "Battery state", description = "Switches the battery into the given state, if default is used, battery state is set automatically")
	BatteryState batteryState() default BatteryState.DEFAULT;
	
	@AttributeDefinition(name = "Number of slaves", description = "The number of slave modules per rack (max. 22)", min = "1", max = "22")
	int numberOfSlaves() default 20;
	
	// TODO much more comfortable
	@AttributeDefinition(name = "Racks Used", description = "Determines what racks are used")
	int[] racks();
	
//	@AttributeDefinition(name = "Rack 1 Usage", description = "Determines whether rack 1 is used")
//	boolean rack1IsUsed() default true;
//	
//	@AttributeDefinition(name = "Rack 2 Usage", description = "Determines whether rack 2 is used")
//	boolean rack2IsUsed() default true;
//	
//	@AttributeDefinition(name = "Rack 3 Usage", description = "Determines whether rack 3 is used")
//	boolean rack3IsUsed() default true;
//	
//	@AttributeDefinition(name = "Rack 4 Usage", description = "Determines whether rack 4 is used")
//	boolean rack4IsUsed() default true;
//	
//	@AttributeDefinition(name = "Rack 5 Usage", description = "Determines whether rack 5 is used")
//	boolean rack5IsUsed() default true;
	
	@AttributeDefinition(name = "Error Level 2 Delay", description = "Sets the delay time in seconds how long the system should be stopped after an error level 2 has occurred")
	int errorLevel2Delay() default 600;
	
	@AttributeDefinition(name = "Max Start Attempts", description = "Sets the counter how many time the system should try to start")
	int maxStartAppempts() default 5;
	
	@AttributeDefinition(name = "Max Start Time", description = "Max Time in seconds allowed for starting the system")
	int maxStartTime() default 20;
	
	@AttributeDefinition(name = "Start Not Successful Delay Time", description = "Sets the delay time in seconds how long the system should be stopped if it was not able to start")
	int startUnsuccessfulDelay() default 3600;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "BMS FENECON Soltaro MultiRack [{id}]";
}