= Ess Active Power Voltage Characteristic

** This controller charge/discharge the system with active power in order to keep the grid voltage within an acceptable range.

** The force to be applied; It is the value indicates in the multi-line graph by taking as reference the ratio of network voltage to nominal voltage.

** Config parameters: 

*** lineConfig : Provides to set the ployline graph configuration via string.Default setting is : 
**** "[{ \"xCoord\" : 0.95, \"yCoord\" : 4000},
 **** { \"xCoord\":0.97999, \"yCoord\": 1000},
 **** { \"xCoord\" : 0.98, \"yCoord\" : 0},
 **** { \"xCoord\" : 1.0299, \"yCoord\" : 0},
 **** {\"xCoord\" :1.03 , \"yCoord\": -1000 },
 **** {\"xCoord\": 1.05 , \"yCoord\": -4000 }]";

 *** The other necessary parameter is nominalVoltage: reference point will be calculated via taking the ratio grid voltage to nominalVoltage
 
 *** waitForHysteresis: Does not update the set power if the last set 
 power time does not exceed the hysteresis time. Default value is 20 second.This parameter added also in purpose of to avoid the oscilation in grid voltage via setting frequently power.

https://github.com/OpenEMS/openems/tree/feature/develop/io.openems.edge.controller.ess.activepowervoltagecharacteristic[Source Code icon:github[]]