package io.openems.edge.kostal.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.kostal.enums.ControlMode;

@ObjectClassDefinition(
		//
		name = "ESS Kostal Plenticore", //
		description = "Implements the Kostal Plenticore hybrid energy storage system.")
@interface Config {
	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read-Only mode", description = "In Read-Only mode no set-power-commands are sent to the inverter")
	boolean readOnlyMode() default true;

	@AttributeDefinition(name = "Control mode", description = "Sets the Control mode")
	ControlMode controlMode() default ControlMode.INTERNAL;
	
	@AttributeDefinition(name = "Minimum Battery-Soc", description = "The minimum battery state of charge.")
	int minsoc() default 5;

	@AttributeDefinition(name = "Watchdog", description = "The watchdog configured at the inverter to return into internal operation mode.")
	int watchdog() default 30;
	
	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 71;

	@AttributeDefinition(name = "Capacity", description = "Capacity of the battery in [Wh]")
	int capacity() default 10_000;
	
	@AttributeDefinition(name = "Time-of-Use Controller", description = "ID of Time-of-Use controller instance for smart control")
	String ctrl_id() default "";

	@AttributeDefinition(name = "Time-of-Use controller target filter", description = "This is auto-generated by 'Time-of-Use controller target'.")
	String ctrl_target() default "(enabled=true)";

	// @AttributeDefinition(name = "Kostal PV-Inverter", description = "ID of
	// Kostal PV-Inverter.")
	// String inverter_id() default "pvInverter0";
//
//	@AttributeDefinition(name = "Core target filter", description = "This is auto-generated by 'Core-ID'")
//	String core_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS Kostal Plenticore [{id}]";
}
