= Implemented Devices
:sectnums:
:sectnumlevels: 4
:toc:
:toclevels: 4
:experimental:
:keywords: AsciiDoc
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../../../assets/images

For the following devices driver implementations are available in OpenEMS Edge.



== FENECON Commercial 40 AC/DC/Hybrid

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss
- EssDcCharger

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.fenecon.commercial40[Source Code icon:github[]]

== KACO blueplanet gridsave 50.0 TL3

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.kaco.blueplanet.gridsave50[Source Code icon:github[]]

== KACO blueplanet hybrid 10.0 TL3

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss

(proprietary)

== Maschinenfabrik Rheinhausen (MR) Gridcon

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.mr.gridcon[Source Code icon:github[]]

== REFU Battery Inverter

Project specific implementation of a REFU inverter. This will not directly apply to all REFU battery inverters.

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss
- AsymmetricEss
- ManagedAsymmetricEss

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.refu[Source Code icon:github[]]

== Sinexcel Battery Inverter

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.sinexcel[Source Code icon:github[]]

== SMA SunnyIsland 6.0H

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss
- AsymmetricEss
- ManagedAsymmetricEss
- SinglePhaseEss
- ManagedSinglePhaseEss

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.sma[Source Code icon:github[]]

== KEBA KeContact c-series Charging Station

Implemented Natures::
- Evcs (Electric Vehicle Charging Station)

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.evcs.keba.kecontact[Source Code icon:github[]]

== FENECON DESS

Applies to multiple similar products like the FENECON by BYD PRO Hybrid.

Implemented Natures::
- SymmetricEss
- AsymmetricEss
- EssDcCharger
- AsymmetricMeter (for Grid and AC-connected PV)
- SymmetricMeter (for Grid and AC-connected PV)

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.fenecon.dess[Source Code icon:github[]]

== FENECON Mini 3-3 | 3-6

Implemented Natures::
- SinglePhaseEss
- AsymmetricEss
- SymmetricEss
- SymmetricMeter (for Grid and PV)

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.fenecon.mini[Source Code icon:github[]]

== FENECON Pro 9-12

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss
- AsymmetricEss
- ManagedAsymmetricEss
- AsymmetricMeter (for PV)
- SymmetricMeter (for PV)

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.fenecon.pro[Source Code icon:github[]]

== FENECON BYD Container

Implemented Natures::
- SymmetricEss
- ManagedSymmetricEss

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.ess.byd.container[Source Code icon:github[]]

== KMtronic Modbus Relay Board

Implemented Natures::
- DigitalOutput

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.io.kmtronic[Source Code icon:github[]]

== WAGO Fieldbus Coupler 750-352

Implemented Natures::
- DigitalOutput
- DigitalInput

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.io.wago[Source Code icon:github[]]

== KOSTAL PIKO

Implemented Natures::
- SymmetricEss
- SymmetricMeter (for Grid meter)
- EssDcCharger (for PV)

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.kostal.piko[Source Code icon:github[]]

== Artemes AM-2

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.artemes.am2[Source Code icon:github[]]

== B-Control EM300 Meter

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.bcontrol.em300[Source Code icon:github[]]

== Carlo Gavazzi EM300 Meter

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.carlo.gavazzi.em300[Source Code icon:github[]]

== Janitza UMG 96RM-E Meter

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.janitza.umg96rme[Source Code icon:github[]]

== Microcare SDM 630 Meter

This implementation is functionally compatible with a number of energy meters with the name "SDM 630".

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.microcare.sdm630[Source Code icon:github[]]

== SOCOMEC Diris A10 | A14 | B30 | E24 Meter

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.socomec[Source Code icon:github[]]

== Weidmueller 525 Meter

Implemented Natures::
- SymmetricMeter
- AsymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.weidmueller[Source Code icon:github[]]

== Virtual Symmetric Add

Implemented Natures::
- SymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.virtual[Source Code icon:github[]]

== Solar-Log

Implemented Natures::
- SymmetricPvInverter
- SymmetricMeter

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.pvinverter.solarlog[Source Code icon:github[]]



