package io.openems.edge.meter.janitza.umg96rme;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Janitza UMG 96RM-E", //
		description = "Implements the Janitza UMG 96RM-E power analyser.")
@interface Config {
	String service_pid();

	String id();

	boolean enabled();

	@AttributeDefinition(name = "Meter-Type", description = "Grid, Production (=default), Consumption")
	String type();

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "Janitza UMG 96RM-E [{id}]";
}