package io.openems.edge.sma;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import io.openems.edge.ess.api.Phase;

@ObjectClassDefinition( //
		name = "SMA SunnyIsland 6.0H", //
		description = "Implements the SMA SunnyIsland 6.0H energy storage system.")
@interface Config {
	String service_pid();

	String id() default "ess0";

	boolean enabled() default true;

	int modbusUnitId() default 3;

	Phase Phase() default Phase.L1;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	@AttributeDefinition(name = "Fire Detection ", description = "Digital Input M2 C3")
	String fireDtection();

	@AttributeDefinition(name = "Battery Level Warning ", description = "Digital Input M2 C4")
	String batteryLevelWarning();

	@AttributeDefinition(name = "Door Operation ", description = "Digital Input M2 C2")
	String doorOperation();

	@AttributeDefinition(name = "Ventil Over Voltage Detection", description = "Digital Input M2 C1")
	String ventilOverVoltageDetection();

	@AttributeDefinition(name = "Sunny Islan 1", description = "Digital  Input M1 C1")
	String sunnyIsland1();

	@AttributeDefinition(name = "Sunny Islan 2", description = "Digital  Input M1 C2")
	String sunnyIsland2();

	@AttributeDefinition(name = "Sunny Islan 3", description = "Digital  Input M1 C3")
	String sunnyIsland3();

	@AttributeDefinition(name = "Sunny Islan 4", description = "Digital  Input M1 C4")
	String sunnyIsland4();

	@AttributeDefinition(name = "Sunny Islan 5", description = "Digital  Input M1 C5")
	String sunnyIsland5();

	@AttributeDefinition(name = "Sunny Island 6", description = "Digital  Input M1 C6")
	String sunnyIsland6();

	@AttributeDefinition(name = "Air Condition", description = "Digital Input M1 C7")
	String airCondtion();

	@AttributeDefinition(name = "BMU1", description = "Digital  Input M1 C8")
	String BMU1();

	@AttributeDefinition(name = "Main Switch/Fuse", description = "Digital Output M3 C1")
	String mainSwitchFuse();

	String webconsole_configurationFactory_nameHint() default "SMA SunnyIsland 6.0H[{id}]";

}