package io.openems.edge.sma;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import io.openems.edge.ess.api.Phase;

@ObjectClassDefinition( //
		name = "SMA SunnyIsland 6.0H", //
		description = "Implements the SMA SunnyIsland 6.0H energy storage system.")
@interface Config {
	String service_pid();

	String id() default "ess0";

	boolean enabled() default true;

	int modbusUnitId() default 3;

	Phase Phase() default Phase.L1;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	@AttributeDefinition(name = "Fire Detection ", description = "Address of the Fire Detection Contact Input Channel(io0/DigitalInputM2C3)")
	String inputFireDetection();

	@AttributeDefinition(name = "Battery Level Warning ", description = "Address of the Battery Level Warning(io0/DigitalInputM2C4)")
	String inputBatteryLevelWarning();

	@AttributeDefinition(name = "Door Operation ", description = "Address of the Door Operationg(io0/DigitalInputM2C2)")
	String inputDoorOperation();

	@AttributeDefinition(name = "Over Voltage Detection", description = "Address of the Over Voltage Detection(io0/DigitalInputM2C1)")
	String inputOverVoltageDetection();

	@AttributeDefinition(name = "Air Condition", description = "Address of the Power Switch Sunny Island 1 (io0/DigitalInputM1C7)")
	String InputAirCondtion();

	@AttributeDefinition(name = "BMU1", description = "Address of the Power Switch Sunny Island 1 (io0/DigitalInputM1C8)")
	String InputBMU1();

	@AttributeDefinition(name = "Main Switch/Fuse", description = "Address of the Main Switch(io0/DigitalOutputM3C1)")
	String outputMainSwitch();

	String webconsole_configurationFactory_nameHint() default "SMA SunnyIsland 6.0H[{id}]";

}