<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
package io.openems.edge.meter.hager.ecr380d;
========
package io.openems.edge.fluidcooling.hydac;
>>>>>>>> 202dc514d2 ([Edge] Industrial XL: Hydac Cooling unit as standalone component & improvements (#3205)):io.openems.edge.fluidcooling.hydac/src/io/openems/edge/fluidcooling/hydac/Config.java

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Meter Hager ECR380D", //
		description = "Implements the Hager ECR380D meter.")
@interface Config {
========
import io.openems.edge.common.startstop.StartStopConfig;

@ObjectClassDefinition(//
		name = "Cooling Unit Hydac", //
		description = "Implements the cooling unit Hydac")
public @interface Config {
>>>>>>>> 202dc514d2 ([Edge] Industrial XL: Hydac Cooling unit as standalone component & improvements (#3205)):io.openems.edge.fluidcooling.hydac/src/io/openems/edge/fluidcooling/hydac/Config.java

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
	@AttributeDefinition(name = "Meter-Type", description = "What is measured by this Meter?")
	MeterType type() default MeterType.PRODUCTION;
========
	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;
>>>>>>>> 202dc514d2 ([Edge] Industrial XL: Hydac Cooling unit as standalone component & improvements (#3205)):io.openems.edge.fluidcooling.hydac/src/io/openems/edge/fluidcooling/hydac/Config.java

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";
========
	@AttributeDefinition(name = "Temperature Setpoint", description = "The setpoint for the cooling temperature. Scaling 0,01 (2500 = 25 Degree)")
	int temperatureSetpoint() default 2500;
>>>>>>>> 202dc514d2 ([Edge] Industrial XL: Hydac Cooling unit as standalone component & improvements (#3205)):io.openems.edge.fluidcooling.hydac/src/io/openems/edge/fluidcooling/hydac/Config.java

	String webconsole_configurationFactory_nameHint() default "Meter Hager ECR380D [{id}]";
}
