package io.openems.edge.evcs.evtec;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "EVCS EVTEC", //
		description = "Implementation of the EVTEC electic vehicle charging station")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "evcs0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device. (2= first plug charger, 3 = second plug charger, 1 = station info)")
	int modbusUnitId() default 2;

	@AttributeDefinition(name = "Minimum current", description = "Minimum current of the Charger in mA for charging.", required = true)
	int minHwCurrent() default 6000;

	@AttributeDefinition(name = "Maximum current", description = "Maximmum current of the Charger in mA for charging.", required = true)
	int maxHwCurrent() default 16000;

	@AttributeDefinition(name = "Maximum current (Discharge)", description = "Maximmum current of the Charger in mA for discharging (must be a positive value)", required = true)
	int maxHwCurrentDischarge() default 16000;

	@AttributeDefinition(name = "Read only", description = "Only read values from device, don't send commands.")
	boolean readOnly() default false;

	@AttributeDefinition(name = "Debug Mode", description = "Activates the debug mode")
	boolean debugMode() default false;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "EVCS EVTEC [{id}]";

}