package io.openems.edge.meter.simulated;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.meter.api.MeterType;

@ObjectClassDefinition( 
		name = "Meter Simulated", //
		description = "Implements the simulated meter.")
@interface Config {
	String service_pid(); 

	String id() default "meter0"; 

	boolean enabled() default true; 

	@AttributeDefinition(name = "Meter-Type", description = "Grid, Production (=default), Consumption") 
	MeterType type() default MeterType.PRODUCTION; 

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id(); 

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId(); 

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default ""; 

	String webconsole_configurationFactory_nameHint() default "Meter Simulated [{id}]"; 
}



