package io.openems.edge.fenecon.dess.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "FENECON DESS Charger 1", //
		description = "The MPP tracker 1 implementation of a FENECON DESS (PRO Hybrid, PRO Compact,...)")
@interface Config1 {

	String id() default "charger0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "FENECON DESS Charger 1 [{id}]";
}