package io.openems.edge.fenecon.pro.pvmeter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Pv Meter FENECON Pro", //
		description = "Implements the FENECON Pro energy storage system.")
@interface Config {
	String service_pid();

	String id() default "meter1";

	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id();

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "Pv Meter FENECON Pro[{id}]";
}