package io.openems.edge.project.controller.enbag.emergencymode;

import io.openems.edge.common.channel.doc.OptionsEnum;

public enum BatteryAndPvState implements OptionsEnum {
	UNDEFINED(-1, "Undefined"), //

	ESS1_EMPTY__ESS2_EMPTY__PV_UNKNOWN(0000, ""), //
	ESS1_EMPTY__ESS2_EMPTY__PV_SUFFICIENT(0001, ""), //
	ESS1_EMPTY__ESS2_EMPTY__PV_NOT_SUFFICIENT(0002, ""), //
	ESS1_EMPTY__ESS2_LOW__PV_UNKNOWN(0010, ""), //
	ESS1_EMPTY__ESS2_LOW__PV_SUFFICIENT(0011, ""), //
	ESS1_EMPTY__ESS2_LOW__PV_NOT_SUFFICIENT(0012, ""), //
	ESS1_EMPTY__ESS2_NORMAL__PV_UNKNOWN(0020, ""), //
	ESS1_EMPTY__ESS2_NORMAL__PV_SUFFICIENT(0021, ""), //
	ESS1_EMPTY__ESS2_NORMAL__PV_NOT_SUFFICIENT(0022, ""), //
	ESS1_EMPTY__ESS2_FULL__PV_UNKNOWN(0030, ""), //
	ESS1_EMPTY__ESS2_FULL__PV_SUFFICIENT(0031, ""), //
	ESS1_EMPTY__ESS2_FULL__PV_NOT_SUFFICIENT(0032, ""), //

	ESS1_LOW__ESS2_EMPTY__PV_UNKNOWN(0040, ""), //
	ESS1_LOW__ESS2_EMPTY__PV_SUFFICIENT(0041, ""), //
	ESS1_LOW__ESS2_EMPTY__PV_NOT_SUFFICIENT(0042, ""), //
	ESS1_LOW__ESS2_LOW__PV_UNKNOWN(0050, ""), //
	ESS1_LOW__ESS2_LOW__PV_SUFFICIENT(0051, ""), //
	ESS1_LOW__ESS2_LOW__PV_NOT_SUFFICIENT(0052, ""), //
	ESS1_LOW__ESS2_NORMAL__PV_UNKNOWN(0060, ""), //
	ESS1_LOW__ESS2_NORMAL__PV_SUFFICIENT(0061, ""), //
	ESS1_LOW__ESS2_NORMAL__PV_NOT_SUFFICIENT(0062, ""), //
	ESS1_LOW__ESS2_FULL__PV_UNKNOWN(0070, ""), //
	ESS1_LOW__ESS2_FULL__PV_SUFFICIENT(0071, ""), //
	ESS1_LOW__ESS2_FULL__PV_NOT_SUFFICIENT(0072, ""), //

	ESS1_NORMAL__ESS2_EMPTY__PV_UNKNOWN(0100, ""), //
	ESS1_NORMAL__ESS2_EMPTY__PV_SUFFICIENT(0101, ""), //
	ESS1_NORMAL__ESS2_EMPTY__PV_NOT_SUFFICIENT(0102, ""), //
	ESS1_NORMAL__ESS2_LOW__PV_UNKNOWN(0110, ""), //
	ESS1_NORMAL__ESS2_LOW__PV_SUFFICIENT(0111, ""), //
	ESS1_NORMAL__ESS2_LOW__PV_NOT_SUFFICIENT(0112, ""), //
	ESS1_NORMAL__ESS2_NORMAL__PV_UNKNOWN(0120, ""), //
	ESS1_NORMAL__ESS2_NORMAL__PV_SUFFICIENT(0121, ""), //
	ESS1_NORMAL__ESS2_NORMAL__PV_NOT_SUFFICIENT(0122, ""), //
	ESS1_NORMAL__ESS2_FULL__PV_UNKNOWN(0130, ""), //
	ESS1_NORMAL__ESS2_FULL__PV_SUFFICIENT(0131, ""), //
	ESS1_NORMAL__ESS2_FULL__PV_NOT_SUFFICIENT(0132, ""), //

	ESS1_FULL__ESS2_EMPTY__PV_UNKNOWN(0140, ""), //
	ESS1_FULL__ESS2_EMPTY__PV_SUFFICIENT(0141, ""), //
	ESS1_FULL__ESS2_EMPTY__PV_NOT_SUFFICIENT(0142, ""), //
	ESS1_FULL__ESS2_LOW__PV_UNKNOWN(0150, ""), //
	ESS1_FULL__ESS2_LOW__PV_SUFFICIENT(0151, ""), //
	ESS1_FULL__ESS2_LOW__PV_NOT_SUFFICIENT(0152, ""), //
	ESS1_FULL__ESS2_NORMAL__PV_UNKNOWN(0160, ""), //
	ESS1_FULL__ESS2_NORMAL__PV_SUFFICIENT(0161, ""), //
	ESS1_FULL__ESS2_NORMAL__PV_NOT_SUFFICIENT(0162, ""), //
	ESS1_FULL__ESS2_FULL__PV_UNKNOWN(0170, ""), //
	ESS1_FULL__ESS2_FULL__PV_SUFFICIENT(0171, ""), //
	ESS1_FULL__ESS2_FULL__PV_NOT_SUFFICIENT(0172, "");

	private final int value;
	private final String name;

	private BatteryAndPvState(int value, String name) {
		this.value = value;
		this.name = name;
	}

	@Override
	public int getValue() {
		return value;
	}

	@Override
	public String getName() {
		return name;
	}

	@Override
	public OptionsEnum getUndefined() {
		return UNDEFINED;
	}
}