package io.openems.edge.project.controller.enbag.emergencymode;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Controller Emergency Cluster Mode", //
		description = "Switches the emergency power to next storage system when battery is empty.")
@interface Config {
	String service_pid();

	String id() default "ctrlEmergencyClusterMode0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Allow Charge from AC", description = "")
	boolean allowChargeFromAC() default true;

	@AttributeDefinition(name = "Grid Feed Limitation", description = "")
	boolean gridFeedLimitation() default true;

	@AttributeDefinition(name = "Is Remote Controlled", description = "")
	boolean isRemoteControlled() default true;

	@AttributeDefinition(name = "Remote Start", description = "")
	boolean remoteStart() default true;

	@AttributeDefinition(name = "Max Grid Feed Power", description = "")
	int maxGridFeedPower();

	@AttributeDefinition(name = "Remote Active Powerr", description = "")
	int remoteActivePower();

	// devices
	// Solar Log
	@AttributeDefinition(name = "PV-Inverter-ID", description = "ID of PV-Inverter device.")
	String pv_inverter_id();

	@AttributeDefinition(name = "PV-Inverter target filter", description = "This is auto-generated by 'PV-Inverter-ID'.")
	String pv_inverter_target() default "";

	// wago
	// Q1 - backupEssSwitch
	@AttributeDefinition(name = "Q1 Input Channel", description = "Channel address of the Q1 Digital Input that should be switched")
	String Q1_inputChannelAddress();

	@AttributeDefinition(name = "Q1 Input component target filter", description = "This is auto-generated by 'Q1 Input Channel'.")
	String Q1_inputComponent_target() default "";

	@AttributeDefinition(name = "Q1 Output Channel", description = "Channel address of the Q1 Digital Output that should be switched")
	String Q1_outputChannelAddress();

	@AttributeDefinition(name = "Q1 Output component target filter", description = "This is auto-generated by 'Q1 Output Channel'.")
	String Q1_outputComponent_target() default "";

	// Q2 - primaryEssSwitch
	@AttributeDefinition(name = "Q2 Input Channel", description = "Channel address of the Q2 Digital Input that should be switched")
	String Q2_inputChannelAddress();

	@AttributeDefinition(name = "Q2 Input component target filter", description = "This is auto-generated by 'Q2 Input Channel'.")
	String Q2_inputComponent_target() default "";

	@AttributeDefinition(name = "Q2 Output Channel", description = "Channel address of the Q2 Digital Output that should be switched")
	String Q2_outputChannelAddress();

	@AttributeDefinition(name = "Q2 Output component target filter", description = "This is auto-generated by 'Q2 Output Channel'.")
	String Q2_outputComponent_target() default "";

	// Q3 - pvOffGridSwitch
	@AttributeDefinition(name = "Q3 Input Channel", description = "Channel address of the Q3 Digital Input that should be switched")
	String Q3_inputChannelAddress();

	@AttributeDefinition(name = "Q3 Input component target filter", description = "This is auto-generated by 'Q3 Input Channel'.")
	String Q3_inputComponent_target() default "";

	@AttributeDefinition(name = "Q3 Output Channel", description = "Channel address of the Q3 Digital Output that should be switched")
	String Q3_outputChannelAddress();

	@AttributeDefinition(name = "Q3 Output component target filter", description = "This is auto-generated by 'Q3 Output Channel'.")
	String Q3_outputComponent_target() default "";

	// Q4 - pvOnGridSwitch
	@AttributeDefinition(name = "Q4 Input Channel", description = "Channel address of the Q4 Digital Input that should be switched")
	String Q4_inputChannelAddress();

	@AttributeDefinition(name = "Q4 Input component target filter", description = "This is auto-generated by 'Q4 Input Channel'.")
	String Q4_inputComponent_target() default "";

	@AttributeDefinition(name = "Q4 Output Channel", description = "Channel address of the Q4 Digital Output that should be switched")
	String Q4_outputChannelAddress();

	@AttributeDefinition(name = "Q4 Output component target filter", description = "This is auto-generated by 'Q4 Output Channel'.")
	String Q4_outputComponent_target() default "";

	// meters
	@AttributeDefinition(name = "Grid-Meter-ID", description = "ID of the Grid-Meter.")
	String grid_meter_id();

	@AttributeDefinition(name = "Grid-Meter target filter", description = "This is auto-generated by 'Grid-Meter-ID'.")
	String grid_meter_target() default "";

	@AttributeDefinition(name = "PV-Meter-ID", description = "ID of the PV-Meter.")
	String pv_meter_id();

	@AttributeDefinition(name = "PV-Meter target filter", description = "This is auto-generated by 'PV-Meter-ID'.")
	String pv_meter_target() default "";

	// esss
	@AttributeDefinition(name = "Ess2-ID", description = "ID of primary Ess device.")
	String ess2_id();

	@AttributeDefinition(name = "Ess2 target filter", description = "This is auto-generated by 'Ess2-ID'.")
	String ess2_target() default "";

	@AttributeDefinition(name = "Ess1-ID", description = "ID of Ess1 device.")
	String ess1_id();

	@AttributeDefinition(name = "Ess1 target filter", description = "This is auto-generated by 'Ess1-ID'.")
	String ess1_target() default "";

	String webconsole_configurationFactory_nameHint() default "Controller Emergency Cluster Mode [{id}]";
}
