package io.openems.edge.controller.ess.syncactivepower;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
	name = "Controller Ess SyncActivePower", //
	description = "Synchronizes the active power of a managed Ess with another Ess")
@interface Config {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
    String id() default "ctrlEssSyncActivePower0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
    String alias() default "";

    @AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "Read-only Ess", description = "ID of the ESS we can only read")
    String readOnlyEss_id();

    @AttributeDefinition(name = "Ess-ID", description = "ID of the Ess, which will be synchronized with the controlled ESS")
    String managedEss_id();

    @AttributeDefinition(name = "min SOC Read-only", description = "Ess does not synchronize with charging Read-Only Ess, if its SOC is below this value")
    int minSocReadOnly() default 20;

    @AttributeDefinition(name = "Lower power threshold", description = "If active power in Watt of Read-only Ess is below this threshold, the controller stops")
    int lowerThreshold() default 300;

    @AttributeDefinition(name = "Read only Ess target filter", description = "This is auto-generated by 'Regulating ESS'.")
    String readOnlyEss_target() default "(enabled=true)";

    @AttributeDefinition(name = "Delay after charging/discharging switch", description = "Delay in seconds, if readOnlyEss changes from charging to discharging or vice versa.")
    int delay() default 5;

    @AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
    String managedEss_target() default "(enabled=true)";

    String webconsole_configurationFactory_nameHint() default "Controller Ess Syncactivepower [{id}]";

}