#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy default config files if they don't exist
rsync -av --chown=abc:abc --ignore-existing /defaults/nginx/ /etc/nginx/

mkdir -p /etc/nginx/site-confs

if [[ "$WEBSOCKET_HOST" == "<hostname>" ]]; then
    echo ""
    echo "WEBSOCKET_HOST contains <hostname> placeholder, replace it with the actual hostname or IP address of the Docker host."
    sleep infinity
fi

for file in /etc/nginx/site-confs/80-*.tpl; do
    env_template="$file"
    env_file="/etc/nginx/site-confs/$(basename "${file%.tpl}")"
    rm -f "$env_file";
    eval "cat <<< \"$(<$env_template)\"" 2> /dev/null > $env_file;
    sed -i '1i# This file might be deleted after the next restart'  "$env_file";
done

case "${USE_SECURE_POROTOCOL^^}" in TRUE|T|YES|Y|1)
    for file in /etc/nginx/site-confs/443-*.tpl; do
        env_template="$file"
        env_file="/etc/nginx/site-confs/$(basename "${file%.tpl}")"
        rm -f "$env_file";
        eval "cat <<< \"$(<$env_template)\"" 2> /dev/null > $env_file;
        sed -i '1i# This file might be deleted after the next restart'  "$env_file";
    done
    ;;
esac

# copy pre-generated dhparams or generate if needed
if [[ ! -f /etc/nginx/dhparams.pem ]]; then
    rsync -av --chown=abc:abc /defaults/nginx/dhparams.pem.sample /etc/nginx/dhparams.pem
fi

if ! grep -q 'PARAMETERS' "/etc/nginx/dhparams.pem"; then
    curl -o /etc/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi
