#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy default config files if they don't exist
rsync -av --chown=abc:abc --ignore-existing /defaults/nginx/ /etc/nginx/

mkdir -p /etc/nginx/site-confs

if [[ "$WEBSOCKET_HOST" == "<hostname>" ]]; then
    echo ""
    echo "WEBSOCKET_HOST contains <hostname> placeholder, replace it with the actual hostname or IP address of the Docker host."
    sleep infinity
fi

if [[ "$WEBSOCKET_SECURE_POROTOCOL^^" == "TRUE" ]]; then
    env_template="/defaults/sites-templates/443-openems.conf.tpl"
    env_file="/etc/nginx/site-confs/443-openems.conf"
else
    env_template="/defaults/sites-templates/80-openems.conf.tpl"
    env_file="/etc/nginx/site-confs/80-openems.conf"
fi
eval "cat <<< \"$(<$env_template)\"" 2> /dev/null > $env_file;

# copy pre-generated dhparams or generate if needed
if [[ ! -f /etc/nginx/dhparams.pem ]]; then
    rsync -av --chown=abc:abc /defaults/nginx/dhparams.pem.sample /etc/nginx/dhparams.pem
fi

if ! grep -q 'PARAMETERS' "/etc/nginx/dhparams.pem"; then
    curl -o /etc/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi
