package io.openems.impl.device.commercial;

import io.openems.api.channel.thingstate.WarningEnum;

public enum WarningCharger implements WarningEnum{
	CurrentSamplingChannelAbnormityOnHighVoltageSide(0), CurrentSamplingChannelAbnormityOnLowVoltageSide(1), BmsDCDC1EEPROMParametersOverRange(2),EEPROMParametersOverRange(3), UpdateEEPROMFailed(4),
	ReadEEPROMFailed(5), CurrentSamplingChannelAbnormityBeforeInductance(6), ReactorPowerDecreaseCausedByOvertemperature(7), IGBTPowerDecreaseCausedByOvertemperature(8),
	TemperatureChanel3PowerDecreaseCausedByOvertemperature(9), TemperatureChanel4PowerDecreaseCausedByOvertemperature(10), TemperatureChanel5PowerDecreaseCausedByOvertemperature(11),
	TemperatureChanel6PowerDecreaseCausedByOvertemperature(12), TemperatureChanel7PowerDecreaseCausedByOvertemperature(13), TemperatureChanel8PowerDecreaseCausedByOvertemperature(14),
	Fan1StopFailed(15), Fan2StopFailed(16), Fan3StopFailed(17), Fan4StopFailed(18), Fan1StartupFailed(19), Fan2StartupFailed(20), Fan3StartupFailed(21), Fan4StartupFailed(22),
	HighVoltageSideOvervoltage(23), HighVoltageSideUndervoltage(24), HighVoltageSideVoltageChangeUnconventionally(25),CurrentAbnormityBeforeDCConverterWorkOnHighVoltageSide(26),
	CurrentAbnormityBeforeDCConverterWorkOnLowVoltageSXide(27), InitialDutyRatioAbnormityBeforeDCConverterWork(28),VoltageAbnormityBeforeDCConverterWorkOnHighVoltageSide(29),
	VoltageAbnormityBeforeDCConverterWorkOnLowVoltageSide(30), HighVoltageBreakerInspectionAbnormity(31),LowVoltageBreakerInspectionAbnormity(32), BsmDCDC5DCPrechargeContactorInspectionAbnormity(33),
	DCPrechargeContactorOpenUnsuccessfully(34), DCMainContactorInspectionAbnormity(35),DCMainContactorOpenUnsuccessfully(36), OutputContactorCloseUnsuccessfully(37), OutputContactorOpenUnsuccessfully(38),
	ACMainContactorCloseUnsuccessfully(39), ACMainContactorOpenUnsuccessfully(40),NegContactorOpenUnsuccessfully(41), NegContactorCloseUnsuccessfully(42), NegContactorStateAbnormal(43),
	BsmDCDC1CurrentSamplingChannelAbnormityOnHighVoltageSide(44), BsmDCDC1CurrentSamplingChannelAbnormityOnLowVoltageSide(45), BsmDCDC1EEPROMParametersOverRange(46), BsmDCDC1UpdateEEPROMFailed(47),
	BsmDCDC1ReadEEPROMFailed(48), BsmDCDC1CurrentSamplingChannelAbnormityBeforeInductance(49), BsmDCDC1ReactorPowerDecreaseCausedByOvertemperature(50), BsmDCDC1IGBTPowerDecreaseCausedByOvertemperature(51),
	BsmDCDC1TemperatureChanel3PowerDecreaseCausedByOvertemperature(52), BsmDCDC1TemperatureChanel4PowerDecreaseCausedByOvertemperature(53), BsmDCDC1TemperatureChanel5PowerDecreaseCausedByOvertemperature(54),
	BsmDCDC1TemperatureChanel6PowerDecreaseCausedByOvertemperature(55), BsmDCDC1TemperatureChanel7PowerDecreaseCausedByOvertemperature(56), BsmDCDC1TemperatureChanel8PowerDecreaseCausedByOvertemperature(57),
	BsmDCDC1Fan1StopFailed(58), BsmDCDC1Fan2StopFailed(59), BsmDCDC1Fan3StopFailed(60), BsmDCDC1Fan4StopFailed(61), BsmDCDC1Fan1StartupFailed(62), BsmDCDC1Fan2StartupFailed(63), BsmDCDC1Fan3StartupFailed(64),
	BsmDCDC1Fan4StartupFailed(65), BsmDCDC1HighVoltageSideOvervoltage(66), BsmDCDC1HighVoltageSideUndervoltage(67), BsmDCDC1HighVoltageSideVoltageChangeUnconventionally(68), BmsDCDC1CurrentAbnormityBeforeDCConverterWorkOnHighVoltageSide(69),
	BmsDCDC1CurrentAbnormityBeforeDCConverterWorkOnLowVoltageSXide(70), BmsDCDC1InitialDutyRatioAbnormityBeforeDCConverterWork(71), BmsDCDC1VoltageAbnormityBeforeDCConverterWorkOnHighVoltageSide(72),
	BmsDCDC1VoltageAbnormityBeforeDCConverterWorkOnLowVoltageSide(73), BmsDCDC1HighVoltageBreakerInspectionAbnormity(74), BmsDCDC1LowVoltageBreakerInspectionAbnormity(75), BmsDCDC1BsmDCDC5DCPrechargeContactorInspectionAbnormity(76),
	BmsDCDC1DCPrechargeContactorOpenUnsuccessfully(77), BmsDCDC1DCMainContactorInspectionAbnormity(78), BmsDCDC1DCMainContactorOpenUnsuccessfully(79), BmsDCDC1OutputContactorCloseUnsuccessfully(80),
	BmsDCDC1OutputContactorOpenUnsuccessfully(81), BmsDCDC1ACMainContactorCloseUnsuccessfully(82), BmsDCDC1ACMainContactorOpenUnsuccessfully(83), BmsDCDC1NegContactorOpenUnsuccessfully(84),
	BmsDCDC1NegContactorCloseUnsuccessfully(85), BmsDCDC1NegContactorStateAbnormal(86), PvDCDCCurrentSamplingChannelAbnormityOnHighVoltageSide(87), PvDCDCCurrentSamplingChannelAbnormityOnLowVoltageSide(88),
	PvDCDCEEPROMParametersOverRange(89), PvDCDCUpdateEEPROMFailed(90), PvDCDCReadEEPROMFailed(91), PvDCDCCurrentSamplingChannelAbnormityBeforeInductance(92), PvDCDCReactorPowerDecreaseCausedByOvertemperature(93),
	PvDCDCIGBTPowerDecreaseCausedByOvertemperature(94), PvDCDCTemperatureChanel3PowerDecreaseCausedByOvertemperature(95), PvDCDCTemperatureChanel4PowerDecreaseCausedByOvertemperature(96), PvDCDCTemperatureChanel5PowerDecreaseCausedByOvertemperature(97),
	PvDCDCTemperatureChanel6PowerDecreaseCausedByOvertemperature(98), PvDCDCTemperatureChanel7PowerDecreaseCausedByOvertemperature(99), PvDCDCTemperatureChanel8PowerDecreaseCausedByOvertemperature(100),
	PvDCDCFan1StopFailed(101), PvDCDCFan2StopFailed(102), PvDCDCFan3StopFailed(103), PvDCDCFan4StopFailed(104), PvDCDCFan1StartupFailed(105), PvDCDCFan2StartupFailed(106), PvDCDCFan3StartupFailed(107),
	PvDCDCFan4StartupFailed(108), PvDCDCHighVoltageSideOvervoltage(109), PvDCDCHighVoltageSideUndervoltage(110), PvDCDCHighVoltageSideVoltageChangeUnconventionally(111), PvDCDCCurrentAbnormityBeforeDCConverterWorkOnHighVoltageSide(112),
	PvDCDCCurrentAbnormityBeforeDCConverterWorkOnLowVoltageSXide(113), PvDCDCInitialDutyRatioAbnormityBeforeDCConverterWork(114), PvDCDCVoltageAbnormityBeforeDCConverterWorkOnHighVoltageSide(115),
	PvDCDCVoltageAbnormityBeforeDCConverterWorkOnLowVoltageSide(116), PvDCDCHighVoltageBreakerInspectionAbnormity(117), PvDCDCLowVoltageBreakerInspectionAbnormity(118), PvDCDCBsmDCDC5DCPrechargeContactorInspectionAbnormity(119),
	PvDCDCDCPrechargeContactorOpenUnsuccessfully(120), PvDCDCDCMainContactorInspectionAbnormity(121), PvDCDCDCMainContactorOpenUnsuccessfully(122), PvDCDCOutputContactorCloseUnsuccessfully(123), PvDCDCOutputContactorOpenUnsuccessfully(124),
	PvDCDCACMainContactorCloseUnsuccessfully(125), PvDCDCACMainContactorOpenUnsuccessfully(126), PvDCDCNegContactorOpenUnsuccessfully(127), PvDCDCNegContactorCloseUnsuccessfully(128), PvDCDCNegContactorStateAbnormal(129),
	PvDCDC1CurrentSamplingChannelAbnormityOnHighVoltageSide(130), PvDCDC1CurrentSamplingChannelAbnormityOnLowVoltageSide(131), PvDCDC1EEPROMParametersOverRange(132), PvDCDC1UpdateEEPROMFailed(133), PvDCDC1ReadEEPROMFailed(134),
	PvDCDC1CurrentSamplingChannelAbnormityBeforeInductance(135), PvDCDC1ReactorPowerDecreaseCausedByOvertemperature(136), PvDCDC1IGBTPowerDecreaseCausedByOvertemperature(137), PvDCDC1TemperatureChanel3PowerDecreaseCausedByOvertemperature(138),
	PvDCDC1TemperatureChanel4PowerDecreaseCausedByOvertemperature(139), PvDCDC1TemperatureChanel5PowerDecreaseCausedByOvertemperature(140), PvDCDC1TemperatureChanel6PowerDecreaseCausedByOvertemperature(141), PvDCDC1TemperatureChanel7PowerDecreaseCausedByOvertemperature(142),
	PvDCDC1TemperatureChanel8PowerDecreaseCausedByOvertemperature(143), PvDCDC1Fan1StopFailed(144), PvDCDC1Fan2StopFailed(145), PvDCDC1Fan3StopFailed(146), PvDCDC1Fan4StopFailed(147), PvDCDC1Fan1StartupFailed(148), PvDCDC1Fan2StartupFailed(149),
	PvDCDC1Fan3StartupFailed(150), PvDCDC1Fan4StartupFailed(151), PvDCDC1HighVoltageSideOvervoltage(152), PvDCDC1HighVoltageSideUndervoltage(153), PvDCDC1HighVoltageSideVoltageChangeUnconventionally(154), PvDCDC1CurrentAbnormityBeforeDCConverterWorkOnHighVoltageSide(155),
	PvDCDC1CurrentAbnormityBeforeDCConverterWorkOnLowVoltageSXide(156), PvDCDC1InitialDutyRatioAbnormityBeforeDCConverterWork(157), PvDCDC1VoltageAbnormityBeforeDCConverterWorkOnHighVoltageSide(158), PvDCDC1VoltageAbnormityBeforeDCConverterWorkOnLowVoltageSide(159),
	PvDCDC1HighVoltageBreakerInspectionAbnormity(160), PvDCDC1LowVoltageBreakerInspectionAbnormity(161), PvDCDC1BsmDCDC5DCPrechargeContactorInspectionAbnormity(162), PvDCDC1DCPrechargeContactorOpenUnsuccessfully(163), PvDCDC1DCMainContactorInspectionAbnormity(164),
	PvDCDC1DCMainContactorOpenUnsuccessfully(165), PvDCDC1OutputContactorCloseUnsuccessfully(166), PvDCDC1OutputContactorOpenUnsuccessfully(167), PvDCDC1ACMainContactorCloseUnsuccessfully(168), PvDCDC1ACMainContactorOpenUnsuccessfully(169),
	PvDCDC1NegContactorOpenUnsuccessfully(170), PvDCDC1NegContactorCloseUnsuccessfully(171), PvDCDC1NegContactorStateAbnormal(172);


	public final int value;

	private WarningCharger(int value) {
		this.value = value;
	}

	@Override
	public int getValue() {
		return this.value;
	}
}
