interface ThingStates { [clazz: string]: { 'faults'?: { [id: number]: string }, 'warnings'?: { [id: number]: string } } };

export const THING_STATES: ThingStates = {
  "io.openems.impl.device.simulator.SimulatorAsymmetricEss": {
    "faults": {
      "0": "Simulated Fault"
    },
    "warnings": {
      "0": "Simulated Warning"
    }
  },
  "io.openems.impl.device.commercial.FeneconCommercialEss": {
    "warnings": {
      "0": "Emergency Stop",
      "1": "Key Manual Stop",
      "2": "Transformer Phase B Temperature Sensor Invalidation",
      "4": "SD Memory Card Invalidation",
      "5": "Inverter Communication Abnormity",
      "6": "Battery Stack Communication Abnormity",
      "7": "Multifunctional Ammeter Communication Abnormity",
      "8": "Remote Communication Abnormity",
      "9": "PVDC 1 Communication Abnormity",
      "10": "PVDC 2 Communication Abnormity",
      "11": "Transformer Severe Overtemperature",
      "12": "DC Precharge Contactor Inspection Abnormity",
      "13": "DC Breaker 1 Inspection Abnormity",
      "14": "DC Breaker 2 Inspection Abnormity",
      "15": "AC Precharge Contactor Inspection Abnormity",
      "16": "AC Mainontactor Inspection Abnormity",
      "17": "AC Breaker Inspection Abnormity",
      "18": "DC Breaker 1 Close Unsuccessfully",
      "19": "DC Breaker 2 Close Unsuccessfully",
      "20": "Control Signal Close Abnormally Inspected By System",
      "21": "Control Signal Open Abnormally Inspected By System",
      "22": "Neutral Wire Contactor Close Unsuccessfully",
      "23": "Neutral Wire Contactor Open Unsuccessfully",
      "24": "Work Door Open",
      "25": "Emergency 1 Stop",
      "26": "AC Breaker Close Unsuccessfully",
      "27": "Control Switch Stop",
      "28": "General Overload",
      "29": "Severe Overload",
      "30": "Battery Current Over Limit",
      "31": "Power Decrease Caused By Overtemperature",
      "32": "Inverter General Overtemperature",
      "33": "AC Three Phase Current Unbalance",
      "34": "Restore Factory Setting Unsuccessfully",
      "35": "Pole Board Invalidation",
      "36": "Self Inspection Failed",
      "37": "Receive BMS Fault And Stop",
      "38": "Refrigeration Equipmentinvalidation",
      "39": "Large Temperature Difference Among IGBT Three Phases",
      "40": "EEPROM Parameters Over Range",
      "41": "EEPROM Parameters Backup Failed",
      "42": "DC Breaker Closeunsuccessfully",
      "43": "Communication Between Inverter And BSMU Disconnected",
      "44": "Communication Between Inverter And Master Disconnected",
      "45": "Communication Between Inverter And UC Disconnected",
      "46": "BMS Start Overtime Controlled By PCS",
      "47": "BMS Stop Overtime Controlled By PCS",
      "48": "Sync Signal Invalidation",
      "49": "Sync Signal Continuous Caputure Fault",
      "50": "Sync Signal Several Times Caputure Fault"
    },
    "faults": {
      "0": "DC Precharge Contactor Close Unsuccessfully",
      "1": "AC Precharge Contactor Close Unsuccessfully",
      "2": "AC Main Contactor Close Unsuccessfully",
      "3": "DC Electrical Breaker 1 Close Unsuccessfully",
      "4": "DC Main Contactor Close Unsuccessfully",
      "5": "AC Breaker Trip",
      "6": "AC Main Contactor Open When Running",
      "7": "DC Main Contactor Open When Running",
      "8": "AC Main Contactor Open Unsuccessfully",
      "9": "DC Electrical Breaker 1 Open Unsuccessfully",
      "10": "DC Main Contactor Open Unsuccessfully",
      "11": "Hardware PDP Fault",
      "12": "Master Stop Suddenly",
      "13": "DC Short Circuit Protection",
      "14": "DC Overvoltage Protection",
      "15": "DC Undervoltage Protection",
      "16": "DC Inverse No Connection Protection",
      "17": "DC Disconnection Protection",
      "18": "Commuting Voltage Abnormity Protection",
      "19": "DC Overcurrent Protection",
      "20": "Phase 1 Peak Current Over Limit Protection",
      "21": "Phase 2 Peak Current Over Limit Protection",
      "22": "Phase 3 Peak Current Over Limit Protection",
      "23": "Phase 1 Grid Voltage Sampling Invalidation",
      "24": "Phase 2 Virtual Current Over Limit Protection",
      "25": "Phase 3 Virtual Current Over Limit Protection",
      "26": "Phase 1 Grid Voltage Sampling Invalidation 2",
      "27": "Phase 2rid Voltage Sampling Invalidation",
      "28": "Phase 3 Grid Voltage Sampling Invalidation",
      "29": "Phase 1 Invert Voltage Sampling Invalidation",
      "30": "Phase 2 Invert Voltage Sampling Invalidation",
      "31": "Phase 3 Invert Voltage Sampling Invalidation",
      "32": "AC Current Sampling Invalidation",
      "33": "DC Current Sampling Invalidation",
      "34": "Phase 1 Overtemperature Protection",
      "35": "Phase 2 Overtemperature Protection",
      "36": "Phase 3 Overtemperature Protection",
      "37": "Phase 1 Temperature Sampling Invalidation",
      "38": "Phase 2 Temperature Sampling Invalidation",
      "39": "Phase 3 Temperature Sampling Invalidation",
      "40": "Phase 1 Precharge Unmet Protection",
      "41": "Phase 2 Precharge Unmet Protection",
      "42": "Phase 3 Precharge Unmet Protection",
      "43": "Unadaptable Phase Sequence Error Protection",
      "44": "DSP Protection",
      "45": "Phase 1 Grid Voltage Severe Overvoltage Protection",
      "46": "Phase 1 Grid Voltage General Overvoltage Protection",
      "47": "Phase 2 Grid Voltage Severe Overvoltage Protection",
      "48": "Phase 2 Grid Voltage General Overvoltage Protection",
      "49": "Phase 3 Grid Voltage Severe Overvoltage Protection",
      "50": "Phase 3 Grid Voltage General Overvoltage Protection",
      "51": "Phase 1 Grid Voltage Severe Undervoltage Protection",
      "52": "Phase 1 Grid Voltage General Undervoltage Protection",
      "53": "Phase 2 Grid Voltage Severe Undervoltage Protection",
      "54": "Phase 2 Grid Voltage General Undervoltage Protection",
      "55": "Phase 3 Grid Voltage Severe Undervoltage Protection",
      "56": "Phase 3 Grid Voltage General Undervoltage Protection",
      "57": "Severe Overfrequncy Protection",
      "58": "General Overfrequncy Protection",
      "59": "Severe Underfrequncy Protection",
      "60": "Generals Underfrequncy Protection",
      "61": "Phase 1 Gridloss",
      "62": "Phase 2 Gridloss",
      "63": "Phase 3 Gridloss",
      "64": "Islanding Protection",
      "65": "Phase 1 Under Voltage Ride Through",
      "66": "Phase 2 Under Voltage Ride Through",
      "67": "Phase 3 Under Voltage Ride Through",
      "68": "Phase 1 Inverter Voltage Severe Overvoltage Protection",
      "69": "Phase 1 Inverter Voltage General Overvoltage Protection",
      "70": "Phase 2 Inverter Voltage Severe Overvoltage Protection",
      "71": "Phase 2 Inverter Voltage General Overvoltage Protection",
      "72": "Phase 3 Inverter Voltage Severe Overvoltage Protection",
      "73": "Phase 3 Inverter Voltage General Overvoltage Protection",
      "74": "Inverter Peak Voltage High Protection Cause By AC Disconnect"
    }
  },
  "io.openems.impl.device.commercial.FeneconCommercialCharger": {
    "warnings": {
      "0": "Current Sampling Channel Abnormity On High Voltage Side",
      "1": "Current Sampling Channel Abnormity On Low Voltage Side",
      "2": "Bms DCDC 1 EEPROM Parameters Over Range",
      "3": "EEPROM Parameters Over Range",
      "4": "Update EEPROM Failed",
      "5": "Read EEPROM Failed",
      "6": "Current Sampling Channel Abnormity Before Inductance",
      "7": "Reactor Power Decrease Caused By Overtemperature",
      "8": "IGBT Power Decrease Caused By Overtemperature",
      "9": "Temperature Chanel 3 Power Decrease Caused By Overtemperature",
      "10": "Temperature Chanel 4 Power Decrease Caused By Overtemperature",
      "11": "Temperature Chanel 5 Power Decrease Caused By Overtemperature",
      "12": "Temperature Chanel 6 Power Decrease Caused By Overtemperature",
      "13": "Temperature Chanel 7 Power Decrease Caused By Overtemperature",
      "14": "Temperature Chanel 8 Power Decrease Caused By Overtemperature",
      "15": "Fan 1 Stop Failed",
      "16": "Fan 2 Stop Failed",
      "17": "Fan 3 Stop Failed",
      "18": "Fan 4 Stop Failed",
      "19": "Fan 1 Startup Failed",
      "20": "Fan 2 Startup Failed",
      "21": "Fan 3 Startup Failed",
      "22": "Fan 4 Startup Failed",
      "23": "High Voltage Side Overvoltage",
      "24": "High Voltage Side Undervoltage",
      "25": "High Voltage Side Voltage Change Unconventionally",
      "26": "Current Abnormity Before DC Converter Work On High Voltage Side",
      "27": "Current Abnormity Before DC Converter Work On Low Voltage S Xide",
      "28": "Initial Duty Ratio Abnormity Before DC Converter Work",
      "29": "Voltage Abnormity Before DC Converter Work On High Voltage Side",
      "30": "Voltage Abnormity Before DC Converter Work On Low Voltage Side",
      "31": "High Voltage Breaker Inspection Abnormity",
      "32": "Low Voltage Breaker Inspection Abnormity",
      "33": "Bsm DCDC 5 DC Precharge Contactor Inspection Abnormity",
      "34": "DC Precharge Contactor Open Unsuccessfully",
      "35": "DC Main Contactor Inspection Abnormity",
      "36": "DC Main Contactor Open Unsuccessfully",
      "37": "Output Contactor Close Unsuccessfully",
      "38": "Output Contactor Open Unsuccessfully",
      "39": "AC Main Contactor Close Unsuccessfully",
      "40": "AC Main Contactor Open Unsuccessfully",
      "41": "Neg Contactor Open Unsuccessfully",
      "42": "Neg Contactor Close Unsuccessfully",
      "43": "Neg Contactor State Abnormal",
      "44": "Bsm DCDC 1 Current Sampling Channel Abnormity On High Voltage Side",
      "45": "Bsm DCDC 1 Current Sampling Channel Abnormity On Low Voltage Side",
      "46": "Bsm DCDC 1 EEPROM Parameters Over Range",
      "47": "Bsm DCDC 1 Update EEPROM Failed",
      "48": "Bsm DCDC 1 Read EEPROM Failed",
      "49": "Bsm DCDC 1 Current Sampling Channel Abnormity Before Inductance",
      "50": "Bsm DCDC 1 Reactor Power Decrease Caused By Overtemperature",
      "51": "Bsm DCDC 1 IGBT Power Decrease Caused By Overtemperature",
      "52": "Bsm DCDC 1 Temperature Chanel 3 Power Decrease Caused By Overtemperature",
      "53": "Bsm DCDC 1 Temperature Chanel 4 Power Decrease Caused By Overtemperature",
      "54": "Bsm DCDC 1 Temperature Chanel 5 Power Decrease Caused By Overtemperature",
      "55": "Bsm DCDC 1 Temperature Chanel 6 Power Decrease Caused By Overtemperature",
      "56": "Bsm DCDC 1 Temperature Chanel 7 Power Decrease Caused By Overtemperature",
      "57": "Bsm DCDC 1 Temperature Chanel 8 Power Decrease Caused By Overtemperature",
      "58": "Bsm DCDC 1 Fan 1 Stop Failed",
      "59": "Bsm DCDC 1 Fan 2 Stop Failed",
      "60": "Bsm DCDC 1 Fan 3 Stop Failed",
      "61": "Bsm DCDC 1 Fan 4 Stop Failed",
      "62": "Bsm DCDC 1 Fan 1 Startup Failed",
      "63": "Bsm DCDC 1 Fan 2 Startup Failed",
      "64": "Bsm DCDC 1 Fan 3 Startup Failed",
      "65": "Bsm DCDC 1 Fan 4 Startup Failed",
      "66": "Bsm DCDC 1 High Voltage Side Overvoltage",
      "67": "Bsm DCDC 1 High Voltage Side Undervoltage",
      "68": "Bsm DCDC 1 High Voltage Side Voltage Change Unconventionally",
      "69": "Bms DCDC 1 Current Abnormity Before DC Converter Work On High Voltage Side",
      "70": "Bms DCDC 1 Current Abnormity Before DC Converter Work On Low Voltage S Xide",
      "71": "Bms DCDC 1 Initial Duty Ratio Abnormity Before DC Converter Work",
      "72": "Bms DCDC 1 Voltage Abnormity Before DC Converter Work On High Voltage Side",
      "73": "Bms DCDC 1 Voltage Abnormity Before DC Converter Work On Low Voltage Side",
      "74": "Bms DCDC 1 High Voltage Breaker Inspection Abnormity",
      "75": "Bms DCDC 1 Low Voltage Breaker Inspection Abnormity",
      "76": "Bms DCDC 1 Bsm DCDC 5 DC Precharge Contactor Inspection Abnormity",
      "77": "Bms DCDC 1 DC Precharge Contactor Open Unsuccessfully",
      "78": "Bms DCDC 1 DC Main Contactor Inspection Abnormity",
      "79": "Bms DCDC 1 DC Main Contactor Open Unsuccessfully",
      "80": "Bms DCDC 1 Output Contactor Close Unsuccessfully",
      "81": "Bms DCDC 1 Output Contactor Open Unsuccessfully",
      "82": "Bms DCDC 1 AC Main Contactor Close Unsuccessfully",
      "83": "Bms DCDC 1 AC Main Contactor Open Unsuccessfully",
      "84": "Bms DCDC 1 Neg Contactor Open Unsuccessfully",
      "85": "Bms DCDC 1 Neg Contactor Close Unsuccessfully",
      "86": "Bms DCDC 1 Neg Contactor State Abnormal",
      "87": "Pv DCDC Current Sampling Channel Abnormity On High Voltage Side",
      "88": "Pv DCDC Current Sampling Channel Abnormity On Low Voltage Side",
      "89": "Pv DCDCEEPROM Parameters Over Range",
      "90": "Pv DCDC Update EEPROM Failed",
      "91": "Pv DCDC Read EEPROM Failed",
      "92": "Pv DCDC Current Sampling Channel Abnormity Before Inductance",
      "93": "Pv DCDC Reactor Power Decrease Caused By Overtemperature",
      "94": "Pv DCDCIGBT Power Decrease Caused By Overtemperature",
      "95": "Pv DCDC Temperature Chanel 3 Power Decrease Caused By Overtemperature",
      "96": "Pv DCDC Temperature Chanel 4 Power Decrease Caused By Overtemperature",
      "97": "Pv DCDC Temperature Chanel 5 Power Decrease Caused By Overtemperature",
      "98": "Pv DCDC Temperature Chanel 6 Power Decrease Caused By Overtemperature",
      "99": "Pv DCDC Temperature Chanel 7 Power Decrease Caused By Overtemperature",
      "100": "Pv DCDC Temperature Chanel 8 Power Decrease Caused By Overtemperature",
      "101": "Pv DCDC Fan 1 Stop Failed",
      "102": "Pv DCDC Fan 2 Stop Failed",
      "103": "Pv DCDC Fan 3 Stop Failed",
      "104": "Pv DCDC Fan 4 Stop Failed",
      "105": "Pv DCDC Fan 1 Startup Failed",
      "106": "Pv DCDC Fan 2 Startup Failed",
      "107": "Pv DCDC Fan 3 Startup Failed",
      "108": "Pv DCDC Fan 4 Startup Failed",
      "109": "Pv DCDC High Voltage Side Overvoltage",
      "110": "Pv DCDC High Voltage Side Undervoltage",
      "111": "Pv DCDC High Voltage Side Voltage Change Unconventionally",
      "112": "Pv DCDC Current Abnormity Before DC Converter Work On High Voltage Side",
      "113": "Pv DCDC Current Abnormity Before DC Converter Work On Low Voltage S Xide",
      "114": "Pv DCDC Initial Duty Ratio Abnormity Before DC Converter Work",
      "115": "Pv DCDC Voltage Abnormity Before DC Converter Work On High Voltage Side",
      "116": "Pv DCDC Voltage Abnormity Before DC Converter Work On Low Voltage Side",
      "117": "Pv DCDC High Voltage Breaker Inspection Abnormity",
      "118": "Pv DCDC Low Voltage Breaker Inspection Abnormity",
      "119": "Pv DCDC Bsm DCDC 5 DC Precharge Contactor Inspection Abnormity",
      "120": "Pv DCDCDC Precharge Contactor Open Unsuccessfully",
      "121": "Pv DCDCDC Main Contactor Inspection Abnormity",
      "122": "Pv DCDCDC Main Contactor Open Unsuccessfully",
      "123": "Pv DCDC Output Contactor Close Unsuccessfully",
      "124": "Pv DCDC Output Contactor Open Unsuccessfully",
      "125": "Pv DCDCAC Main Contactor Close Unsuccessfully",
      "126": "Pv DCDCAC Main Contactor Open Unsuccessfully",
      "127": "Pv DCDC Neg Contactor Open Unsuccessfully",
      "128": "Pv DCDC Neg Contactor Close Unsuccessfully",
      "129": "Pv DCDC Neg Contactor State Abnormal",
      "130": "Pv DCDC 1 Current Sampling Channel Abnormity On High Voltage Side",
      "131": "Pv DCDC 1 Current Sampling Channel Abnormity On Low Voltage Side",
      "132": "Pv DCDC 1 EEPROM Parameters Over Range",
      "133": "Pv DCDC 1 Update EEPROM Failed",
      "134": "Pv DCDC 1 Read EEPROM Failed",
      "135": "Pv DCDC 1 Current Sampling Channel Abnormity Before Inductance",
      "136": "Pv DCDC 1 Reactor Power Decrease Caused By Overtemperature",
      "137": "Pv DCDC 1 IGBT Power Decrease Caused By Overtemperature",
      "138": "Pv DCDC 1 Temperature Chanel 3 Power Decrease Caused By Overtemperature",
      "139": "Pv DCDC 1 Temperature Chanel 4 Power Decrease Caused By Overtemperature",
      "140": "Pv DCDC 1 Temperature Chanel 5 Power Decrease Caused By Overtemperature",
      "141": "Pv DCDC 1 Temperature Chanel 6 Power Decrease Caused By Overtemperature",
      "142": "Pv DCDC 1 Temperature Chanel 7 Power Decrease Caused By Overtemperature",
      "143": "Pv DCDC 1 Temperature Chanel 8 Power Decrease Caused By Overtemperature",
      "144": "Pv DCDC 1 Fan 1 Stop Failed",
      "145": "Pv DCDC 1 Fan 2 Stop Failed",
      "146": "Pv DCDC 1 Fan 3 Stop Failed",
      "147": "Pv DCDC 1 Fan 4 Stop Failed",
      "148": "Pv DCDC 1 Fan 1 Startup Failed",
      "149": "Pv DCDC 1 Fan 2 Startup Failed",
      "150": "Pv DCDC 1 Fan 3 Startup Failed",
      "151": "Pv DCDC 1 Fan 4 Startup Failed",
      "152": "Pv DCDC 1 High Voltage Side Overvoltage",
      "153": "Pv DCDC 1 High Voltage Side Undervoltage",
      "154": "Pv DCDC 1 High Voltage Side Voltage Change Unconventionally",
      "155": "Pv DCDC 1 Current Abnormity Before DC Converter Work On High Voltage Side",
      "156": "Pv DCDC 1 Current Abnormity Before DC Converter Work On Low Voltage S Xide",
      "157": "Pv DCDC 1 Initial Duty Ratio Abnormity Before DC Converter Work",
      "158": "Pv DCDC 1 Voltage Abnormity Before DC Converter Work On High Voltage Side",
      "159": "Pv DCDC 1 Voltage Abnormity Before DC Converter Work On Low Voltage Side",
      "160": "Pv DCDC 1 High Voltage Breaker Inspection Abnormity",
      "161": "Pv DCDC 1 Low Voltage Breaker Inspection Abnormity",
      "162": "Pv DCDC 1 Bsm DCDC 5 DC Precharge Contactor Inspection Abnormity",
      "163": "Pv DCDC 1 DC Precharge Contactor Open Unsuccessfully",
      "164": "Pv DCDC 1 DC Main Contactor Inspection Abnormity",
      "165": "Pv DCDC 1 DC Main Contactor Open Unsuccessfully",
      "166": "Pv DCDC 1 Output Contactor Close Unsuccessfully",
      "167": "Pv DCDC 1 Output Contactor Open Unsuccessfully",
      "168": "Pv DCDC 1 AC Main Contactor Close Unsuccessfully",
      "169": "Pv DCDC 1 AC Main Contactor Open Unsuccessfully",
      "170": "Pv DCDC 1 Neg Contactor Open Unsuccessfully",
      "171": "Pv DCDC 1 Neg Contactor Close Unsuccessfully",
      "172": "Pv DCDC 1 Neg Contactor State Abnormal"
    },
    "faults": {
      "0": "High Voltage Side Of DC Converter Undervoltage",
      "1": "High Voltage Side Of DC Converter Overvoltage",
      "2": "Low Voltage Side Of DC Converter Undervoltage",
      "3": "Low Voltage Side Of DC Converter Overvoltage",
      "4": "High Voltage Side Of DC Converter Overcurrent Fault",
      "5": "Low Voltage Side Of DC Converter Overcurrent Fault",
      "6": "DC Converter IGBT Fault",
      "7": "DC Converter Precharge Unmet",
      "8": "BECU Communication Disconnected",
      "9": "DC Converter Communication Disconnected",
      "10": "Current Configuration Over Range",
      "11": "The Battery Request Stop",
      "12": "Overcurrent Relay Fault",
      "13": "Lightning Protection Device Fault",
      "14": "DC Converter Priamary Contactor Disconnected Abnormally",
      "15": "DC Disconnected Abnormally On Low Voltage Side Of DC Convetor",
      "16": "DC Convetor EEPROM Abnormity 1",
      "17": "DC Convetor EEPROM Abnormity 1 Second",
      "18": "EDC Convetor EEPROM Abnormity 1",
      "19": "DC Convertor General Overload",
      "20": "DC Short Circuit",
      "21": "Peak Pulse Current Protection",
      "22": "DC Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "23": "Effective Pulse Value Overhigh",
      "24": "DC Converte Severe Overload",
      "25": "DC Breaker Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "26": "DC Breaker Disconnect Abnormally On Low Voltage Side Of DC Convetor",
      "27": "DC Convetor Precharge Contactor Close Failed",
      "28": "DC Convetor Main Contactor Close Failed",
      "29": "AC Contactor State Abnormity Of DC Convetor",
      "30": "DC Convetor Emergency Stop",
      "31": "DC Converter Charging Gun Disconnected",
      "32": "DC Current Abnormity Before DC Convetor Work",
      "33": "Fu Se Disconnected",
      "34": "DC Converter Hardware Current Or Voltage Fault",
      "35": "DC Converter Crystal Oscillator Circuit Invalidation",
      "36": "DC Converter Reset Circuit Invalidation",
      "37": "DC Converter Sampling Circuit Invalidation",
      "38": "DC Converter Digital IO Circuit Invalidation",
      "39": "DC Converter PWM Circuit Invalidation",
      "40": "DC Converter X 5045 Circuit Invalidation",
      "41": "DC Converter CAN Circuit Invalidation",
      "42": "DC Converter Software AND Hardware Protection Circuit Invalidation",
      "43": "DC Converter Power Circuit Invalidation",
      "44": "DC Converter CPU Invalidation",
      "45": "DC Converter TINT 0 Interrupt Invalidation",
      "46": "DC Converter ADC Interrupt Invalidation",
      "47": "DC Converter CAPITN 4 Interrupt Invalidation",
      "48": "DC Converter CAPINT 6 Interrupt Invalidation",
      "49": "DC Converter T 3 PIN Tinterrupt Invalidation",
      "50": "DC Converter T 4 PIN Tinterrupt Invalidation",
      "51": "DC Converter PDPINTA Interrupt Invalidation",
      "52": "DC Converter T 1 PINT Interrupt Invalidation",
      "53": "DC Converter RESV Interrupt Invalidation",
      "54": "DC Converter 100us Task Invalidation",
      "55": "DC Converter Clock Invalidation",
      "56": "DC Converter EMS Memory Invalidation",
      "57": "DC Converter Exterior Communication Invalidation",
      "58": "DC Converter IO Interface Invalidation",
      "59": "DC Converter Input Voltage Bound Fault",
      "60": "DC Converter Outter Voltage Bound Fault",
      "61": "DC Converter Output Voltage Bound Fault",
      "62": "DC Converter Induct Current Bound Fault",
      "63": "DC Converter Input Current Bound Fault",
      "64": "DC Converter Output Current Bound Fault",
      "65": "DC Reactor Over Temperature",
      "66": "DCIGBT Over Temperature",
      "67": "DC Converter Chanel 3 Over Temperature",
      "68": "DC Converter Chanel 4 Over Temperature",
      "69": "DC Converter Chanel 5 Over Temperature",
      "70": "DC Converter Chanel 6 Over Temperature",
      "71": "DC Converter Chanel 7 Over Temperature",
      "72": "DC Converter Chanel 8 Over Temperature",
      "73": "DC Reactor Temperature Sampling Invalidation",
      "74": "DCIGBT Temperature Sampling Invalidation",
      "75": "DC Converter Chanel 3 Temperature Sampling Invalidation",
      "76": "DC Converter Chanel 4 Temperature Sampling Invalidation",
      "77": "DC Converter Chanel 5 Temperature Sampling Invalidation",
      "78": "DC Converter Chanel 6 Temperature Sampling Invalidation",
      "79": "DC Converter Chanel 7 Temperature Sampling Invalidation",
      "80": "DC Converter Chanel 8 Temperature Sampling Invalidation",
      "81": "DC Converter Inductance Current Sampling Invalidation",
      "82": "Current Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "83": "Voltage Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "84": "Insulation Inspection Fault",
      "85": "Neg Contactor Close Unsuccessly",
      "86": "Neg Contactor Cut When Running",
      "87": "Bms DCDC 1 High Voltage Side Of DC Converter Undervoltage",
      "88": "Bms DCDC 1 High Voltage Side Of DC Converter Overvoltage",
      "89": "Bms DCDC 1 Low Voltage Side Of DC Converter Undervoltage",
      "90": "Bms DCDC 1 Low Voltage Side Of DC Converter Overvoltage",
      "91": "Bms DCDC 1 High Voltage Side Of DC Converter Overcurrent Fault",
      "92": "Bms DCDC 1 Low Voltage Side Of DC Converter Overcurrent Fault",
      "93": "Bms DCDC 1 DC Converter IGBT Fault",
      "94": "Bms DCDC 1 DC Converter Precharge Unmet",
      "95": "Bms DCDC 1 BECU Communication Disconnected",
      "96": "Bms DCDC 1 DC Converter Communication Disconnected",
      "97": "Bms DCDC 1 Current Configuration Over Range",
      "98": "Bms DCDC 1 The Battery Request Stop",
      "99": "Bms DCDC 1 Overcurrent Relay Fault",
      "100": "Bms DCDC 1 Lightning Protection Device Fault",
      "101": "Bms DCDC 1 DC Converter Priamary Contactor Disconnected Abnormally",
      "102": "Bms DCDC 1 DC Disconnected Abnormally On Low Voltage Side Of DC Convetor",
      "103": "Bms DCDC 1 DC Convetor EEPROM Abnormity 1",
      "104": "Bms DCDC 1 DC Convetor EEPROM Abnormity 1 Second",
      "105": "Bms DCDC 1 EDC Convetor EEPROM Abnormity 1",
      "106": "Bsm DCDC 1 DC Convertor General Overload",
      "107": "Bsm DCDC 1 DC Short Circuit",
      "108": "Bsm DCDC 1 Peak Pulse Current Protection",
      "109": "Bsm DCDC 1 DC Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "110": "Bsm DCDC 1 Effective Pulse Value Overhigh",
      "111": "Bsm DCDC 1 DC Converte Severe Overload",
      "112": "Bsm DCDC 1 DC Breaker Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "113": "Bsm DCDC 1 DC Breaker Disconnect Abnormally On Low Voltage Side Of DC Convetor",
      "114": "Bsm DCDC 1 DC Convetor Precharge Contactor Close Failed",
      "115": "Bsm DCDC 1 DC Convetor Main Contactor Close Failed",
      "116": "Bsm DCDC 1 AC Contactor State Abnormity Of DC Convetor",
      "117": "Bsm DCDC 1 DC Convetor Emergency Stop",
      "118": "Bsm DCDC 1 DC Converter Charging Gun Disconnected",
      "119": "Bsm DCDC 1 DC Current Abnormity Before DC Convetor Work",
      "120": "Bsm DCDC 1 Fu Se Disconnected",
      "121": "Bsm DCDC 1 DC Converter Hardware Current Or Voltage Fault",
      "122": "Bms DCDC 1 DC Converter Crystal Oscillator Circuit Invalidation",
      "123": "Bms DCDC 1 DC Converter Reset Circuit Invalidation",
      "124": "Bms DCDC 1 DC Converter Sampling Circuit Invalidation",
      "125": "Bms DCDC 1 DC Converter Digital IO Circuit Invalidation",
      "126": "Bms DCDC 1 DC Converter PWM Circuit Invalidation",
      "127": "Bms DCDC 1 DC Converter X 5045 Circuit Invalidation",
      "128": "Bms DCDC 1 DC Converter CAN Circuit Invalidation",
      "129": "Bms DCDC 1 DC Converter Software AND Hardware Protection Circuit Invalidation",
      "130": "Bms DCDC 1 DC Converter Power Circuit Invalidation",
      "131": "Bms DCDC 1 DC Converter CPU Invalidation",
      "132": "Bms DCDC 1 DC Converter TINT 0 Interrupt Invalidation",
      "133": "Bms DCDC 1 DC Converter ADC Interrupt Invalidation",
      "134": "Bms DCDC 1 DC Converter CAPITN 4 Interrupt Invalidation",
      "135": "Bms DCDC 1 DC Converter CAPINT 6 Interrupt Invalidation",
      "136": "Bms DCDC 1 DC Converter T 3 PIN Tinterrupt Invalidation",
      "137": "Bms DCDC 1 DC Converter T 4 PIN Tinterrupt Invalidation",
      "138": "Bms DCDC 1 DC Converter PDPINTA Interrupt Invalidation",
      "139": "Bms DCDC 1 DC Converter T 1 PINT Interrupt Invalidation Second",
      "140": "Bms DCDC 1 DC Converter RESV Interrupt Invalidation",
      "141": "Bms DCDC 1 DC Converter 100us Task Invalidation",
      "142": "Bms DCDC 1 DC Converter Clock Invalidation",
      "143": "Bms DCDC 1 DC Converter EMS Memory Invalidation",
      "144": "Bms DCDC 1 DC Converter Exterior Communication Invalidation",
      "145": "Bms DCDC 1 DC Converter IO Interface Invalidation",
      "146": "Bms DCDC 1 DC Converter Input Voltage Bound Fault",
      "147": "Bms DCDC 1 DC Converter Outter Voltage Bound Fault",
      "148": "Bms DCDC 1 DC Converter Output Voltage Bound Fault",
      "149": "Bms DCDC 1 DC Converter Induct Current Bound Fault",
      "150": "Bms DCDC 1 DC Converter Input Current Bound Fault",
      "151": "Bms DCDC 1 DC Converter Output Current Bound Fault",
      "152": "Bms DCDC 1 DC Reactor Over Temperature",
      "153": "Bms DCDC 1 DCIGBT Over Temperature",
      "154": "Bms DCDC 1 DC Converter Chanel 3 Over Temperature",
      "155": "Bms DCDC 1 DC Converter Chanel 4 Over Temperature",
      "156": "Bms DCDC 1 DC Converter Chanel 5 Over Temperature",
      "157": "Bms DCDC 1 DC Converter Chanel 6 Over Temperature",
      "158": "Bms DCDC 1 DC Converter Chanel 7 Over Temperature",
      "159": "Bms DCDC 1 DC Converter Chanel 8 Over Temperature",
      "160": "Bms DCDC 1 DC Reactor Temperature Sampling Invalidation",
      "161": "Bms DCDC 1 DCIGBT Temperature Sampling Invalidation",
      "162": "Bms DCDC 1 DC Converter Chanel 3 Temperature Sampling Invalidation",
      "163": "Bms DCDC 1 DC Converter Chanel 4 Temperature Sampling Invalidation",
      "164": "Bms DCDC 1 DC Converter Chanel 5 Temperature Sampling Invalidation",
      "165": "Bms DCDC 1 DC Converter Chanel 6 Temperature Sampling Invalidation",
      "166": "Bms DCDC 1 DC Converter Chanel 7 Temperature Sampling Invalidation",
      "167": "Bms DCDC 1 DC Converter Chanel 8 Temperature Sampling Invalidation",
      "168": "Bms DCDC 1 DC Converter Inductance Current Sampling Invalidation",
      "169": "Bms DCDC 1 Current Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "170": "Bms DCDC 1 Voltage Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "171": "Bms DCDC 1 Insulation Inspection Fault",
      "172": "Bms DCDC 1 Neg Contactor Close Unsuccessly",
      "173": "Bms DCDC 1 Neg Contactor Cut When Running",
      "174": "Pv DCDC High Voltage Side Of DC Converter Undervoltage",
      "175": "Pv DCDC High Voltage Side Of DC Converter Overvoltage",
      "176": "Pv DCDC Low Voltage Side Of DC Converter Undervoltage",
      "177": "Pv DCDC Low Voltage Side Of DC Converter Overvoltage",
      "178": "Pv DCDC High Voltage Side Of DC Converter Overcurrent Fault",
      "179": "Pv DCDC Low Voltage Side Of DC Converter Overcurrent Fault",
      "180": "Pv DCDCDC Converter IGBT Fault",
      "181": "Pv DCDCDC Converter Precharge Unmet",
      "182": "Pv DCDCBECU Communication Disconnected",
      "183": "Pv DCDCDC Converter Communication Disconnected",
      "184": "Pv DCDC Current Configuration Over Range",
      "185": "Pv DCDC The Battery Request Stop",
      "186": "Pv DCDC Overcurrent Relay Fault",
      "187": "Pv DCDC Lightning Protection Device Fault",
      "188": "Pv DCDCDC Converter Priamary Contactor Disconnected Abnormally",
      "189": "Pv DCDCDC Disconnected Abnormally On Low Voltage Side Of DC Convetor",
      "190": "Pv DCDCDC Convetor EEPROM Abnormity 1",
      "191": "Pv DCDCDC Convetor EEPROM Abnormity 1 Second",
      "192": "Pv DCDCEDC Convetor EEPROM Abnormity 1",
      "193": "Pv DCDCDC Convertor General Overload",
      "194": "Pv DCDCDC Short Circuit",
      "195": "Pv DCDC Peak Pulse Current Protection",
      "196": "Pv DCDCDC Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "197": "Pv DCDC Effective Pulse Value Overhigh",
      "198": "Pv DCDCDC Converte Severe Overload",
      "199": "Pv DCDCDC Breaker Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "200": "Pv DCDCDC Breaker Disconnect Abnormally On Low Voltage Side Of DC Convetor",
      "201": "Pv DCDCDC Convetor Precharge Contactor Close Failed",
      "202": "Pv DCDCDC Convetor Main Contactor Close Failed",
      "203": "Pv DCDCAC Contactor State Abnormity Of DC Convetor",
      "204": "Pv DCDCDC Convetor Emergency Stop",
      "205": "Pv DCDCDC Converter Charging Gun Disconnected",
      "206": "Pv DCDCDC Current Abnormity Before DC Convetor Work",
      "207": "Pv DCDC Fu Se Disconnected",
      "208": "Pv DCDCDC Converter Hardware Current Or Voltage Fault",
      "209": "Pv DCDCDC Converter Crystal Oscillator Circuit Invalidation",
      "210": "Pv DCDCDC Converter Reset Circuit Invalidation",
      "211": "Pv DCDCDC Converter Sampling Circuit Invalidation",
      "212": "Pv DCDCDC Converter Digital IO Circuit Invalidation",
      "213": "Pv DCDCDC Converter PWM Circuit Invalidation",
      "214": "Pv DCDCDC Converter X 5045 Circuit Invalidation",
      "215": "Pv DCDCDC Converter CAN Circuit Invalidation",
      "216": "Pv DCDCDC Converter Software AND Hardware Protection Circuit Invalidation",
      "217": "Pv DCDCDC Converter Power Circuit Invalidation",
      "218": "Pv DCDCDC Converter CPU Invalidation",
      "219": "Pv DCDCDC Converter TINT 0 Interrupt Invalidation",
      "220": "Pv DCDCDC Converter ADC Interrupt Invalidation",
      "221": "Pv DCDCDC Converter CAPITN 4 Interrupt Invalidation",
      "222": "Pv DCDCDC Converter CAPINT 6 Interrupt Invalidation",
      "223": "Pv DCDCDC Converter T 3 PIN Tinterrupt Invalidation",
      "224": "Pv DCDCDC Converter T 4 PIN Tinterrupt Invalidation",
      "225": "Pv DCDC Converter PDPINTA Interrupt Invalidation",
      "226": "Pv DCDC Converter T 1 PINT Interrupt Invalidation Second",
      "227": "Pv DCDC Converter RESV Interrupt Invalidation",
      "228": "Pv DCDC Converter 100us Task Invalidation",
      "229": "Pv DCDC Converter Clock Invalidation",
      "230": "Pv DCDC Converter EMS Memory Invalidation",
      "231": "Pv DCDC Converter Exterior Communication Invalidation",
      "232": "Pv DCDC Converter IO Interface Invalidation",
      "233": "Pv DCDC Converter Input Voltage Bound Fault",
      "234": "Pv DCDC Converter Outter Voltage Bound Fault",
      "235": "Pv DCDC Converter Output Voltage Bound Fault",
      "236": "Pv DCDC Converter Induct Current Bound Fault",
      "237": "Pv DCDC Converter Input Current Bound Fault",
      "238": "Pv DCDC Converter Output Current Bound Fault",
      "239": "Pv DCDCDC Reactor Over Temperature",
      "240": "Pv DCDCDCIGBT Over Temperature",
      "241": "Pv DCDCDC Converter Chanel 3 Over Temperature",
      "242": "Pv DCDCDC Converter Chanel 4 Over Temperature",
      "243": "Pv DCDCDC Converter Chanel 5 Over Temperature",
      "244": "Pv DCDCDC Converter Chanel 6 Over Temperature",
      "245": "Pv DCDCDC Converter Chanel 7 Over Temperature",
      "246": "Pv DCDCDC Converter Chanel 8 Over Temperature",
      "247": "Pv DCDCDC Reactor Temperature Sampling Invalidation",
      "248": "Pv DCDCDCIGBT Temperature Sampling Invalidation",
      "249": "Pv DCDCDC Converter Chanel 3 Temperature Sampling Invalidation",
      "250": "Pv DCDCDC Converter Chanel 4 Temperature Sampling Invalidation",
      "251": "Pv DCDCDC Converter Chanel 5 Temperature Sampling Invalidation",
      "252": "Pv DCDCDC Converter Chanel 6 Temperature Sampling Invalidation",
      "253": "Pv DCDCDC Converter Chanel 7 Temperature Sampling Invalidation",
      "254": "Pv DCDCDC Converter Chanel 8 Temperature Sampling Invalidation",
      "255": "Pv DCDCDC Converter Inductance Current Sampling Invalidation",
      "256": "Pv DCDC Current Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "257": "Pv DCDC Voltage Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "258": "Pv DCDC Insulation Inspection Fault",
      "259": "Pv DCDC Neg Contactor Close Unsuccessly",
      "260": "Pv DCDC Neg Contactor Cut When Running",
      "261": "Pv DCDC 1 High Voltage Side Of DC Converter Undervoltage",
      "262": "Pv DCDC 1 High Voltage Side Of DC Converter Overvoltage",
      "263": "Pv DCDC 1 Low Voltage Side Of DC Converter Undervoltage",
      "264": "Pv DCDC 1 Low Voltage Side Of DC Converter Overvoltage",
      "265": "Pv DCDC 1 High Voltage Side Of DC Converter Overcurrent Fault",
      "266": "Pv DCDC 1 Low Voltage Side Of DC Converter Overcurrent Fault",
      "267": "Pv DCDC 1 DC Converter IGBT Fault",
      "268": "Pv DCDC 1 DC Converter Precharge Unmet",
      "269": "Pv DCDC 1 BECU Communication Disconnected",
      "270": "Pv DCDC 1 DC Converter Communication Disconnected",
      "271": "Pv DCDC 1 Current Configuration Over Range",
      "272": "Pv DCDC 1 The Battery Request Stop",
      "273": "Pv DCDC 1 Overcurrent Relay Fault",
      "274": "Pv DCDC 1 Lightning Protection Device Fault",
      "275": "Pv DCDC 1 DC Converter Priamary Contactor Disconnected Abnormally",
      "276": "Pv DCDC 1 DC Disconnected Abnormally On Low Voltage Side Of DC Convetor",
      "277": "Pv DCDC 1 DC Convetor EEPROM Abnormity 1",
      "278": "Pv DCDC 1 DC Convetor EEPROM Abnormity 1 Second",
      "279": "Pv DCDC 1 EDC Convetor EEPROM Abnormity 1",
      "280": "Pv DCDC 1 DC Convertor General Overload",
      "281": "Pv DCDC 1 DC Short Circuit",
      "282": "Pv DCDC 1 Peak Pulse Current Protection",
      "283": "Pv DCDC 1 DC Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "284": "Pv DCDC 1 Effective Pulse Value Overhigh",
      "285": "Pv DCDC 1 DC Converte Severe Overload",
      "286": "Pv DCDC 1 DC Breaker Disconnect Abnormally On High Voltage Side Of DC Convetor",
      "287": "Pv DCDC 1 DC Breaker Disconnect Abnormally On Low Voltage Side Of DC Convetor",
      "288": "Pv DCDC 1 DC Convetor Precharge Contactor Close Failed",
      "289": "Pv DCDC 1 DC Convetor Main Contactor Close Failed",
      "290": "Pv DCDC 1 AC Contactor State Abnormity Of DC Convetor",
      "291": "Pv DCDC 1 DC Convetor Emergency Stop",
      "292": "Pv DCDC 1 DC Converter Charging Gun Disconnected",
      "293": "Pv DCDC 1 DC Current Abnormity Before DC Convetor Work",
      "294": "Pv DCDC 1 Fu Se Disconnected",
      "295": "Pv DCDC 1 DC Converter Hardware Current Or Voltage Fault",
      "296": "Pv DCDC 1 DC Converter Crystal Oscillator Circuit Invalidation",
      "297": "Pv DCDC 1 DC Converter Reset Circuit Invalidation",
      "298": "Pv DCDC 1 DC Converter Sampling Circuit Invalidation",
      "299": "Pv DCDC 1 DC Converter Digital IO Circuit Invalidation",
      "300": "Pv DCDC 1 DC Converter PWM Circuit Invalidation",
      "301": "Pv DCDC 1 DC Converter X 5045 Circuit Invalidation",
      "302": "Pv DCDC 1 DC Converter CAN Circuit Invalidation",
      "303": "Pv DCDC 1 DC Converter Software AND Hardware Protection Circuit Invalidation",
      "304": "Pv DCDC 1 DC Converter Power Circuit Invalidation",
      "305": "Pv DCDC 1 DC Converter CPU Invalidation",
      "306": "Pv DCDC 1 DC Converter TINT 0 Interrupt Invalidation",
      "307": "Pv DCDC 1 DC Converter ADC Interrupt Invalidation",
      "308": "Pv DCDC 1 DC Converter CAPITN 4 Interrupt Invalidation",
      "309": "Pv DCDC 1 DC Converter CAPINT 6 Interrupt Invalidation",
      "310": "Pv DCDC 1 DC Converter T 3 PIN Tinterrupt Invalidation",
      "311": "Pv DCDC 1 DC Converter T 4 PIN Tinterrupt Invalidation",
      "312": "Pv DCDC 1 DC Converter PDPINTA Interrupt Invalidation",
      "313": "Pv DCDC 1 DC Converter T 1 PINT Interrupt Invalidation Second",
      "314": "Pv DCDC 1 DC Converter RESV Interrupt Invalidation",
      "315": "Pv DCDC 1 DC Converter 100us Task Invalidation",
      "316": "Pv DCDC 1 DC Converter Clock Invalidation",
      "317": "Pv DCDC 1 DC Converter EMS Memory Invalidation",
      "318": "Pv DCDC 1 DC Converter Exterior Communication Invalidation",
      "319": "Pv DCDC 1 DC Converter IO Interface Invalidation",
      "320": "Pv DCDC 1 DC Converter Input Voltage Bound Fault",
      "321": "Pv DCDC 1 DC Converter Outter Voltage Bound Fault",
      "322": "Pv DCDC 1 DC Converter Output Voltage Bound Fault",
      "323": "Pv DCDC 1 DC Converter Induct Current Bound Fault",
      "324": "Pv DCDC 1 DC Converter Input Current Bound Fault",
      "325": "Pv DCDC 1 DC Converter Output Current Bound Fault",
      "326": "Pv DCDC 1 DC Reactor Over Temperature",
      "327": "Pv DCDC 1 DCIGBT Over Temperature",
      "328": "Pv DCDC 1 DC Converter Chanel 3 Over Temperature",
      "329": "Pv DCDC 1 DC Converter Chanel 4 Over Temperature",
      "330": "Pv DCDC 1 DC Converter Chanel 5 Over Temperature",
      "331": "Pv DCDC 1 DC Converter Chanel 6 Over Temperature",
      "332": "Pv DCDC 1 DC Converter Chanel 7 Over Temperature",
      "333": "Pv DCDC 1 DC Converter Chanel 8 Over Temperature",
      "334": "Pv DCDC 1 DC Reactor Temperature Sampling Invalidation",
      "335": "Pv DCDC 1 DCIGBT Temperature Sampling Invalidation",
      "336": "Pv DCDC 1 DC Converter Chanel 3 Temperature Sampling Invalidation",
      "337": "Pv DCDC 1 DC Converter Chanel 4 Temperature Sampling Invalidation",
      "338": "Pv DCDC 1 DC Converter Chanel 5 Temperature Sampling Invalidation",
      "339": "Pv DCDC 1 DC Converter Chanel 6 Temperature Sampling Invalidation",
      "340": "Pv DCDC 1 DC Converter Chanel 7 Temperature Sampling Invalidation",
      "341": "Pv DCDC 1 DC Converter Chanel 8 Temperature Sampling Invalidation",
      "342": "Pv DCDC 1 DC Converter Inductance Current Sampling Invalidation",
      "343": "Pv DCDC 1 Current Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "344": "Pv DCDC 1 Voltage Sampling Invalidation On The Low Voltage Side Of DC Converter",
      "345": "Pv DCDC 1 Insulation Inspection Fault",
      "346": "Pv DCDC 1 Neg Contactor Close Unsuccessly",
      "347": "Pv DCDC 1 Neg Contactor Cut When Running"
    }
  },
  "io.openems.impl.device.pro.FeneconProEss": {
    "warnings": {
      "0": "Fail The System Should Be Stopped",
      "1": "Common Low Voltage Alarm",
      "2": "Common High Voltage Alarm",
      "3": "Charging Over Current Alarm",
      "4": "Discharging Over Current Alarm",
      "5": "Over Temperature Alarm",
      "6": "Interal Communication Abnormal",
      "7": "Grid Undervoltage L 1",
      "8": "Grid Overvoltage L 1",
      "9": "Grid Under Frequency L 1",
      "10": "Grid Over Frequency L 1",
      "11": "Grid Power Supply Off L 1",
      "12": "Grid Condition Unmeet L 1",
      "13": "DC Under Voltage L 1",
      "14": "Input Over Resistance L 1",
      "15": "Combination Error L 1",
      "16": "Comm With Inverter Error L 1",
      "17": "Tme Error L 1",
      "18": "Grid Undervoltage L 2",
      "19": "Grid Overvoltage L 2",
      "20": "Grid Under Frequency L 2",
      "21": "Grid Over Frequency L 2",
      "22": "Grid Power Supply Off L 2",
      "23": "Grid Condition Unmeet L 2",
      "24": "DC Under Voltage L 2",
      "25": "Input Over Resistance L 2",
      "26": "Combination Error L 2",
      "27": "Comm With Inverter Error L 2",
      "28": "Tme Error L 2",
      "29": "Grid Undervoltage L 3",
      "30": "Grid Overvoltage L 3",
      "31": "Grid Under Frequency L 3",
      "32": "Grid Over Frequency L 3",
      "33": "Grid Power Supply Off L 3",
      "34": "Grid Condition Unmeet L 3",
      "35": "DC Under Voltage L 3",
      "36": "Input Over Resistance L 3",
      "37": "Combination Error L 3",
      "38": "Comm With Inverter Error L 3",
      "39": "Tme Error L 3",
      "40": "OFF Grid"
    },
    "faults": {
      "0": "Control Current Overload 100 Percent L 1",
      "1": "Control Current Overload 110 Percent L 1",
      "2": "Control Current Overload 150 Percent L 1",
      "3": "Control Current Overload 200 Percent L 1",
      "4": "Control Current Overload 120 Percent L 1",
      "5": "Control Current Overload 300 Percent L 1",
      "6": "Control Transient Load 300 Percent L 1",
      "7": "Grid Over Current L 1",
      "8": "Locking Waveform Too Many Times L 1",
      "9": "Inverter Voltage Zero Drift Error L 1",
      "10": "Grid Voltage Zero Drift Error L 1",
      "11": "Control Current Zero Drift Error L 1",
      "12": "Inverter Current Zero Drift Error L 1",
      "13": "Grid Current Zero Drift Error L 1",
      "14": "PDP Protection L 1",
      "15": "Hardware Control Current Protection L 1",
      "16": "Hardware AC Voltage Protection L 1",
      "17": "Hardware DC Current Protection L 1",
      "18": "Hardware Temperature Protection L 1",
      "19": "No Capturing Signal L 1",
      "20": "DC Overvoltage L 1",
      "21": "DC Disconnected L 1",
      "22": "Inverter Undervoltage L 1",
      "23": "Inverter Overvoltage L 1",
      "24": "Current Sensor Fail L 1",
      "25": "Voltage Sensor Fail L 1",
      "26": "Power Uncontrollable L 1",
      "27": "Current Uncontrollable L 1",
      "28": "Fan Error L 1",
      "29": "Phase Lack L 1",
      "30": "Inverter Relay Fault L 1",
      "31": "Grid Realy Fault L 1",
      "32": "Control Panel Overtemp L 1",
      "33": "Power Panel Overtemp L 1",
      "34": "DC Input Overcurrent L 1",
      "35": "Capacitor Overtemp L 1",
      "36": "Radiator Overtemp L 1",
      "37": "Transformer Overtemp L 1",
      "38": "Combination Comm Error L 1",
      "39": "EEPROM Error L 1",
      "40": "Load Current Zero Drift Error L 1",
      "41": "Current Limit R Error L 1",
      "42": "Phase Sync Error L 1",
      "43": "External PV Current Zero Drift Error L 1",
      "44": "External Grid Current Zero Drift Error L 1",
      "45": "Control Current Overload 100 Percent L 2",
      "46": "Control Current Overload 110 Percent L 2",
      "47": "Control Current Overload 150 Percent L 2",
      "48": "Control Current Overload 200 Percent L 2",
      "49": "Control Current Overload 120 Percent L 2",
      "50": "Control Current Overload 300 Percent L 2",
      "51": "Control Transient Load 300 Percent L 2",
      "52": "Grid Over Current L 2",
      "53": "Locking Waveform Too Many Times L 2",
      "54": "Inverter Voltage Zero Drift Error L 2",
      "55": "Grid Voltage Zero Drift Error L 2",
      "56": "Control Current Zero Drift Error L 2",
      "57": "Inverter Current Zero Drift Error L 2",
      "58": "Grid Current Zero Drift Error L 2",
      "59": "PDP Protection L 2",
      "60": "Hardware Control Current Protection L 2",
      "61": "Hardware AC Voltage Protection L 2",
      "62": "Hardware DC Current Protection L 2",
      "63": "Hardware Temperature Protection L 2",
      "64": "No Capturing Signal L 2",
      "65": "DC Overvoltage L 2",
      "66": "DC Disconnected L 2",
      "67": "Inverter Undervoltage L 2",
      "68": "Inverter Overvoltage L 2",
      "69": "Current Sensor Fail L 2",
      "70": "Voltage Sensor Fail L 2",
      "71": "Power Uncontrollable L 2",
      "72": "Current Uncontrollable L 2",
      "73": "Fan Error L 2",
      "74": "Phase Lack L 2",
      "75": "Inverter Relay Fault L 2",
      "76": "Grid Realy Fault L 2",
      "77": "Control Panel Overtemp L 2",
      "78": "Power Panel Overtemp L 2",
      "79": "DC Input Overcurrent L 2",
      "80": "Capacitor Overtemp L 2",
      "81": "Radiator Overtemp L 2",
      "82": "Transformer Overtemp L 2",
      "83": "Combination Comm Error L 2",
      "84": "EEPROM Error L 2",
      "85": "Load Current Zero Drift Error L 2",
      "86": "Current Limit R Error L 2",
      "87": "Phase Sync Error L 2",
      "88": "External PV Current Zero Drift Error L 2",
      "89": "External Grid Current Zero Drift Error L 2",
      "90": "Control Current Overload 100 Percent L 3",
      "91": "Control Current Overload 110 Percent L 3",
      "92": "Control Current Overload 150 Percent L 3",
      "93": "Control Current Overload 200 Percent L 3",
      "94": "Control Current Overload 120 Percent L 3",
      "95": "Control Current Overload 300 Percent L 3",
      "96": "Control Transient Load 300 Percent L 3",
      "97": "Grid Over Current L 3",
      "98": "Locking Waveform Too Many Times L 3",
      "99": "Inverter Voltage Zero Drift Error L 3",
      "100": "Grid Voltage Zero Drift Error L 3",
      "101": "Control Current Zero Drift Error L 3",
      "102": "Inverter Current Zero Drift Error L 3",
      "103": "Grid Current Zero Drift Error L 3",
      "104": "PDP Protection L 3",
      "105": "Hardware Control Current Protection L 3",
      "106": "Hardware AC Voltage Protection L 3",
      "107": "Hardware DC Current Protection L 3",
      "108": "Hardware Temperature Protection L 3",
      "109": "No Capturing Signal L 3",
      "110": "DC Overvoltage L 3",
      "111": "DC Disconnected L 3",
      "112": "Inverter Undervoltage L 3",
      "113": "Inverter Overvoltage L 3",
      "114": "Current Sensor Fail L 3",
      "115": "Voltage Sensor Fail L 3",
      "116": "Power Uncontrollable L 3",
      "117": "Current Uncontrollable L 3",
      "118": "Fan Error L 3",
      "119": "Phase Lack L 3",
      "120": "Inverter Relay Fault L 3",
      "121": "Grid Realy Fault L 3",
      "122": "Control Panel Overtemp L 3",
      "123": "Power Panel Overtemp L 3",
      "124": "DC Input Overcurrent L 3",
      "125": "Capacitor Overtemp L 3",
      "126": "Radiator Overtemp L 3",
      "127": "Transformer Overtemp L 3",
      "128": "Combination Comm Error L 3",
      "129": "EEPROM Error L 3",
      "130": "Load Current Zero Drift Error L 3",
      "131": "Current Limit R Error L 3",
      "132": "Phase Sync Error L 3",
      "133": "External PV Current Zero Drift Error L 3",
      "134": "External Grid Current Zero Drift Error L 3",
      "135": "System Fault",
      "136": "Battery Fault",
      "137": "PCS Fault"
    }
  },
  "io.openems.impl.device.byd.Bem125ktla01Ess": {
    "warnings": {
      "0": "Warning State",
      "1": "Protection State",
      "2": "Derating State",
      "3": "Charge Forbidden",
      "4": "Discharge Forbidden",
      "5": "Status Abnormal Of AC Surge Protector",
      "6": "Close Of Control Switch",
      "7": "Emergency Stop",
      "8": "Status Abnormal Of Frog Detector",
      "9": "Serious Leakage",
      "10": "Normal Leakage",
      "11": "Failure Of Temperature Sensor In Control Cabinet",
      "12": "Failure Of Humidity Sensor In Control Cabinet",
      "13": "Failure Of Storage Device",
      "14": "Exceeding Of Humidity In Control Cabinet"
    }
  },
  "io.openems.impl.device.minireadonly.FeneconMiniEss": {
    "faults": {
      "0": "BECU 1 Discharge Severe Overcurrent",
      "1": "BECU 1 Charge Severe Overcurrent",
      "2": "BECU 1 General Undervoltage",
      "3": "BECU 1 Severe Overvoltage",
      "4": "BECU 1 General Overvoltage",
      "5": "BECU 1 Severe Undervoltage",
      "6": "BECU 1 Inside CAN Broken",
      "7": "BECU 1 General Undervoltage High Current Discharge",
      "8": "BECU 1 BMU Error",
      "9": "BECU 1 Current Sampling Invalidation",
      "10": "BECU 1 Battery Fail",
      "11": "BECU 1 Temperature Sampling Broken",
      "12": "BECU 1 Contactor 1 Test Back Is Abnormal Turn On Abnormity",
      "13": "BECU 1 Contactor 1 Test Back Is Abnormal Turn Off Abnormity",
      "14": "BECU 1 Contactor 2 Test Back Is Abnormal Turn On Abnormity",
      "15": "BECU 1 Contactor 2 Test Back Is Abnormal Turn Off Abnormity",
      "16": "BECU 1 Severe High Temperature Fault",
      "17": "BECU 1 Hall Invalidation",
      "18": "BECU 1 Contactor Invalidation",
      "19": "BECU 1 Outside CAN Broken",
      "20": "BECU 1 Cathode Contactor Broken",
      "21": "BECU 2 Discharge Severe Overcurrent",
      "22": "BECU 2 Charge Severe Overcurrent",
      "23": "BECU 2 General Undervoltage",
      "24": "BECU 2 Severe Overvoltage",
      "25": "BECU 2 General Overvoltage",
      "26": "BECU 2 Severe Undervoltage",
      "27": "BECU 2 Inside CAN Broken",
      "28": "BECU 2 General Undervoltage High Current Discharge",
      "29": "BECU 2 BMU Error",
      "30": "BECU 2 Current Sampling Invalidation",
      "31": "BECU 2 Battery Fail",
      "32": "BECU 2 Temperature Sampling Broken",
      "33": "BECU 2 Contactor 1 Test Back Is Abnormal Turn On Abnormity",
      "34": "BECU 2 Contactor 1 Test Back Is Abnormal Turn Off Abnormity",
      "35": "BECU 2 Contactor 2 Test Back Is Abnormal Turn On Abnormity",
      "36": "BECU 2 Contactor 2 Test Back Is Abnormal Turn Off Abnormity",
      "37": "BECU 2 Severe High Temperature Fault",
      "38": "BECU 2 Hall Invalidation",
      "39": "BECU 2 Contactor Invalidation",
      "40": "BECU 2 Outside CAN Broken",
      "41": "BECU 2 Cathode Contactor Broken",
      "42": "No Available Battery Group",
      "43": "Stack General Leakage",
      "44": "Stack Severe Leakage",
      "45": "Stack Starting Fail",
      "46": "Stack Stopping Fail",
      "47": "Battery Protection",
      "48": "Stack And Group 1 CAN Communication Interrupt",
      "49": "Stack And Group 2 CAN Communication Interrupt"
    },
    "warnings": {
      "0": "BECU 1 General Charge Over Current Alarm",
      "1": "BECU 1 General Discharge Over Current Alarm",
      "2": "BECU 1 Charge Current Limit Alarm",
      "3": "BECU 1 Discharge Current Limit Alarm",
      "4": "BECU 1 General High Voltage Alarm",
      "5": "BECU 1 General Low Voltage Alarm",
      "6": "BECU 1 Abnormal Voltage Change Alarm",
      "7": "BECU 1 General High Temperature Alarm",
      "8": "BECU 1 General Low Temperature Alarm",
      "9": "BECU 1 Abnormal Temperature Change Alarm",
      "10": "BECU 1 Severe High Voltage Alarm",
      "11": "BECU 1 Severe Low Voltage Alarm",
      "12": "BECU 1 Severe Low Temperature Alarm",
      "13": "BECU 1 Severve Charge Over Current Alarm",
      "14": "BECU 1 Severve Discharge Over Current Alarm",
      "15": "BECU 1 Abnormal Cell Capacity Alarm",
      "16": "BECU 1 Balanced Sampling Alarm",
      "17": "BECU 1 Balanced Control Alarm",
      "18": "BECU 1 Hall Sensor Does Not Work Accurately",
      "19": "BECU 1 Generalleakage",
      "20": "BECU 1 Severeleakage",
      "21": "BECU 1 Contactor 1 Turn On Abnormity",
      "22": "BECU 1 Contactor 1 Turn Off Abnormity",
      "23": "BECU 1 Contactor 2 Turn On Abnormity",
      "24": "BECU 1 Contactor 2 Turn Off Abnormity",
      "25": "BECU 1 Contactor 4 Check Abnormity",
      "26": "BECU 1 Contactor Current Unsafe",
      "27": "BECU 1 Contactor 5 Check Abnormity",
      "28": "BECU 1 High Voltage Offset",
      "29": "BECU 1 Low Voltage Offset",
      "30": "BECU 1 High Temperature Offset",
      "31": "BECU 2 General Charge Over Current Alarm",
      "32": "BECU 2 General Discharge Over Current Alarm",
      "33": "BECU 2 Charge Current Limit Alarm",
      "34": "BECU 2 Discharge Current Limit Alarm",
      "35": "BECU 2 General High Voltage Alarm",
      "36": "BECU 2 General Low Voltage Alarm",
      "37": "BECU 2 Abnormal Voltage Change Alarm",
      "38": "BECU 2 General High Temperature Alarm",
      "39": "BECU 2 General Low Temperature Alarm",
      "40": "BECU 2 Abnormal Temperature Change Alarm",
      "41": "BECU 2 Severe High Voltage Alarm",
      "42": "BECU 2 Severe Low Voltage Alarm",
      "43": "BECU 2 Severe Low Temperature Alarm",
      "44": "BECU 2 Severve Charge Over Current Alarm",
      "45": "BECU 2 Severve Discharge Over Current Alarm",
      "46": "BECU 2 Abnormal Cell Capacity Alarm",
      "47": "BECU 2 Balanced Sampling Alarm",
      "48": "BECU 2 Balanced Control Alarm",
      "49": "BECU 2 Hall Sensor Does Not Work Accurately",
      "50": "BECU 2 Generalleakage",
      "51": "BECU 2 Severeleakage",
      "52": "BECU 2 Contactor 1 Turn On Abnormity",
      "53": "BECU 2 Contactor 1 Turn Off Abnormity",
      "54": "BECU 2 Contactor 2 Turn On Abnormity",
      "55": "BECU 2 Contactor 2 Turn Off Abnormity",
      "56": "BECU 2 Contactor 4 Check Abnormity",
      "57": "BECU 2 Contactor Current Unsafe",
      "58": "BECU 2 Contactor 5 Check Abnormity",
      "59": "BECU 2 High Voltage Offset",
      "60": "BECU 2 Low Voltage Offset",
      "61": "BECU 2 High Temperature Offset",
      "62": "General Overcurrent Alarm At Cell Stack Charge",
      "63": "General Overcurrent Alarm At Cell Stack Discharge",
      "64": "Current Limit Alarm At Cell Stack Charge",
      "65": "Current Limit Alarm At Cell Stack Discharge",
      "66": "General Cell Stack High Voltage Alarm",
      "67": "General Cell Stack Low Voltage Alarm",
      "68": "Abnormal Cell Stack Voltage Change Alarm",
      "69": "General Cell Stack High Temperature Alarm",
      "70": "General Cell Stack Low Temperature Alarm",
      "71": "Abnormal Cell Stack Temperature Change Alarm",
      "72": "Severe Cell Stack High Voltage Alarm",
      "73": "Severe Cell Stack Low Voltage Alarm",
      "74": "Severe Cell Stack Low Temperature Alarm",
      "75": "Severve Over Current Alarm At Cell Stack Dharge",
      "76": "Severve Over Current Alarm At Cell Stack Discharge",
      "77": "Abnormal Cell Stack Capacity Alarm",
      "78": "The Parameter Of EEPROM In Cell Stack Lose Effectiveness",
      "79": "Isolating Switch In Confluence Ark Break",
      "80": "The Communication Between Cell Stack And Temperature Of Collector Break",
      "81": "The Temperature Of Collector Fail",
      "82": "Hall Sensor Do Not Work Accurately",
      "83": "The Communication Of PCS Break",
      "84": "Advanced Charging Or Main Contactor Close Abnormally",
      "85": "Abnormal Sampled Voltage",
      "86": "Abnormal Advanced Contactor Or Abnormal RS 485 Gallery Of PCS",
      "87": "Abnormal Main Contactor",
      "88": "General Cell Stack Leakage",
      "89": "Severe Cell Stack Leakage",
      "90": "Smoke Alarm",
      "91": "The Communication Wire To Ammeter Break",
      "92": "The Communication Wire To Dred Break"
    }
  },
  "io.openems.impl.device.pro.FeneconProPvMeter": {
    "warnings": {
      "0": "Negative Power L 1",
      "1": "Negative Power L 2",
      "2": "Negative Power L 3"
    }
  },
  "io.openems.impl.device.refu.RefuEss": {
    "faults": {
      "0": "BMS In Error",
      "1": "BMS In Error Second",
      "2": "BMS Undervoltage",
      "3": "BMS Overcurrent",
      "4": "Error BMS Limits Not Initialized",
      "5": "Connect Error",
      "6": "Overvoltage Warning",
      "7": "Undervoltage Warning",
      "8": "Overcurrent Warning",
      "9": "BMS Ready",
      "10": "TREX Ready",
      "11": "No Enable Batery Group Or Usable Battery Group",
      "12": "Normal Leakage Of Battery Group",
      "13": "Serious Leakage Of Battery Group",
      "14": "Battery Start Failure",
      "15": "Battery Stop Failure",
      "16": "Interruption Of CAN Communication",
      "17": "Interruption Of CAN Communication Between Battery Group And Controller",
      "18": "Emergency Stop Abnormal Of Auxiliary Collector",
      "19": "Leakage Self Detection On Negative",
      "20": "Leakage Self Detection On Positive",
      "21": "Self Detection Failure On Battery",
      "22": "CAN Communication Interruption Between Battery Group And Group 1",
      "23": "CAN Communication Interruption Between Battery Group And Group 2",
      "24": "CAN Communication Interruption Between Battery Group And Group 3",
      "25": "CAN Communication Interruption Between Battery Group And Group 4",
      "26": "Main Contractor Abnormal In Battery Self Detect Group 1",
      "27": "Main Contractor Abnormal In Battery Self Detect Group 2",
      "28": "Main Contractor Abnormal In Battery Self Detect Group 3",
      "29": "Main Contractor Abnormal In Battery Self Detect Group 4",
      "30": "Pre Charge Contractor Abnormal On Battery Self Detect Group 1",
      "31": "Pre Charge Contractor Abnormal On Battery Self Detect Group 2",
      "32": "Pre Charge Contractor Abnormal On Battery Self Detect Group 3",
      "33": "Pre Charge Contractor Abnormal On Battery Self Detect Group 4",
      "34": "Main Contact Failure On Battery Control Group 1",
      "35": "Main Contact Failure On Battery Control Group 2",
      "36": "Main Contact Failure On Battery Control Group 3",
      "37": "Main Contact Failure On Battery Control Group 4",
      "38": "Pre Charge Failure On Battery Control Group 1",
      "39": "Pre Charge Failure On Battery Control Group 2",
      "40": "Pre Charge Failure On Battery Control Group 3",
      "41": "Pre Charge Failure On Battery Control Group 4",
      "42": "Sampling Circuit Abnormal For BMU",
      "43": "Power Cable Disconnect Failure",
      "44": "Sampling Circuit Disconnect Failure",
      "45": "CAN Disconnect For Master And Slave",
      "46": "Sammpling Circuit Failure",
      "47": "Single Battery Failure",
      "48": "Circuit Detection Abnormal For Main Contactor",
      "49": "Circuit Detection Abnormal For Main Contactor Second",
      "50": "Circuit Detection Abnormal For Fancontactor",
      "51": "BMU Power Contactor Circuit Detection Abnormal",
      "52": "Central Contactor Circuit Detection Abnormal",
      "53": "Serious Temperature Fault",
      "54": "Communication Fault For System Controller",
      "55": "Frog Alarm",
      "56": "Fuse Fault",
      "57": "Normal Leakage",
      "58": "Serious Leakage",
      "59": "CAN Disconnection Between Battery Group And Battery Stack",
      "60": "Central Contactor Circuit Open",
      "61": "BMU Power Contactor Open"
    },
    "warnings": {
      "0": "Normal Charging Over Current",
      "1": "Charginig Current Over Limit",
      "2": "Discharging Current Over Limit",
      "3": "Normal High Voltage",
      "4": "Normal Low Voltage",
      "5": "Abnormal Voltage Variation",
      "6": "Normal High Temperature",
      "7": "Normal Low Temperature",
      "8": "Abnormal Temperature Variation",
      "9": "Serious High Voltage",
      "10": "Serious Low Voltage",
      "11": "Serious Low Temperature",
      "12": "Charging Serious Over Current",
      "13": "Discharging Serious Over Current",
      "14": "Abnormal Capacity Alarm",
      "15": "EEPROM Parameter Failure",
      "16": "Switch Of Inside Combined Cabinet",
      "17": "Should Not Be Connected To Grid Due To The DC Side Condition",
      "18": "Emergency Stop Require From System Controller",
      "19": "Battery Group 1 Enable And Not Connected To Grid",
      "20": "Battery Group 2 Enable And Not Connected To Grid",
      "21": "Battery Group 3 Enable And Not Connected To Grid",
      "22": "Battery Group 4 Enable And Not Connected To Grid",
      "23": "The Isolation Switch Of Battery Group 1 Open",
      "24": "The Isolation Switch Of Battery Group 2 Open",
      "25": "The Isolation Switch Of Battery Group 3 Open",
      "26": "The Isolation Switch Of Battery Group 4 Open",
      "27": "Balancing Sampling Failure Of Battery Group 1",
      "28": "Balancing Sampling Failure Of Battery Group 2",
      "29": "Balancing Sampling Failure Of Battery Group 3",
      "30": "Balancing Sampling Failure Of Battery Group 4",
      "31": "Balancing Control Failure Of Battery Group 1",
      "32": "Balancing Control Failure Of Battery Group 2",
      "33": "Balancing Control Failure Of Battery Group 3",
      "34": "Balancing Control Failure Of Battery Group 4"
    }
  },
  "io.openems.impl.device.mini.FeneconMiniEss": {
    "faults": {
      "0": "Control Current Overload 100 Percent",
      "1": "Control Current Overload 110 Percent",
      "2": "Control Current Overload 150 Percent",
      "3": "Control Current Overload 200 Percent",
      "4": "Control Current Overload 120 Percent",
      "5": "Control Current Overload 300 Percent",
      "6": "Control Transient Load 300 Percent",
      "7": "Grid Over Current",
      "8": "Locking Waveform Too Many Times",
      "9": "Inverter Voltage Zero Drift Error",
      "10": "Grid Voltage Zero Drift Error",
      "11": "Control Current Zero Drift Error",
      "12": "Inverter Current Zero Drift Error",
      "13": "Grid Current Zero Drift Error",
      "14": "PDP Protection",
      "15": "Hardware Control Current Protection",
      "16": "Hardware AC Volt Protection",
      "17": "Hardware DC Current Protection",
      "18": "Hardware Temperature Protection",
      "19": "No Capturing Signal",
      "20": "DC Overvoltage",
      "21": "DC Disconnected",
      "22": "Inverter Undervoltage",
      "23": "Inverter Overvoltage",
      "24": "Current Sensor Fail",
      "25": "Voltage Sensor Fail",
      "26": "Power Uncontrollable",
      "27": "Current Uncontrollable",
      "28": "Fan Error",
      "29": "Phase Lack",
      "30": "Inverter Relay Fault",
      "31": "Grid Relay Fault",
      "32": "Control Panel Overtemp",
      "33": "Power Panel Overtemp",
      "34": "DC Input Overcurrent",
      "35": "Capacitor Overtemp",
      "36": "Radiator Overtemp",
      "37": "Transformer Overtemp",
      "38": "Combination Comm Error",
      "39": "EEPROM Error",
      "40": "Load Current Zero Drift Error",
      "41": "Current Limit R Error",
      "42": "Phase Sync Error",
      "43": "External PV Current Zero Drift Error",
      "44": "External Grid Current Zero Drift Error"
    },
    "warnings": {
      "0": "Fail The System Should Be Stopped",
      "1": "Common Low Voltage Alarm",
      "2": "Common High Voltage Alarm",
      "3": "Charging Over Current Alarm",
      "4": "Discharging Over Current Alarm",
      "5": "Over Temperature Alarm",
      "6": "Interal Communication Abnormal",
      "7": "Grid Undervoltage",
      "8": "Grid Overvoltage",
      "9": "Grid Under Frequency",
      "10": "Grid Over Frequency",
      "11": "Grid Power Supply Off",
      "12": "Grid Condition Unmeet",
      "13": "DC Under Voltage",
      "14": "Input Over Resistance",
      "15": "Combination Error",
      "16": "Comm With Inverter Error",
      "17": "Tme Error"
    }
  },
  "io.openems.impl.protocol.modbus.ModbusRtu": {
    "faults": {
      "0": "Configuration Fault",
      "1": "Connection Fault"
    }
  },
  "io.openems.impl.protocol.modbus.ModbusTcp": {
    "faults": {
      "0": "Configuration Fault",
      "1": "Connection Fault"
    }
  }
};