package io.openems.edge.goodwe.batteryinverter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.goodwe.GoodWeConstants;
import io.openems.edge.goodwe.common.enums.EmsPowerMode;

@ObjectClassDefinition(//
		name = "GoodWe Battery-Inverter", //
		description = "GoodWe Battery Inverter.")

@interface Config {
	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "batteryInverter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default GoodWeConstants.DEFAULT_UNIT_ID;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	@AttributeDefinition(name = "Fixed EMS Power Mode", description = "")
	EmsPowerMode emsPowerMode() default EmsPowerMode.UNDEFINED;

	@AttributeDefinition(name = "Fixed EMS Power Set", description = "")
	int emsPowerSet() default -1;

	@AttributeDefinition(name = "Battery Registers", description = "")
	BatteryRegisters batteryRegisters();

	@AttributeDefinition(name = "Fix Allowed Charge Current", description = "")
	int allowedChargeCurrent() default 0;

	String webconsole_configurationFactory_nameHint() default "GoodWe Battery Inverter [{id}]";

}
