package io.openems.edge.heater.gasboiler.viessmann;

public enum ErrorList {

    STANDARD_ERRORS(new String[]{
            "01",
            "02",
            "03",
            "04",
            "05",
            "06",
            "07",
            "08",
            "09",
            "0A",
            "0B",
            "0C",
            "0D",
            "0E",
            "0F Wartung durchführen",
            "10 Kurzschluss Außentemperatursensor",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18 Unterbrechung Außentemperatursensor",
            "19 Verbindungsfehler Aussentemperaturfühler",
            "1A",
            "1B",
            "1C",
            "1D Störung Volumenstromsensor Kommunikationsfehler",
            "1E Störung Volumenstromsensor Fehler 1",
            "1F Störung Volumenstromsensor Fehler 2",
            "20 Kurzschluss Vorlauftemp. HK1 / Anlage",
            "21 Fehler Temperaturwerte Solarkreislauf",
            "22 Fehler Speichertemperaturwerte",
            "23 Fehler Ladezustandsberechnung",
            "24 Fehler Zirkulation detektiert",
            "25 Fehler Umschichtung detektiert",
            "26 Fehler Aktor Signale",
            "27 Fehler Volumenstromwert",
            "28 Unterbrechung Vorlauftemp. HK1 / Anlage",
            "29 Fehler Signal Elektroheizeinsätze",
            "2A Inversion detektiert",
            "2B",
            "2C",
            "2D",
            "2E",
            "2F",
            "30 Kurzschluss Kesseltemperatursensor",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38 Unterbrechung Kesseltemperatursensor",
            "39",
            "3A LAN Hardware Fehler",
            "3B LAN System Fehler",
            "3C LAN DHCP-Server antwortet nicht",
            "3D LAN Ethernet-Leitung nicht verbunden",
            "3E LAN Broker Verbindungsfehler",
            "3F LAN Update Fehler",
            "40 Kurzschluss Vorlauftemp. HK2",
            "41 Kurzschluss Rücklauftemp. HK2",
            "42",
            "43",
            "44 Kurzschluss Vorlauftemp. HK3",
            "45 Kurzschluss Rücklauftemp. HK3",
            "46",
            "47",
            "48 Unterbrechung Vorlauftemp. HK2",
            "49 Unterbrechung Rücklauftemp. HK 2",
            "5A",
            "5B",
            "4C Unterbrechung Vorlauftemp. HK3",
            "4D Unterbrechung Rücklauftemp. HK3",
            "4E",
            "4F",
            "50 Kurzschluss Speichertemperatursensor 1",
            "51 Kurzschluss Speichertemperatursensor 2",
            "52 Kurzschluss Puffertemperatursensor",
            "53",
            "54 Fehler Kessel 5",
            "55 Fehler Kessel 6",
            "56 Fehler Kessel 7",
            "57 Fehler Kessel 8",
            "58 Unterbrechung Speichertemperatursensor 1",
            "59 Unterbrechung Speichertemperatursensor 2",
            "5A Unterbr. Puffersensor/Vorlauftemperaturs. Hydr. Weiche",
            "5B",
            "5C Ausfall-Kessel 5",
            "5D Ausfall-Kessel 6",
            "5E Ausfall-Kessel 7",
            "5F Ausfall-Kessel 8",
            "60 Kurzschluss Temperatursensor 17A",
            "61",
            "62",
            "63",
            "64",
            "65",
            "66",
            "67",
            "68 Unterbrechung Temperatursensor 17A",
            "69",
            "6A",
            "6B",
            "6C",
            "6D",
            "6E",
            "6F",
            "70 Kurzschluss Temperatursensor 17B",
            "71",
            "72",
            "73",
            "74 Kurzschluss Sensor 1 Pumpenmodul PM1",
            "75 Kurzschluss Sensor 2 Pumpenmodul PM1",
            "76 Kurzschluss Sensor 3 Pumpenmodul PM1",
            "77 Kurzschluss Sensor 4 Pumpenmodul PM1",
            "78 Unterbrechung Temperatursensor 17B",
            "79",
            "7A",
            "7B",
            "7C Unterbrechung Sensor 1 Pumpenmodul PM1",
            "7D Unterbrechung Sensor 2 Pumpenmodul PM1",
            "7E Unterbrechung Sensor 3 Pumpenmodul PM1",
            "7F Unterbrechung Sensor 4 Pumpenmodul PM1",
            "80 Kurzschluss Sicherheits-Kesseltemperaturbegrenzer (SKTS)",
            "81 Sensordrift Sicherheits-Kesseltemperaturbegrenzer (SKTS)",
            "82 Kurzschluss Sicherheits-Abastemperaturbegrenzer (SAGTS)",
            "83 Sensordrift Sicherheits-Abastemperaturbegrenzer (SAGTS)",
            "84 Fehler Kessel 1",
            "85 Fehler Kessel 2",
            "86 Fehler Kessel 3",
            "87 Fehler Kessel 4",
            "88 Unterbrechung Sicherheits-Kesseltemperaturbegrenzer (SKTS)",
            "89 Unterbrechung Sicherheits-Abastemperaturbegrenzer (SAGTS)",
            "8A",
            "8B",
            "8C Ausfall-Kessel 1",
            "8D Ausfall-Kessel 2",
            "8E Ausfall-Kessel 3",
            "8F Ausfall-Kessel 4",
            "90 Solar: Kurzschluss Sensor 7",
            "91 Solar: Kurzschluss Sensor 10",
            "92 Solar: Kurzschluss Kollektortemperatursensor",
            "93 Solar: Kurzschluss Kollektorrücklauftemperatursensor S3",
            "94 Solar: Kurzschluss Speichertemperatursensorsensor",
            "95",
            "96",
            "97",
            "98 Solar: Unterbrechung Sensor 7",
            "99 Solar: Unterbrechung Sensor 10",
            "9A Solar: Unterbrechung Kollektortemperatursensor",
            "9B Solar: Unterbrechung Kollektorrücklauftemperatursensor S3",
            "9C Solar: Unterbrechung Speichertemperatursensor",
            "9D",
            "9E Solar: Delta-T Überwachung",
            "9F Solar: allgemeiner Fehler",
            "A0 Störmeldemodul 2: Eingang 1",
            "A1 Störmeldemodul 2: Eingang 2",
            "A2 Störmeldemodul 2: Eingang 3/niedriger Wasserdruck Regelung",
            "A3 Störmeldemodul 2: Eingang 4/Abgastemperaturs. nicht richtig po",
            "A4 Störmeldemodul 2: externe Störung/Überschreitung Anlagenmaxi",
            "A5 Externe Störung Pumpenmodul PM1",
            "A6 Interne Störung Pumpenmodul PM1/Fehler Fremdstromanode",
            "A7 Fehler Bedienteil (Uhrenbaustein)",
            "A8 Fehler interne Pumpe meldet Luft",
            "A9 Fehler interne Pumpe blockiert",
            "AA Konfigurationsfehler TSA-Funktion",
            "AB Konfigurationsfehler Wärmetauscherset",
            "AC Konfigurationsfehler Rücklaufregelung",
            "AD Konfigurationsfehler Drosselklappe",
            "AE Interner Fehler Mischer",
            "AF Interner Fehler Mischer",
            "B0 Kurzschluss Abgastemperatursensor",
            "B1 Fehler Bedieneinheit",
            "B2",
            "B3",
            "B4 Interner Fehler ADC (Referenzkanal)",
            "B5 Interner Fehler EEPROM",
            "B6 Hardwarekennung ungültig",
            "B7 Kesselschutzcodierkarte falsch/fehlerhaft",
            "B8 Unterbrechung Abgastemperatursensor",
            "B9 Fehlerhafte Übertragung Codiersteckerdaten",
            "BA Kommunikationsfehler Mischermodul HK2",
            "BB Kommunikationsfehler Mischermodul HK3",
            "BC Kommunikationsfehler Fernbedienung HK1",
            "BD Kommunikationsfehler Fernbedienung HK2",
            "BE Kommunikationsfehler Fernbedienung HK3",
            "BF LON-Modul falsch/fehlerhaft",
            "C0",
            "C1 externe Sicherheitseinrichtung Kessel 1/Kommunikationsfehler An",
            "C2 Kommunikationsfehler Solarregelung",
            "C3 Kommunikationsfehler Anschlusserweiterung AM1",
            "C4 Kommunikationsfehler Anschlusserweiterung 0-10V/OT/Pumpenmodul",
            "C5 Kommunikationsfehler KM-Bus Gerät DAP1/Kommunikationsfehler dr",
            "C6 Kommunikationsfehler KM-Bus Gerät DAP2/Kommunikationsfehler dr",
            "C7 Störmeldem. 1 externe Störung/Kommunikationsfehler drehzahlge",
            "C8 Störmeldemodul 1 Eingang 1: Wasserstandsbegrenzer/Kommunikatio",
            "C9 Störmeldemodul 1 Eingang 2: Maximaldruck 1/Kommunikationsfehle",
            "CA Störmeldemodul 1 Eingang 3: Minimaldruck/Maximaldruck 2/Kommun",
            "CB Störmeldemodul 1 Eingang 4: Maximaldruck 2",
            "CC reserviert externe Peripherie",
            "CD Kommunikationsfehler Vitocom 100",
            "CE Kommunikationsfehler Störmeldemodul 1/Anschlusserweiterung",
            "CF Kommunikationsfehler LON-Modul/HV-Modul",
            "D0",
            "D1 Brennerstörung Kessel 1",
            "D2 Kommunikationsfehler Störmeldemodul 2",
            "D3 Kommunikationsfehler Anschlusserweiterung EA1",
            "D4 Sicherheitstemperaturbegrenzer Kessel",
            "D5 Kaskade: Kessel meldet sich nicht",
            "D6 EA1: Externe Störung 1",
            "D7 EA1: Externe Störung 2",
            "D8 EA1: Externe Störung 3",
            "D9",
            "DA Kurzschluss Raumtemperatursensor HK 1",
            "DB Kurzschluss Raumtemperatursensor HK 2",
            "DC Kurzschluss Raumtemperatursensor HK 3",
            "DD Unterbrechung Raumtemperatursensor HK 1",
            "DE Unterbrechung Raumtemperatursensor HK 2",
            "DF Unterbrechung Raumtemperatursensor HK 3",
            "E0 Fehler externer Teilnehmer LON",
            "E1 Gasventil 1 undicht/Gasdruckw. 2 öffnet nicht/SCOT Kalibration",
            "E2 Gasventil 2 undicht/Gasdruckw. 2 schließt nicht/keine Kalibrat",
            "E3 Fehler Sicherheitskette/Kalibrationsfehler thermisch",
            "E4 Fehler Versorgungsspannung/",
            "E5 Fehler Flammenverstärker",
            "E6 Minimalen Luft-/Wasserdruck nicht erreicht/Abgas-/ Zuluftsystem",
            "E7 Kurzschluss Kesseltemperatursensor 2/SCOT Kalibrationswert Gren",
            "E8 Sensordrift Kesseltemperatursensor 2/SCOT Ionisationssignal wei",
            "E9 Unterbrechung Kesseltemperatursensor 2",
            "EA Fehler Hauptventil mehrere Gasarten/SCOT Kalibrationswert weich",
            "EB Fehler: keine Freigabe Brenner über ext. Kontakt / SCOT Kalibr",
            "EC Fehler Sicherheitsrelais/SCOT Ionisationssollwert fehlerhaft",
            "ED Fehler Zündrelais/SCOT Systemfehler",
            "EE Fehler Brennstoffrelais 1/keine Flammbildung",
            "EF Fehler Brennstoffrelais 2/Flammenausfall in Sicherheitszeit",
            "F0 Kommunikationsfehler Feuerungsautomat",
            "F1 Abgasübertemperatur",
            "F2 Kesselübertemperatur",
            "F3 Fremdlichterkennung/Flamme vor Start",
            "F4 keine Flammenbildung",
            "F5 Luftdruckwächter schließt nicht",
            "F6 Gasdruckwächter schließt nicht",
            "F7 Luftdruckwächter öffnet nicht",
            "F8 Fehlerhafte Brennstoffventil Rückmeldung",
            "F9 Lüfter Drehzahl nicht erreicht",
            "FA Lüfter Stillstand nicht erreicht",
            "FB Feuerraumdruck, Brennerklappe öffnet nicht, Kondensatstau/Flam",
            "FC Lüfter Fehler elektrische Ansteuerung",
            "FD Interner Fehler Feuerungsautomat (Fehlerursache steht an)",
            "FE Codierstecker defekt oder falsch oder EMV-Störung",
            "FF Interner Fehler Feuerungsautomat (Fehlerursache steht nicht meh",
    });


    private String[] errors;

    ErrorList(String[] errors) {
        this.errors = errors;
    }

    public String[] getErrorList() {
        return this.errors;
    }

}
