package io.openems.edge.thermometer.esera.onewire;


import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.thermometer.esera.onewire.enums.LogVerbosity;
import io.openems.edge.thermometer.esera.onewire.enums.OneWireDevice;

@ObjectClassDefinition(//
		name = "Esera OneWire Thermometer", //
		description = "OneWire thermometer connected to Esera Eco 5x1")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "thermometer0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "Log-Verbosity", description = "The log verbosity.")
	LogVerbosity logVerbosity() default LogVerbosity.NONE;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;
	
    @AttributeDefinition(name = "Thermometer number", description = "The number of the 1w thermometer (1-20)")
    OneWireDevice OneWireDevice() default OneWireDevice.OneWireThermometer1;	
	
	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Esera OneWire Thermometer [{id}]";

}