#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXTRA_JVM_OPTS=${EXTRA_JVM_OPTS:-""}

command="/usr/bin/java \
-Dosgi.clean=true \
-Dorg.apache.felix.eventadmin.Timeout=0 \
-Dorg.apache.felix.http.host=0.0.0.0 \
-Dorg.apache.felix.http.port=8078 \
-Dfelix.cm.dir=/var/opt/openems/config \
-Dopenems.data.dir=/var/opt/openems/data \
-Djava.net.preferIPv4Stack=true \
-XX:+ExitOnOutOfMemoryError \
-XX:+UseZGC -XX:+ZGenerational \
$EXTRA_JVM_OPTS \
-jar /opt/openems/openems-backend-edge.jar"

echo "RUN '$command'"

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 8078" \
        s6-setuidgid abc $command
