package io.openems.edge.controller.api.modbus.customSerial;

import io.openems.edge.controller.api.modbus.AbstractModbusApi;
import io.openems.edge.controller.api.modbus.FlowControlIn;
import io.openems.edge.controller.api.modbus.FlowControlOut;
import io.openems.edge.controller.api.modbus.Parity;
import io.openems.edge.controller.api.modbus.Stopbit;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Api Modbus/Serial Custom", //
		description = "This controller provides a custom Modbus/Serial api.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlApiModbusSerial0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Port", description = "The serial port on which the server should listen - e.g. '/dev/ttyUSB0' or 'COM3'")
	String port() default AbstractModbusApi.DEFAULT_PORT_SERIAL;

	@AttributeDefinition(name = "Baudrate", description = "The baudrate - e.g. 9600, 19200, 38400, 57600 or 115200")
	int baudRate() default 9600;

	@AttributeDefinition(name = "Flow control in", description = "Flow control in")
	FlowControlIn flowControlIn() default FlowControlIn.DISABLED;

	@AttributeDefinition(name = "Flow control out", description = "Flow control out")
	FlowControlOut flowControlOut() default FlowControlOut.DISABLED;

	@AttributeDefinition(name = "Databits", description = "The number of databits - e.g. 8")
	int databits() default 8;

	@AttributeDefinition(name = "Stopbits", description = "The number of stopbits - '1', '1.5' or '2'")
	Stopbit stopbits() default Stopbit.ONE;

	@AttributeDefinition(name = "Parity", description = "The parity - 'none', 'even', 'odd', 'mark' or 'space'")
	Parity parity() default Parity.NONE;

	@AttributeDefinition(name = "Echo", description = "Echo")
	boolean echo() default false;

	@AttributeDefinition(name = "Channels", description = "Channels that should be made available via Modbus. The input "
			+ "format is \"RegisterAddress/ModbusType/Component-ID/Channel-ID/AccessMode\". "
			+ " - \"RegisterAddress\" is the Modbus holding and input register you want to map the channel to. This needs to be an "
			+ "integer between 0 and 9998 (inclusive). Channels are always mapped to both holding and input registers, no matter the channel type."
			+ " - \"ModbusType\" is how to convert the channel. Available options: UINT16, FLOAT32, FLOAT64 and STRING16."
			+ " Note that this affects how many registers are needed to transmit the data. UNIT16 needs one register, "
			+ "FLOAT32 needs two, FLOAT64 needs four and STRING16 needs 16 registers. "
			+ " - \"Component-ID\" is the Id of the module that contains the channel."
			+ " - \"Channel-ID\" is the Id of the channel, entered as UPPER_UNDERSCORE or UpperCamel."
			+ " - \"AccessMode\" defines the privilege of the Modbus connection. Available options: READ_ONLY, READ_WRITE and WRITE_ONLY."
			+ " A mismatch with the channel access mode (like Modbus WRITE_ONLY for a READ_ONLY channel) will default back to the channel access mode.")
	String[] component_ids() default { "0/UINT16/meter0/SIMULATED_ACTIVE_POWER/read_write" };

	@AttributeDefinition(name = "Api-Timeout", description = "Sets the timeout in seconds for updates on Channels set by this Api.")
	int apiTimeout() default 60;

	@AttributeDefinition(name = "Components target filter", description = "This is auto-generated by 'Component-IDs'.")
	String Component_target() default "";

	String webconsole_configurationFactory_nameHint() default "Controller Api Modbus/Serial Custom [{id}]";
}