= Cycle Controller

Developed in order to provide cycle, capacity test scenarios.

== Configuration

Parameters which should be taken care of:

`ess_id`::
Id of the device. ex, ess0
`cycleOrder`::
Initial step decide whether to start with charge or discharge in type of 'CycleOrder'. ex, CycleOrder.START_WITH_DISCHARGE
`standbyTime`::
The time is to wait between charge and discharge, asked to be given in minute. ex, standby=5, means wait 5 minute before to switch from charge to discharge.
`startTime`::
Start Time in Hour should be configured like [YYYY-MM-DD HH:MM]. Also provide an opportunity to activate the controller for required date and time.
`maxSoc`::
The maximum Soc value that will be reached for charging when the controller is activated. If its set to 100, limit condition will be considered for allowed charge power. For value 100, when allowed charge power is 0, charge will be stopped.
`minSoc`::
The minimum Soc value that will be reached for charging when the controller is activated. If its set to 0, limit condition will be considered for allowed discharge power. For value 0, when allowed discharge power is 0, charge will be stopped.
`power`::
The power in Watt to charge or discharge.
`totalCycleNumber`::
Decides for how many times cycles to apply.
`finalSoc`::
The Soc value which will be kept in the battery after cycle test completed.

== Monitoring

Channels can be followed from Grafana or online monitoring:

`ctrlEssCycle0/AwaitingHysteresis`::
Active when waiting between two states (see standby-time)
`ctrlEssCycle0/CompletedCycleNumber`::
Number of already completed cycles
`ctrlEssCycle0/StateMachine`::
The current State of the State-Machine: UNDEFINED, FINISHED, CHARGE, DISCHARGE, STORE_SOC, etc. states.

== Algorithm logic

Controller starts with `UNDEFINED` state. First checks for `cycleOrder` configuration. If it is defined, according to the selection goes to `CHARGE or `DISCHARGE` state. 
If `cycleOrder` is not defined, selection is made according to the Soc value.
If Soc is higher than 50 % starts with `CHARGE` state, otherwise starts with `DISCHARGE` state.

If the second state is `CHARGE` state, controller start to charge the system until `maxSoc`. Again, if it is configured as 100 %, when allowed charge power is 0 W, charge will be stopped. Then, based on the `standbyTime` configuration will wait until hysteresis completed.
Afterwards, will switch to `DISCHARGE` state.

If the second state is `DISCHARGE` state, controller start to discharge the system until `minSoc`. Again, if it is configured as 0 %, when allowed discharge power is 0 W, discharge will be stopped. Then, based on the `standbyTime` configuration will wait until hysteresis completed.
Afterwards, will switch to `CHARGE` state.

After first `CHARGE` and `DISCHARGE` next state will be `FINISHED`. If the `totalCycleNumber` is "1", next state will be `FINAL_SOC`. And in this state, according to the `finalSoc` system will be charged or discharged last time.
If the `totalCycleNumber` is higher than "1", next cycle will be called. This process will repeat itself until `totalCycleNumber` reaches. At the end, last state will be `FINAL_SOC` and required last Soc value will be kept in the battery.

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.controller.ess.cycle[Source Code icon:github[]]