package io.openems.edge.simulator.datasource.csv;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Simulator DataSource: CSV Reader", //
		description = "This service provides CSV-Input data.")
@interface Config {
	String service_pid();

	String id() default "datasource0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Source", description = "A Data-Input generated by a CSV Reader.")
	Source source();

	String webconsole_configurationFactory_nameHint() default "Simulator DataSource: CSV Reader [{id}]";
}