package io.openems.edge.simulator.datasource.csv;

public enum Source {
	H0_HOUSEHOLD_SUMMER_WEEKDAY_STANDARD_LOAD_PROFILE,
	H0_HOUSEHOLD_SUMMER_WEEKDAY_PV_PRODUCTION,
	H0_HOUSEHOLD_SUMMER_WEEKDAY_NON_REGULATED_CONSUMPTION,
	H0_HOUSEHOLD_SUMMER_WEEKDAY_PV_PRODUCTION2,
	GENERATED
}
