package io.openems.edge.controller.api.modbus.readonlySerial;

import io.openems.edge.controller.api.modbus.AbstractModbusApi;
import io.openems.edge.controller.api.modbus.FlowControlIn;
import io.openems.edge.controller.api.modbus.FlowControlOut;
import io.openems.edge.controller.api.modbus.Parity;
import io.openems.edge.controller.api.modbus.Stopbit;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Api Modbus/Serial Read-Only", //
		description = "This controller provides a read-only Modbus/Serial api.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlApiModbusSerial0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Port", description = "The serial port on which the server should listen - e.g. '/dev/ttyUSB0' or 'COM3'")
	String port() default AbstractModbusApi.DEFAULT_PORT_SERIAL;

	@AttributeDefinition(name = "Baudrate", description = "The baudrate - e.g. 9600, 19200, 38400, 57600 or 115200")
	int baudRate() default 9600;

	@AttributeDefinition(name = "Flow control in", description = "Flow control in")
	FlowControlIn flowControlIn() default FlowControlIn.DISABLED;

	@AttributeDefinition(name = "Flow control out", description = "Flow control out")
	FlowControlOut flowControlOut() default FlowControlOut.DISABLED;

	@AttributeDefinition(name = "Databits", description = "The number of databits - e.g. 8")
	int databits() default 8;

	@AttributeDefinition(name = "Stopbits", description = "The number of stopbits - '1', '1.5' or '2'")
	Stopbit stopbits() default Stopbit.ONE;

	@AttributeDefinition(name = "Parity", description = "The parity - 'none', 'even', 'odd', 'mark' or 'space'")
	Parity parity() default Parity.NONE;

	@AttributeDefinition(name = "Echo", description = "Echo")
	boolean echo() default false;

	@AttributeDefinition(name = "Component-IDs", description = "Components that should be made available via Modbus.")
	String[] component_ids() default { "_sum" };

	@AttributeDefinition(name = "Components target filter", description = "This is auto-generated by 'Component-IDs'.")
	String Component_target() default "";

	String webconsole_configurationFactory_nameHint() default "Controller Api Modbus/Serial Read-Only [{id}]";
}