package io.openems.edge.battery.soltaro.single.versionc;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;

@ObjectClassDefinition(//
		name = "BMS Soltaro Single Rack Version C", //
		description = "Implements the Soltaro battery rack system.")
public @interface Config {

	/**
	 * Return the id.
	 * @return id
	 */
	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "battery0"; 

	/**
	 * Return the alias.
	 * @return alias
	 */
	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	/**
	 * Return the enabled.
	 * @return enabled
	 */
	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	/**
	 * Gets the StartStopConfig.
	 * @return StartStopConfig
	 */
	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	/**
	 * Return the modbus_id.
	 * @return modbus_id
	 */
	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	/**
	 * Return the modbusUnitId.
	 * @return modbusUnitId
	 */
	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 0;

	/**
	 * Return the Modbus_target.
	 * @return Modbus_target
	 */
	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	/**
	 * Return the webconsole_configurationFactory_nameHint.
	 * @return webconsole_configurationFactory_nameHint
	 */
	String webconsole_configurationFactory_nameHint() default "BMS Soltaro Single Rack Version C [{id}]";
}