package io.openems.edge.sma.sunnyisland4;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.ess.api.SinglePhase;

@ObjectClassDefinition( //
		name = "ESS SMA SunnyIsland 4.4M", //
		description = "Implements the SMA SunnyIsland 4.4M energy storage system.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	SinglePhase phase() default SinglePhase.L1;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Write mode enabled?", description = "true if sunny island should be controlled by OpenEMS.")
	boolean writeModeEnabled() default false;

	@AttributeDefinition(name = "Symetric mode enabled?", description = "true, if three Sunny Island are configured for master-slave symmetric mode")
	boolean symetricMode() default true;

	int modbusUnitId() default 3;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS SMA SunnyIsland 4.4M [{id}]";

}