# OpenEMS Web-Interface
location /openems-ui {
    alias   /opt/plcnext/apps/openems-ui/html;
    index	index.html;

    add_header Cache-Control "no-transform" always;
    add_header Content-Security-Policy "upgrade-insecure-requests; frame-ancestors 'self'";
    add_header Permissions-Policy "interest-cohort=()";
    add_header Referrer-Policy "same-origin" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    try_files $uri $uri/ /index.html;
    error_page	404 300 /index.html;
}
