package io.openems.edge.battery.microcare.ubmu;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( 
		name = "BMS Microcare UBMU", //
		description = "Implements the Microcare Universal Battery Management Unit.")
@interface Config {
	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ubmu0"; 

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default ""; 

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true; 

	@AttributeDefinition(name = "MCComms Bridge Component ID", description = "Component-ID of the MCComms bridge.")
	String mcCommsBridge_id() default "mccomms0";

	@AttributeDefinition(name = "UBMU MCComms Address", description = "The address of the UBMU device.")
	int UBMUmcCommsAddress() default 16;
	
	@AttributeDefinition(name = "OpenEMS MCComms Address", description = "The virtual address of the OpenEMS MCComms device.")
	int openemsMCCommsAddress() default 1;
	
	@AttributeDefinition(name = "Status Refresh Period (Milliseconds)", description = "The number of milliseconds between requests for the UBMU status values.")
	int statusRefreshMS() default 5000;
	
	@AttributeDefinition(name = "RTD Refresh Period (Milliseconds)", description = "The number of milliseconds between requests for the UBMU real time data values.")
	int RTDrefreshMS() default 1000;
	
	@AttributeDefinition(name = "MCComms-bridge target filter", description = "This is auto-generated by 'MCComms Bridge Component ID'.")
	String mcCommsBridge_target() default "";

	String webconsole_configurationFactory_nameHint() default "MCUBMU [{id}]";
}
