export const IGNORE_NATURES = [
  "IO.OPENEMS.EDGE.COMMON.MODBUSSLAVE.MODBUS_SLAVE",
  "IO.OPENEMS.EDGE.COMMON.COMPONENT.OPENEMS_COMPONENT",
  "IO.OPENEMS.EDGE.BRIDGE.MODBUS.API.BRIDGE_MODBUS_SERIAL",
  "IO.OPENEMS.EDGE.BRIDGE.MODBUS.API.BRIDGE_MODBUS_TCP",
  "IO.OPENEMS.EDGE.COMMON.JSONAPI.JSON_API",
  "ORG.OSGI.SERVICE.CM.CONFIGURATION_LISTENER",
];
