<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
package io.openems.edge.meter.hager.ecr380d;
========
package io.openems.edge.firealarmsystem.hekatron;
>>>>>>>> b059229803 ([Edge] Hekatron B9-X2 fire alarm system: implementation as standalone component (#3294)):io.openems.edge.firealarmsystem.hekatron/src/io/openems/edge/firealarmsystem/hekatron/Config.java

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
		name = "Meter Hager ECR380D", //
		description = "Implements the Hager ECR380D meter.")
@interface Config {
========
		name = "Fire Alarm Hekatron B9-X2", //
		description = "Implements the Hekatron B9-X2 fire alarm system component")
public @interface Config {
>>>>>>>> b059229803 ([Edge] Hekatron B9-X2 fire alarm system: implementation as standalone component (#3294)):io.openems.edge.firealarmsystem.hekatron/src/io/openems/edge/firealarmsystem/hekatron/Config.java

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
	@AttributeDefinition(name = "Meter-Type", description = "What is measured by this Meter?")
	MeterType type() default MeterType.PRODUCTION;
========
	@AttributeDefinition(name = "Fire Alarm Config Version", description = "The config version of the Fire Alarm.")
	ConfigVersion configVersion() default ConfigVersion.INDUSTRIAL_XL_V1;
>>>>>>>> b059229803 ([Edge] Hekatron B9-X2 fire alarm system: implementation as standalone component (#3294)):io.openems.edge.firealarmsystem.hekatron/src/io/openems/edge/firealarmsystem/hekatron/Config.java

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

<<<<<<<< HEAD:io.openems.edge.meter.hager/src/io/openems/edge/meter/hager/ecr380d/Config.java
	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter Hager ECR380D [{id}]";
}
========
	String webconsole_configurationFactory_nameHint() default "Fire Alarm Hekatron B9-X2 [{id}]";

}
>>>>>>>> b059229803 ([Edge] Hekatron B9-X2 fire alarm system: implementation as standalone component (#3294)):io.openems.edge.firealarmsystem.hekatron/src/io/openems/edge/firealarmsystem/hekatron/Config.java
