package io.openems.edge.wago;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "IO WAGO Fieldbus Coupler 750-352", //
		description = "Implements the WAGO Fieldbus Coupler 750-352")
@interface Config {
	String id() default "io0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id();

	@AttributeDefinition(name = "Username", description = "Username")
	String username() default "admin";

	@AttributeDefinition(name = "Password", description = "Password")
	String password() default "wago";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "IO WAGO Fieldbus Coupler 750-352 [{id}]";
}