package io.openems.edge.controller.pbyf;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "AIT HIL Controller Curve-Based Frequency-Watt", //
		description = "Controls an AIT HIL with Curve-Based Frequency-Watt")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlPByF0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "AIT HIL-ID", description = "ID of AIT HIL device.")
	String aithil_id();

	@AttributeDefinition(name = "Schedule", description = "The Schedule as a JSON-Array")
	String schedule() default "";

	@AttributeDefinition(name = "AIT HIL target filter", description = "This is auto-generated by 'AIT HIL-ID'.")
	String component_target() default "";

	String webconsole_configurationFactory_nameHint() default "AIT HIL Controller Curve-Based Frequency-Watt [{id}]";
}