package io.openems.edge.ruhfass.battery.batcon;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;
import io.openems.edge.ruhfass.battery.batcon.enums.BatteryType;
import io.openems.edge.ruhfass.battery.batcon.enums.RemainingBusSimulationCommand;

@ObjectClassDefinition(//
		name = "Ruhfass Battery Batcon", //
		description = "Implements the Ruhfass Battery Batcon system.")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "battery0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	@AttributeDefinition(name = "Remaining Bus Simulation?", description = "Should the Remaining Bus Simulation be on or off?")
	RemainingBusSimulationCommand remainingBusSimulation() default RemainingBusSimulationCommand.OFF;

	@AttributeDefinition(name = "Set Battery Type", description = "Sets the Battery Type used!")
	BatteryType batteryType() default BatteryType.CBEV;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "Ruhfass Battery Batcon [{id}]";

}