= IO Heating Element

Controls a three-phase heating element via Relays, according to grid active power  

== Configuration

                - `id` Unique ID of this Component (id), e.g. "ctrlIoAlarm0", "ctrlIoAlarm1"

                - `alias` Human-readable name of this Component; defaults to Component-ID (alias)

                - `enabled` Is this Component enabled?

                - `mode` Selection of the Mode, 1) always on 2) always off or 3) Automatic

                - `inputChannelAddress` Address of the input channel for the grid power

                - `outputChannelAddress1` Channel address of the Digital Output that should be switched

                - `outputChannelAddress2` Channel address of the Digital Output that should be switched

                - `outputChannelAddress3` Channel address of the Digital Output that should be switched
                
                - `heatingLevel` This is the unit which tell which level the heating element runs

                - `endTime` End time to check the minimum run time

                - `priority` Decide the priority, time or the Kilowatthours

                - `minTime` Minimum time for heating element to run in hours

                - `minkwh` Minimum Kilowatthours for heating element to run in kWh

                - `powerOfPhase` Power of the single phase in W




== Example Configuration

- `Component-ID` : ctrlHeatingElement00
- `Alias` : myCtrl
- `enabled` : true
- `Mode` : Automatic
- `Input Channels` : _sum/GridActivePower
- `Output Channel1` : io0/Relay1
- `Output Channel2` : io0/Relay2
- `Output Channel3` : io0/Relay3
- `Heating Level` : level_3 
- `End time` : "17:00:00" 
- `Priority` : "Time"
- `Minimum Time` : 1
- `Minimum Kwh` : 4
- `Power of Phase` : 2000

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.controller.io.heatingelement[Source Code icon:github[]]
