package io.openems.edge.evcs.evtec.core;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "EVCS EVTEC Core", //
		description = "Implementation of the core of the EVTEC electic vehicle charging station")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "core0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge (same one as for Evcs EvTec).")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device. (2= first plug charger, 3 = second plug charger, 1 = station info)")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Enable communication timeout", description = "If true, the communication timeout will be enabled.")
	boolean comTimeoutEnabled() default true;

	@AttributeDefinition(name = "Timeout value", description = "Timeout in seconds for communication failure")
	int comTimeoutValue() default 120;

	@AttributeDefinition(name = "Fallback power", description = "Fallback power after communication timeout in W")
	int fallbackPower() default 4200;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "EVCS EVTEC Core [{id}]";

}