= Timedata
:sectnums:
:sectnumlevels: 4
:toc:
:toclevels: 4
:experimental:
:keywords: AsciiDoc
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../../assets/images


Live and historical data of an OpenEMS edge are handled by the nature https://github.com/OpenEMS/openems/blob/develop/io.openems.backend.common/src/io/openems/backend/common/timedata/Timedata.java[Timedata].
It describes basically methods to write and read edge data to/from a database. There are different kind of timedata providers within OpenEMS 
(see xref:service.adoc[Service] for concrete implementations).
 
Within OpenEMS Backend the only component which uses the different timedata providers directly is the  
https://github.com/OpenEMS/openems/blob/develop/io.openems.backend.core/src/io/openems/backend/core/timedatamanager/TimedataManagerImpl.java[TimedataManager].
It passes edge relevant data to **all** Timedata provider and it reads the data 
from the **first** Timedata providers which can deliver it. 


[NOTE]
====

Beginning with OpenEMS version V2023.08, data handling has changed within OpenEMS Edge, OpenEMS Backend and OpenEMS UI.  
OpenEMS Edges will send different types of data to the OpenEMS Backend:

* `TimestampedDataNotification` 
 ** channel values which have changed 
 ** every 5 minutes a full snapshot of all channel values is sent, including channels which haven't changed over this time period. 
* `AggregatedDataNotification` - 
 ** average data (`avg`, e.g. power values) - will be sent every 5 mins. 
 ** maximum data (`max`, e.g. energy values) - will be sent only once per day. 
* `ResendDataNotification` - TBD (coming soon)

Splitting the data enables OpenEMS to implement different timedata providers, 
which handle data differently. This gives more flexibility when scaling OpenEMS.  
Also due to performance reasons the computation of `AggregatedDataNotification` is done on the edge side. 
This helps keeping CPU load on the database server low.
  
To get a better understanding of the new edge data concept, have a look at the   
xref:service.adoc.d/io.openems.backend.timedata.aggregatedinflux.adoc[Aggregated Influx] bundle.

====

