= IO Alarm

Switches a digital output, when one or more State-Channels are set. This controller can be used to signal alarms.
This controller is used to check for the State-Channels which are boolean type, which typically represents the error channels. A specific configured digital output channel can be signaled based on the configured input State-Channels(one more channels).

== Configuration

- `Component-ID` Unique ID of this Component (id), e.g. "ctrlIoAlarm0", "ctrlIoAlarm1"
- `Alias` Human-readable name of this Component; defaults to Component-ID (alias)
- `Input Channels` Addresses of the input State-Channels (inputChannelAddress), This is a array of input state channels.
- `Output Channel` Channel address of the Digital Output that should be switched (outputChannelAddress)

Multiple instances can be created in "Apache felix" during the configuration for each Output channel signal.

== Example Configuration

- `Component-ID` : ctrlIoAlarm0
- `Alias` : myIoAlarm
- `Input Channels` : [ess0/State15, ess0/State33, ess0/State43]
- `Output Channel` : io0/Relay1

NOTE: ess0/State15 - represents the State15 channels of the ESS0, 
io0/relay1 = represents the relay 1 of the KM tronic relay board.

The above example configuration describes, if any of the configured three input channels is set to "True" then a signal "True" is sent to output channel, else the "False" signal is sent to output channel.


https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.controller.io.alarm[Source Code icon:github[]]