#!/bin/bash

# create temp file and redirect everything
tmpfile=$(/bin/mktemp)
echo $tmpfile
exec > >(tee ${tmpfile})
exec 2>&1

# Verify that fems-pagekite service is running
/bin/systemctl --quiet is-active fems-pagekite || {
	echo "# fems-pagekite was not running"
	/bin/systemctl start fems-pagekite.service
	/bin/systemctl --quiet is-active fems-pagekite && {
		echo "# fems-pagekite is now running"
	} || {
		echo "# fems-pagekite is STILL NOT running"
	}
}

# Verify that year is ok
if [ "$(date +%Y)" -eq "2000" ]; then
	echo "# date was wrong"
	/usr/sbin/ntpdate -b fenecon.de
fi

# Remove old log files
rm -Rf /var/log/*.[0123456789]
rm -Rf /var/log/*.gz

# Send file if there were messages
if [ -s ${tmpfile} ]; then
	/usr/bin/fems-sendmessage ${tmpfile}
fi

