package io.openems.edge.pytes.dccharger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;



@ObjectClassDefinition(//
		name = "Pytes DcCharger", //
		description = "")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "dccharger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "Pytes Ess id", description = "ID of Pytes ESS device.")
	String ess_id() default "ess0";
	
	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readOnlyMode() default true;

	@AttributeDefinition(name = "Pytes ESS target filter", description = "This is auto-generated by 'Pytes ESS '.")
	String Ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID' from Pytes ESS .")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Pytes DcCharger [{id}]";

}