= Virtual Meter 

== Virtual Subtract Meter

This is a virtual meter built from subtracting other meters or energy storage systems.

The logic calculates `Minuend - Subtrahend1 - Subtrahend2 - ...`.

Example use-case: create a virtual Grid-Meter from Production-Meter, Consumption-Meter and Energy Storage System (ESS)
- by definition Consumption is defined as `Consumption = ESS + Grid + Production (AC)
- or: `Grid = Consumption - ESS - Production (AC)
- this can be achieved by configuring the Consumption-Meter as Minuend and Production-Meter and ESS as Subtrahends.


== Virtual Add Meter

This is a virtual meter which is used to sum up the values from multiple symmetric meters. The use case for this feature is, Usually when there are multiple meters reading values from different systems, The average values from the systems make more sense for calculation and statistics. 

Implemented Natures
- ElectricityMeter

=== Example Configuration

- `Component-ID` : meter0
- `Alias` : virtualMeter
- `Meter-Type` : PRODUCTION
- `Meter IDs` : [meter1, meter2, meter3]

NOTE: Meter IDs is a list of the meters which needs summing of the values. 

The above example configuration describes, The values from the three meters configured (meter1, meter2, meter3) are summed up and average values is set to the corresponding channel address.


https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.meter.virtual[Source Code icon:github[]]