package io.openems.edge.system.fenecon.industrial.s;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;
import io.openems.edge.system.fenecon.industrial.s.enums.CoolingUnitMode;

@ObjectClassDefinition(//
		name = "System FENECON Industrial S", //
		description = "Implements the FENECON Industrial S core component")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "system0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	@AttributeDefinition(name = "Cooling unit behaviour?", description = "Should this Component be forced to cool down?")
	CoolingUnitMode coolingUnitMode() default CoolingUnitMode.AUTO;

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id();

	@AttributeDefinition(name = "Battery IDs", description = "IDs of battery devices.")
	String[] battery_ids();

	@AttributeDefinition(name = "Cooling unit error channel", description = "The channel that indicates an error condition of the device.")
	String coolingUnitError();

	@AttributeDefinition(name = "Cooling unit enable/disable control channel", description = "The channel that enable/disable the cooling unit.")
	String coolingUnitEnable();

	@AttributeDefinition(name = "Emergency Stop State", description = "IO for emergency stop state.")
	String emergencyStopState();

	@AttributeDefinition(name = "Acknowledge", description = "IO for acknowledge.")
	String acknowledgeEmergencyStop();

	@AttributeDefinition(name = "Spd Tripped Channel", description = "IO for Spd tripped.")
	String spdTripped();

	@AttributeDefinition(name = "Fuse Tripped Channel", description = "IO for Fuse tripped.")
	String fuseTripped();

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Battery target filter", description = "This is auto-generated by 'Battery-ID'.")
	String Battery_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "System FENECON Industrial S [{id}]";
}