package io.openems.edge.deye.battery;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Deye.Battery", //
		description = "Implements the Deye Battery")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "battery0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readOnlyMode() default false;
	
	@AttributeDefinition(name = "Debug mode", description = "Enables Debug mode")
	boolean debugMode() default false;	
	
	@AttributeDefinition(name = "Extended Debug mode", description = "Enables extended Debug mode")
	boolean extendedDebugMode() default false;			

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbusId() default "modbus0";

	@AttributeDefinition(name = "Modbus-Unit-ID", description = "Unit ID of Modbus bridge.")
	int modbusUnitId() default 1;
	
	
	@AttributeDefinition(name = "Max. charge current[A]", description = "Maximum charge current. The hardware configured values will be overwritten")
	int maxChargeCurrent() default 10;	
	
	@AttributeDefinition(name = "Max. discharge current[A]", description = "Maximum discharge current. The hardware configured values will be overwritten")
	int maxDischargeCurrent() default 10;	

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Deye Battery [{id}]";
}
