package io.openems.edge.app.evcs;

import java.util.EnumMap;

import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

import com.google.common.collect.Lists;
import com.google.gson.JsonElement;

import io.openems.common.exceptions.OpenemsError.OpenemsNamedException;
import io.openems.common.function.ThrowingTriFunction;
import io.openems.common.session.Language;
import io.openems.common.utils.EnumUtils;
import io.openems.common.utils.JsonUtils;
import io.openems.edge.app.evcs.HardyBarthEvcs.Property;
import io.openems.edge.common.component.ComponentManager;
import io.openems.edge.core.appmanager.AbstractOpenemsApp;
import io.openems.edge.core.appmanager.AppAssistant;
import io.openems.edge.core.appmanager.AppConfiguration;
import io.openems.edge.core.appmanager.AppDescriptor;
import io.openems.edge.core.appmanager.ComponentUtil;
import io.openems.edge.core.appmanager.ConfigurationTarget;
import io.openems.edge.core.appmanager.DefaultEnum;
import io.openems.edge.core.appmanager.JsonFormlyUtil;
import io.openems.edge.core.appmanager.JsonFormlyUtil.InputBuilder.Validation;
import io.openems.edge.core.appmanager.OpenemsApp;
import io.openems.edge.core.appmanager.OpenemsAppCardinality;
import io.openems.edge.core.appmanager.TranslationUtil;

/**
 * Describes a Hardy Barth evcs App.
 *
 * <pre>
  {
    "appId":"App.Evcs.HardyBarth",
    "alias":"eCharge Hardy Barth Ladestation",
    "instanceId": UUID,
    "image": base64,
    "properties":{
      "EVCS_ID": "evcs0",
      "CTRL_EVCS_ID": "ctrlEvcs0",
      "IP":"192.168.25.30"
    },
    "appDescriptor": {
    	"websiteUrl": <a href=
"https://fenecon.de/fems-app-echarge-hardy-barth-ladestation/">https://fenecon.de/fems-app-echarge-hardy-barth-ladestation/</a>
    }
  }
 * </pre>
 */
@Component(name = "App.Evcs.HardyBarth")
public class HardyBarthEvcs extends AbstractEvcsApp<Property> implements OpenemsApp {

	public static enum Property implements DefaultEnum {
		ALIAS("eCharge Hardy Barth Ladestation"), //
		EVCS_ID("evcs0"), //
		CTRL_EVCS_ID("ctrlEvcs0"), //
		IP("192.168.25.30");

		private final String defaultValue;

		private Property(String defaultValue) {
			this.defaultValue = defaultValue;
		}

		@Override
		public String getDefaultValue() {
			return this.defaultValue;
		}

	}

	@Activate
	public HardyBarthEvcs(@Reference ComponentManager componentManager, ComponentContext componentContext,
			@Reference ConfigurationAdmin cm, @Reference ComponentUtil componentUtil) {
		super(componentManager, componentContext, cm, componentUtil);
	}

	@Override
	protected ThrowingTriFunction<ConfigurationTarget, EnumMap<Property, JsonElement>, Language, AppConfiguration, OpenemsNamedException> appConfigurationFactory() {
		return (t, p, l) -> {
			// values the user enters
			var ip = EnumUtils.getAsOptionalString(p, Property.IP).orElse(Property.IP.getDefaultValue());
			var alias = this.getValueOrDefault(p, Property.ALIAS, this.getName(l));

			// values which are being auto generated by the appmanager
			var evcsId = this.getId(t, p, Property.EVCS_ID);
			var ctrlEvcsId = this.getId(t, p, Property.CTRL_EVCS_ID);

			var components = this.getComponents(evcsId, alias, "Evcs.HardyBarth", ip, ctrlEvcsId);

			return new AppConfiguration(components, Lists.newArrayList(ctrlEvcsId, "ctrlBalancing0"),
					ip.startsWith("192.168.25.") ? Lists.newArrayList("192.168.25.10/24") : null);
		};
	}

	@Override
	public AppAssistant getAppAssistant(Language language) {
		var bundle = AbstractOpenemsApp.getTranslationBundle(language);
		return AppAssistant.create(this.getName(language)) //
				.fields(JsonUtils.buildJsonArray() //
						.add(JsonFormlyUtil.buildInput(Property.IP) //
								.setLabel(TranslationUtil.getTranslation(bundle, "ipAddress")) //
								.setDescription(
										TranslationUtil.getTranslation(bundle, this.getAppId() + ".Ip.description"))
								.setDefaultValue(Property.IP.getDefaultValue()) //
								.isRequired(true) //
								.setValidation(Validation.IP) //
								.build()) //
						.build()) //
				.build();
	}

	@Override
	public AppDescriptor getAppDescriptor() {
		return AppDescriptor.create() //
				.setWebsiteUrl("https://fenecon.de/fems-app-echarge-hardy-barth-ladestation/") //
				.build();
	}

	@Override
	protected Class<Property> getPropertyClass() {
		return Property.class;
	}

	@Override
	public OpenemsAppCardinality getCardinality() {
		return OpenemsAppCardinality.MULTIPLE;
	}

	@Override
	public String getImage() {
		return "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8Y"
				+ "QUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAFQMSURBVHhe7Z0JnB5Fmf/r7cnM5L7JHY4kkIQQTpH7TCaIeK+L67HqKuq6uAghJAEF8"
				+ "YQkiKAiouJ9rLvey/LXJKjIJYjcECBcEgjkIIHcyWTe9//8uvuZed6aqj7ea9633/rm86Sfuqu6qmuq6u2uUg6Hw+FwOBwOh8Phc"
				+ "DgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw"
				+ "+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcD"
				+ "ofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh6PK5MJrVklbvgJJXBjppxw9s"
				+ "3innOep9oH/RkV9JxX5c4V7f3pXYdPzoWsvqnmvEAdAPKa4pTsw+QFxOq4gSi8VU3rApjOcdqYo50bWO7bKjKvoKLgRmOKTbkl1X"
				+ "CXSzuTOsJseH2DdFI+uA91N+pFExdOte/MWn0LGq0k9ku3I/DNV6Lo4v2LpmsAcG48kzn+p4YCuA5jLCQukG2Oyqyacp0xRyxtYa"
				+ "2yNiSmlAcm4bDqQces64DBsL7HZ9zWcL708vu7Nu3g/Mi4llUZVOUP+C9vJfpnq6lyWv+WqnbAgkfEAjh/oadj8ROm4Al0HcX7K0"
				+ "QHMNr0WcHqZolY3ry8wla2SDQjhZVhp1t36gmrmoTtur2PxIOqfFpM6n2QA7MDQCWPUyKn7qpfuf0zt3rYjtPV5XhUKiwsbnvp54"
				+ "YFfIJ6+pt7qDVQiH/VwbytOPVROtejrsqVtdPqDA0xmW7x6GGDza8KUpk1XuSPPbsmNmvJe6qy+RMaJsAP9hw5Wk489TA0/YLIfI"
				+ "r+3S6174HH10gOrVNfevaEvnzuo47ogv+LKe0MzpyHzIXWg5yOpjisw+WH0cCDKv0T61/WoONgvkP5lHEA3AxmfdGc9k8gbkDW48"
				+ "tKWUW8I1b5HnEYl0tLzDvQ4dT9J0uS4fGj6dxzZfIVCHhNaqZbWfmrCkbPUmEOnK6+lJbTtYQ+Nsl68+wG1cfU/QhufPMkPSS7JL"
				+ "7/iJd+mB+RLzx+bi/JDyPLYsPmR8TPsR6Zl0yUme1P8tcCUv4anr25mLeDGU6sy6mnVMu2a4M1dNEl53hWkvofEL1sul1OjD9pfT"
				+ "Xz9Yap1UH+2trJ93Ub1/B33qW3rXwltfLaSXKHynV/Jr7xqd2AVS9r7nbY+pH/owBY+bV4Ym79S45MgTOZIexMaCS4bV1y1y5q2U"
				+ "Zn8p7XTrzpJ/MEO6P6Ar3tz5g9ULe0LSF9ILoM4hiHjRqt9jz9SDRwzKrDoDsZaLvDKsYYUCgW1afVz6oW7H1R7tmP9vZtnSBaqH"
				+ "Zt/lb/9m4FNT+ieyAN0O5FCL3s9LJD+gcmPxBZ/FBzGlj7bS39sr6cnzTqmeDJJ1E1odLjimTRljWog0o11Tke3B7obYDtgClMJy"
				+ "o4vN31uLrfv686mYdQSMu4b2CrVPnigmnTs4f6iuvEHwYTkOzvVS/evUi8/+LjKd3WFtj5/puxfkF9+5YOhmZH3DSBxeX+j3IHNP"
				+ "3QGdqa44rCF4bj1dE1pAumP0f0ngePJFGlvQiOBsnFFl1LhzcvQcco75oNHUWf0FTKdGFgq1dKvRY07fKYvXr9+oW357Nm6Ta356"
				+ "4Nq09NFL5eiB7uRerJL8yuXbiBdr8Oouk1qZyNt+DRx25BxsJ42Xj2OzFHuTa5nGq1s3MC4oYJSdAAz2+t2JrrdvLmLqLfyvkjqB"
				+ "2CEHRg1bT9/VNU6aEAwqCrQf7kwGE3xgtD+f/6Uj/VgANZjlpofLIjMt922dr16/s771PYNm9kTeI08fl7t3fX1/J+u2RPapaUn2"
				+ "WTAP2MLJ+OU/oEpDPtJk49y0POUCWp18/qCapVNb6hSBzCbdAnb69ekwD/Qw0SlB6z+vTkX9lctbeeTejFZDeUgg8eMVPsef5QaN"
				+ "G60b64cSJaz1QM6u1cef0a9cM9DqnPnrtDW50lyvKjw95/eVNj0vKmMlSLqHlbCHkg3XdeBG9vbwph0vmYK0w3KCtUoGxqBjFc3l"
				+ "0Il4kiCMZ3c1JNUbsoJb6ehzjIyTglslWobOEBNOuYwNfKg/f1RkClwkoyXWriuPZ3qpfseVesefoJmhXj7oZvlKp+/ML9yyaOhu"
				+ "ZHhW4PbBHSzCfiR/m1+o+JoWEppS41CXNlQoeWWP20cUf65genuae1Bonx5HYsPo97oalJPC2zIrqVFjTtsuhp/xMHKa20lG5q6+"
				+ "S7BL37+dI8UmAIXtifNT5H9d7v4GgNXDhvYFneG7O7r5LBny1a15q771ebnXvTtfApqL3n5psp3Xp5fedWm0NZRDFdDpuhpSdmjm"
				+ "mXjZ6z4aSzG5Meky6uOzR5EuUXizVs8hoJ/joKfQ9futzxHTpmsJh97uGobOohMnM1S4CJVji0vvKzW3Hm/2rFpM5k47gI6q8vVt"
				+ "g035O+8sTOwc4SU1Dbqncq2qvqiUmXTnz5uCLCTelJkQ6rl/S94p32yXbUOOJeSvZTMwwNrpQaNHqEmH3+kGjKB+rGk6HelBhTye"
				+ "bVx1dPqxb89rDp3Fb1f+hi5Xpi/8zt/UNs2hlYNg96OZPtgbH5s/oHNvqFBgbNKX5YNjcWWvu7GZmkfpQP2D9hNIsOo3NgZKnfY2"
				+ "84i7ctkPCiwVdR39VeTXn+oGjVjSvhrXUBRYJ2euV+MR4HNn27vmw2eNfu9u/eol+59WK179ClVwPpWj/ebqFdbkF+x5MnQ3Mzgh"
				+ "mUOUzPKCtUqm3yionQAc5y9vFYcmv7NouipoyqcwSl5XosaO/sgNf6oWaqlDetUMnsmvT7ZtXmLWnPXferV5/EZYvdt3EPq11W+8"
				+ "wv5W778Kvw1KVVpT31NfbfI8qh12WxPuG7f/WSF16rgzVkwSrW0Xkbqv5OgV/IZsf9ENfm4I1T7sCGhTTpkpm16FMnCmF3YtjiOg"
				+ "tpCHRbWt3a+uiW09VlPrpepV1+8MX/Pj4peo28ScJsyh7m9ZAO9besUt3szHAejxxUVvwmOS4bhOGRc0l+U3su/d9r8FtXajk7qc"
				+ "hL+yE8NHDnMX6caOmkseQ5+pysObtJ78G27nYJfAk2xBP8RsCRdzDSLnHzCwGwvte5fCqHTf3hPFaYcKYEOen5xVF0Ftf7R1Wrt3"
				+ "x/xp4yCB2maOD9/+zf/pHa+Flr1KX6RArWq9NzMDFGLG9dXVKts3BD0+GVDlH7i7OUVSN2G0T9N/+bR5WoyzfJtidb+7Wri6w5Vo"
				+ "w+eSh7weLN3etAL9MD7/kLPIkp2C7qEahDkodLs3blbrb33IbX+saepDPz+FtIp/Io6roX5FUvxgXUzwJWZKarTFusDLlvPU2hH+"
				+ "rHpdYs3d+FBymu5itQ3BTaUYc9TY2dNU+OPmq369W8LbSsI7kwF7kpZ0UQE3vnKq/761msvrAttfHZRmGtUoeuK/MqlmD9Wu15NO"
				+ "bTlukJ3tBvElzmqXWF9DcrHFce6bgf0xiL9SftaIfMoKbL35l40jDqqS8n6E2Ts7pWGTx5P078jVP8Rw4oKoBeGzbp97eidcrGNN"
				+ "JlyGZ1zjBJfe+5F/8XTXVu2hbY+L5Hrp9TubT/I3/r1otfoCUSIiBndzJRqL92hgzT2Nh2wf8BumYILl2VMZSy1YuvifnnHn9OiB"
				+ "o/+EKmfpyyFL08V1IDhQ/11qmHUYfUsHulFNelm5Fvn9UBxjuPLxfkvdHWpdQ8/qdb+/VHV1SnXt3J/p17t/Pzd379DbXk5tEsQc"
				+ "Y+OK0ij41oqacJzupminJtX73DZZIMBstKjGkCaxlEb2gcr7+RPnEqdET6nOTywVKpfe5uacNQhaswhB/pTwcpRf7fAp8Rsde7Yq"
				+ "V6852G18Yln/NFXCJSfq3zXYpomWg9PJGSqfXVjbOma7GGXOfriptcSlI8rjsvKlSvtbXZAD9cneB2LDqDeCB8ov52E8oFFcU/tM"
				+ "3Oqmnj0oarfgHbfn47MtK0AaQpWqZuAeECpcXE+eq49o0HpBvQ0dmzYpNbceZ/a8hK22eoGR/tcpfJ7l+ZXLtseWEUik5DE2etZS"
				+ "6NLouyBya3h4cJlEa7Qhi6jN+fCIaqlFcdoXUDSn4s1bOI4f/o3YFT3FzZVx3Yzy7nJMqxJt7kD3cwk6bwwwnr1mTVqzV8fULu3y"
				+ "v6p8AL9t1htXvOz/N9+oq9vVQJTlpNiux0mnYucKcq5efWOrEDAlahXbF/D+SoiN+tNXm7iIe8nDZvpjQ9sw2O0jjtCDT8AJ2tVO"
				+ "vtVuiX1cqcN+MeQPYhjyB5TXZ1Fx5DdRfm+IL/iintCcz1ga78mHdfMUafNqGLIiovSgV7RJnu2qypex+ITwnWqowOb8Bito2apM"
				+ "bPNx2gloZwCyLA9I5jiZfliP7a0Ss1FT7hAC9IG+D9trNI/Ytq7fad/KMbGJ58LbQFe5Mr9mC6X5FcsEfvb+HCyOnH2ScIl0ZsS3"
				+ "ICsIsuGSubK1hsAw259hjd34b7UG11J6rtI/Lzgx77R06cEx2gNxDFatcJwOxLdoT6/jWXhH0N25/1qG10F22gOuYQ6ri/nVy4tO"
				+ "ubHAArP7UvC9mlvTqk31JSHhqdxW1Y8smxc6Xolsp3pPpjsZRxpdSveaRcMUq3tF5F3HKU1MLBVasj4fYJjtPYZGdrUOygqiiy1B"
				+ "qRQUJue+oe/vqUdQ/YcFWxh4bm7fllY/efYeq0Ctttqsu+L/FWdhm1TJYCyciUm0SVsj2vFyM2cl8tNPupfSMWoarJvScm0D8Fx7"
				+ "4erEVNw3HvyJPUMDmtrUWP6t/r2eXoI92KheXeX2tIZfAs8sJ+nJgxs6y7c3nxB7erKq5d3BnvhjaDwI9r7qe2dZLcLdsWL2ZMpb"
				+ "FtLTq0j/9v2BuvTcJ0ypF3tO7hdtXo5P75Nu/eq57buVtvJD6ZfgS9cQRDjKEoH+X1l1171aic2FMWkL8D3TYbgUyEJxxXAGtvK8"
				+ "ED6LtblxLaHPOXj5QdWqZceXOWvdQn+QhnCMfv3hWaJTFrC9voVcOJ6OJPfpoZvVBbRK7uuyup1LD6ankAco3V8YFNQLa2tavzhM"
				+ "9XYw2aUfYzWyeOHqi8cPZmSyKm9Yk/0lS++pr54/4tq+rD+6rqTpqj+LZ7qFO47qVN54+8f9/WvHr+/OmqfwWo3uZ/5/1bRteeZ2"
				+ "XdQm/p5x3SFLui/n9qorn0kePHy4wePVR+YPkZtoo5nBz3kHqXfRh3Xz8jPT0h0ECPeHPsFxTWsvUU98epOde7tzyarsRrV6p6t2"
				+ "9ULdz+gXnmq1zFk36Np4qfzK5bI73+4vdnQ22OcznGltc8kXNgsoldkXeDNvWiC8lq+RFl6H4yBrfKPe8ehD62DumeEZbHsmP3U4"
				+ "FZPfeKOZ7GRQS/+c9Y4dfrEYepdK59Ue2hk1QuyuvHUqerRTTvUWfuNUJf9bY26Yx1OlA9434Gj1RwKv5lGTxupc/rSfS/6I6A/n"
				+ "DVT3fTcZvXVR7vfHI/l4OED1A2nTFHn/uVZdf3JU9RbqMN8heKtKFGtwObm24eOdNn28obwGLKibeS30GjrC2rXlq/lb/uG3AY1K"
				+ "sVKIdPQ04M5c1Tyteh6AxXGlSZ1Rne3EeWWGO/U8wZ48y6+hIZONHzJvZ+i9e/94LGj1MFv71AHnH6cah04sCixHr13FmCj2wbTr"
				+ "QDqq9TLOzqLOqsid5rKYfqFzorjYlf/Sk2/P/nZRqOku9dtUyeNH0L2gQ/8f/K4oeq2l7b4IzKM0rDlCw2kaJrZop7agm+Mwzgxl"
				+ "wtBeJjZjf9Hx3nfhu3qoc071Ivb96hTaHTIwMdAir+dIkdITFOPGDWQprLBFl9+nPRvME1vMQWF/7EDWn0/mGYGKZA/yhvroEjHY"
				+ "25yhD33AXQZPH4fNfMd89SUU49RbT0/gAylnnqpGjDsYarft+AUIgIxcKymmHX7KEzhdXT7pHE3HFnusMKW5l9ZGFSoNAPYcUXbr"
				+ "mnw48+Nn5Xz5i1+J7XwR8j4BZLBsG+jkdRU6qRmvK1DDRobnvlHIWSmenRpG4A//Lqtvw7TndOeNSAf6ih61mng0qNDYwHBtaAGU"
				+ "OeDDun2l7eoE6mDagld0BHMog7h9pe3+tNErIXBBZ3jK7s61ZGjB/kNy49TrMEhfZh9+26boMO6dW2w+d6t1AnOmTTM1wHcPzl7v"
				+ "Dr3kHHq00dMUr+YN1196fX7+de37z/SjwH/lh67n3rvtNHqy3T9yekHqiV0/fUZM9TxY/zb7ccTpBnQS7c5aiD/2FL6kH95k5qAk"
				+ "4WoMw2ZRvKb3NQTl1N9zyZd3n7oRdVBcCq6P8akIwzr0l3mWNpnjix3WIypArni5RVENQhTPFEUvI7FR+Rmv+WPFPy/SQ5ADB51A"
				+ "hOPOkTNpgbPZ/6VhC2YsJ89cqBafPjEQI6YqBYdNkH1892D4hwwtF1dd+IUkgO65YhRODEH5PwRFkZgd9JUEIvvM0cM8F1OGDtEb"
				+ "djZqZ58bZfa2RWMsJjvPbFBvZGmkL8+Y7q69MiJ6qzJw9XINvt63EyaDo6j0dJt1Cni/ty69jV1OHV46BR7KKi37DdSrdm2R5118"
				+ "yp/Pe0XT7+iPjpzbHcDxkDu3dRhoeM74+bH1Jnk7+51W9Q55CeWJDUr/ZCOraUn0hT+kLPPUiMPmBQ6+Myle3cfjbau8+ZctA+Zu"
				+ "UZwDW58gBZjN9BNfpKQ1n/DkeUOy9QI9Apls37Vsdkb8ToWjqEG+y3qje6hoKeE1mrUtH3V7HedpSYcPVvlWoMHUkYM3ZQRto9yA"
				+ "z16oKEzWb9zTyidvkj/WBj/zbObimTtDmyJHtBOHdGOzrx6dU+XenjTdnUSjbIAFvTveClYz9pFIzCMsJhfP/eKeu8tq9Uvn3mFO"
				+ "p1WdSF1kr9+w3R1InVyPH0DrGN09RR1fF3UMY6kTgrT2C2796pTJwRpcV7u3bBN/WD1erUrjx8ICuoPL7yqhre3+J0dc/Pzm9Xvn"
				+ "t/kj/S6qAfDDwwHDuuvqN/tjifQekw+3KUUwTkNkX6E3j5ssJo67yQ1482nq4E9n0lR5Rb+Q7X0e4LawXnenAt56x8t4SKz7qYDd"
				+ "/ajh4sLmxmy3GHpTYyFYV1eo3Q2W/FO+UQbTQcWqFzLE2Q8h6QFwXCM1sy3zlVTOk5QbUOCEYyMnJGJmOyL3MIm2sveJ7BFR/BdG"
				+ "vFAbnxivfrekxuK1rReo45oOT3UK4TgFQWExkOOX/d4QR7Tv5OpE8Go62iaZvkjIgKvLfQXHRamZ89u3a1+tHqjOv+u59QbaTT0w"
				+ "Mbt6kMzxvhu+IcYWUeHdRCNsm4+62CSmeqmN85UI/q3+vZBfD3Af7DglFNbKO8YnQ5uDd7654Gq7yfU4KcN618kvq1flCB8PD0xx"
				+ "UIeh0wcqw7+pzPU/icfrVr9D9H90CNIrqHh2IM02j4TFhHI5FjXs6CbgSlcZslyhwVQgUkq0VbpyRrA4NE5apBvVu1DHqYgS8nGf"
				+ "9qwMHvAqceomdSQsWAr+oryseTMXpAek82PBAvY/UiwhgVupxHVAUP6qzdMGu6PXu6jTgigwxogpoQ6u6iH/Ou6bWrCoJ5dTzlN/"
				+ "Do4nuw/+MfVat5Nj3XLQuroiqeFIpeh2hZuo4N3xwCmhHpZ0Fnh/TOM3nxsha0Q2Npnn4On+dP98YfOkFv9kCH3fzTaupnayYzQj"
				+ "jHlChmGPV+BNJvCNAVZ7rBQuSxAvyZB+jWG8zoWHeId/5E/UIP8LXk50LejBwXvU2FhVj/zTweRmjIm7YHNTV6lPSPtpB+MtAbhp"
				+ "0Rhx0BHh4B876YpGMzPbdutnt+2S11AU7y712/rtkeHNIBGWMXhg+lUIAXqrFrVDur42AzwP0ZRz9Io8HGS1zq7fMFLrVgz205XT"
				+ "AvZt34HZ48aoDqpI1pLU0gG+Q38B/FjDW89ue/mDsuA3aUY6Q+6LRzsW9rb1KTjj1CHnH2mGr7fhMAh4EzK5EPUcV1DHRdGX4Cj0"
				+ "qPU7eVV+tX1THdmWS6cqWyVqFCEL3inXzhatbReTg3wo2TuXiHGAuykYw8v+RitgPKzec1x+/vvSH32PuyW0ptjaVp39fH7+9NGd"
				+ "A4MRkwX3PUP/9WA375hhvrYrU+rBzdhq6jgzffhbf3U+l2d/tvvyOKb9xuhLjx0gjrtfx/1c42F/bEDW7tfMsUo6ZBRA9WPaDp6/"
				+ "WM971eidL+cN139Yc2r6oZVRfuu+1x+1CS1D+UBL5FefPhENW/yMPUSdT54sRQTPExPV77wqv8SLLjuhAPUjBED1BrqWPFaxaB+L"
				+ "b6fbz26Tv1gddG+VzVny5qX/Pe3dm7GNLq7bjeSfpnas/Pb+T9fyxUgK75cPZNwAbOKXj5ZqUno1SC84z/cqgbv83FSceZf90d+A"
				+ "0cOV/uecKS/llEP4NWCPdRpPLI56GxMTBva31+URgEx8cP0ClNAvCCKhXS8ynD3+q3+WpeZgho/sE3NGjHQX+AGx+wzWE0Z2q6GU"
				+ "seGdTAs/D++eaf6K43K5FOE96pOmTBM3b9xm9qwq/dLopMHt6mDhg1Qt1C86LBGtLeob69ar15PHe1Q6jjxqc8K6rD2+pEWqMOao"
				+ "p54baf/K+ERVHasq62ijvbWl/llV3vV213iSB4Sx+xveHS1evHeXseQPUzz2fn5u79/i9ryclyE0j1KzyzJ7nZjopctrjFEkhu5r"
				+ "8od9Z43UAxfJtPM0Do4RuvoQ9XomTT1M2xPXFai5dKniVcOdFij+vdTC/76j9CmNxhhraYO65rwE6GqUsZ93bsLx5A9otY/tpo6s"
				+ "aK+5bcqn78ov3LJU6G5XIoizwpZXsPS4SYmKzJJpRa8jkXTc697z000/buZzH5nhc5p3KHT1ex3v0ntM2sa3Uncyp7oelZxGF696"
				+ "dF6bJKQxm9IBjqruqSM+9qP/sDte+JRatY7z1TDJo0LbX3eSm0Ib8sv8ebMxzsdxY2nh7R6psh6k05aPlSw7NB83Ztz0XDV0g9Tv"
				+ "/8g6TlGa98J/jFa7cOHkMcgmIxAN2WKChctiC460iNHDfRfTbiLppU2Tho3xJ+6PrQJv15yXKVktpp1p8eNY8jWqudxDNlrPd9pE"
				+ "hgmXqq2b/xe/o5v83wcAREBYL04st7mzCELmDVKLpt3wkdb1KBRHyH1syTB+wgU24ARQ9W+xx2hhlKH1RjobdhRjxTwgu8jOIbsE"
				+ "bV3T8+vnsR9CtvY3PWd29S23jtdxOA6rAZDL1v80zt4tPKOO+d0mvpdTd4PZe84Rmvi6w6hqV+lj9FKhsx4El2CaWeKVyAdfcjen"
				+ "bvUi/c8pDY83usYsl8o/5j9JfZFvN50R5AlmqElm5/jYnvfHB6l9XRgRRa5nBpz8DT/UxqsPQAZ0Kb3jp5JH6I+icptXEls96Dad"
				+ "6CWaZlInuaOjZuDY8jWrg9tfB7LL7/ikFBHZAARxumZopkW3SV6y2Fz9+kOg0YNV7P++Uw1+aSjVAt1VnG1XxyhHj0j7ZOFqBXpW"
				+ "ndUbuNKYrsH1b4DtUzLhD1N/d4PHD1CTX/LHDVt3omqpWcjR/msIjKO0KZnkix3WLbKk+3D+pwOHj9G9R85lCKQE6rioOaW0fMbY"
				+ "LweQeihlz9hL93sujTZyXQrrz+wkL6TagYLU8+SPEz6XTQLXE719SuaDv6A5oTXjZgyeUmuxSvaLVBgq/JM0wztNHEZaUo4jaaET"
				+ "0Ifd8hBavKJR/n2Eqwt8Kc26Az87oyaSyHHa0VBF9Fb972FWrHebeq+lLnuVBx5heBIcQWs2xKyuUl7W5wgyg9ge2DT02KNB2964"
				+ "jQK/EyJn/O2kes2cvXN1Ca2UpsgvbCNmodvl4Pu+8mRe57scltVeM137t65/enH9qy69EN4XxeJIDHQS/fmXbyarthr63GaEh4MO"
				+ "xLAfnE1wf4yha2wWSB12by5C6cpryWyw3I0BEWdS/e1UNimctRxdOtkTx0MPdnofIKOiDof8kPmwtZ8VxeFJX/5wu5X7vh91zNfu"
				+ "5S81BbqsNAeZYeVFNdhNRjpOyx/hJULO6zpahJ1WNW+QVF/InWi/5z2jMqkPzkiTEaaHJUNEsPv+Ph+SHYw6ChCHR0MdRrSvUCjG"
				+ "qW2B37IPU8dCzogct+19rltD53/T7ZvieKoduFTx9/TYRWow7rSdVjhNavElU82IOwQeqAKO6yxNMLCG8m925i5zRXZmr1ExBRo0"
				+ "t0SRWrw63iq/iqSAnUEOYxe8HZmTwdSrIcdTC4YrZAdJe93MP4V0yJ0ONTJFLr2bt/5/FO7Hl38vmBXvp4iV+NWSKoRZ1JSldONs"
				+ "Irpq0qrBSgbV5osp6mR+Fd/hKW8J2GTkSkh1l7QiaCDQefRu4MJpkm4BmaaMoVrLoFd2MHAX9eeXTt3PPf43lWXftj0MJjuK6i0j"
				+ "iuI0oEpLIjSGdjpZmALa8PmP7EedFgFape5NB0WwmYSvjlZRJZNNgQrctG9Z4TVQ3Er6B2lbGm9kf4DXYSGBUYZ3WsvZIGOgvRCs"
				+ "L6Sw/qK2kqjJd+e3LeSfeDXnw5h0TdP0yPqYHLe1vyuHdu2PPq3PRv/cnNh053LyVtN6V1YR0m4KWExzdCQospY9DD17rCOJE0Ex"
				+ "/wK5pzfuWD0wlOjsAOhjgOjEdGpsDsFJj23LRcu9uZxxaKu38GorbvXr9350Hlvq/BhfJGgYNyok+i46m6A7YFNlySxZx1XkFQHH"
				+ "BYk0eNgv7gCk26KN0oHHBboOvDDGKaEMq4oOL5MkaTgjUpRxQdqNF7HQuqwgl8JB48Z+fsZb+/4FgXFtGg7xbK10NWJkczWvdu37"
				+ "Njy8D2dT19zsenD1Eoi8564HDXElr9q6rgCXQdxYYHUyyFJPDY/ifMQ02HZdABz5kh00xoUvfJg1iu1CNlhkddraQh+QaAnguMHS"
				+ "XSHIxY3JSwmy2+6o8JkRyGvjFapwrnYJUnlSz9J9L5G3gubLokrE666HmXHwrAu7ZPooBw9KXp4NtvijdJ1YaSuYayWCP/ZpBk+z"
				+ "YlqELaHU8fkL2nYckjYmEvCFrctHS4v3E060HWTm7Tna1w8jEm35SdpnBKEYaQO9PBstsXLup4PALMURvdnQs9XU9EMHz+jEaCS9"
				+ "YqW5lAXVkHTMfjpRjeXQlwcaRtzLbDlqZ71pJQb3oQeTwnxFjUTW/iotpoZmmlKyMIYdHk7fCub/0pRjThrhf6A6GZG6jpJwiSJy"
				+ "2bPwD3OTxy2fCSJl9NnSYm1mdjaZyO3q0iaYUoIuJHIxmJoOLFtKa5R2NzjwtWCSqXLNwnxST0J+v3ncKXojLQHupsO7Nhe1xmTL"
				+ "tOw6TbgR4qjRLI+woqilIaDODmc1AF02bhl+ja9llQqXb3MTKV15DetDmDWdVyT6EDqQOp9B3IVjfQR77tByfoaFlccN7qoxkd+j"
				+ "fWsW0pzEr1ZKKXMUffM1mmUqiP+tGElfVen/gehoW4nSRkanmabEkYRfH3cm2o1hL57AOyUU9ZS7g2Hwb2QOmPTo0gSJmlcklLKV"
				+ "wEoq5X7er3haZYpYbIalw3D/wynF6U0dBv12Aq5fLhWsqxxyHsRp8t8mXT4S6MDqdcZXGwjtjLUcXnKI+sjrHTIDit96HKot4ZX2"
				+ "9KnQ+ZN1/l+JdUZaV9NOA2ZVhJdAvu0YTJD1tew0pHHN82RyEZuQn8IGJvOpPFbacpJW39AKv3ARMVnelCRZ6kzScqVpLzlwmkky"
				+ "ZstP7Bntyg9kzTLlDAZ8WsFcXGaHiJg0+sBU95wteUzyp5voB7eFoYx+dXt9DhkWrLioOthGZsusdlXkhLy123U/bBZ1zNJ1qeEs"
				+ "uJsOrBVsCmM/nAwpei2dPsamU+dpGWzuZkw+ZVxSF3HZC/tkugSm301MLUvwHpw9f/3syXtWQc2PXNkfUqYtFGGZlHXgSr9sZ6ko"
				+ "STVbfnrK0zl1ZFlALq5VkTd13qH7y2uUXrxvtnSPl4ySdY7LG68+hUYGras54apc0M5Sibq/pjc5LUUASY9iQBdZ3T3ehHG5GaW4"
				+ "mZo9mOWTNJMi+76Xx6pBxUsX2UIXGXF90UjSJJ+cZOuHpwOrrpeqgCTXqoAk14vIpF20s2mS9L6zwzNMiWMq8jAvfd7WDJcXBw6t"
				+ "rBp4kzjt1RKzZujdEz3GVeTTnT/rbL5semZoxlGWLZRim3EElB+lSdJNzoPtSEub7hWU4DJPo0Ak16ugErrcQKkTnQ3Rpsfm545s"
				+ "txhcaXJrkfXIyq2/B6rAsj89VUjxI2opgCTfRoBJr1cAZXWo9wYqUuS2Nv8ZIIsd1hccfyg61cDRqe+6ihAPTbEJPdD+kmrNwO2e"
				+ "o2rb9wnkx9pr/vJFFkfYcnK069Aq1h5OxDUJ03ldwcikui1JipPLSSzSTpI5pEcRzKOBMB9KMlJJGNDc5QAvoKkepyANHopAmqlJ"
				+ "xBcAF+73YDUgdQzSdbXsNJ0NkTZ9W3rDG16HJVujLZ8vJfkHyQPkvyB5Pckd5CsJTmLBH4PJbmV5IzQnERAGj1OQBq9FAHV1oHNT"
				+ "ddDfDXKD9qH1DNJM0wJQcIKlN5k8D5DZqJaGTqN5IeBqv6dBCOr15OcSPIWkntIQF3ckIxgq1eD3uu2m/zjatIzR9ZHWAxXoOyRD"
				+ "J1YZus5iotIUPA3k3yL5G6Se0nuJLmJZAOJpC28Atv9jNLZLHUg9VKxxZc27qT+qxWvoIQgGaYZOizUOAseTNkC0rYG9s/xAdaj3"
				+ "IDUgdSTkjbMeJJ/I7mU5GKSfyYZQsL0I8G61EMk98MiAVyO6ST/SfJpEqx7yXs7kuQUkn8luZDkMpKFoR3/VcB1NAnWy6BDjiFBB"
				+ "/o6EgZ255EgDpTh3SSYlkIOI2HQkWJEuIgEfj9GMpUEeeI0K0214hXUIAlHXcAPgRRG133xOhYd6M27uBDI4mukm0WATQdxOvuvh"
				+ "ryVZAcJjtN/nuQFEuyf8xIJOhv42ZcED/RPQrMugPWTSeB3AckvSRDvGpItJLD/CAn7RScFu20kSPepUIcdOk/2h44Odug0sT4GH"
				+ "fJ2Erh/MzSvJvkjyV0kO0O7v5GgU4I//DjwGAnsN5I8Q7KbZC/Jx0k4vUYSDCZy1BZXh21ylbRPoGeSzBZMwA8BhGEdlduD/3a79"
				+ "BaLDK/rbI7S4zDlOQkYOV1PguncgST7kUwmOZYEo5rFJIgPIyHwSnjVQR71dK8g2UyCTg8d3hQSdCLvIGG/3yAZSILRHNKdRsKdy"
				+ "n+Q6GCRH50S8tef5Dcko0jQCX6F5CCSOSRYX8MvmZ0kK0kwhQUY5c0kwY8H+5BgZIVfMzFqRH5bSeJIc3+ZNGHSxh/6x6UoqDQk0"
				+ "TNF1jssveL0TqLY3f80p6g/0cPDHCUgrR6FzK+e9yjwix6mg98leRYWIRiVYFR0AAni4wcZIxEbnC7nFyOsc0ieJoEdRjQYtaGjY"
				+ "XaFItlOch/JGN9UDDoxxIkF/j0kiBf+0D7xayXg9JHuOhJ0TAD2mB5iBPKz0AxeI0GnNowEHTPbA12HxN1fGcZEVPwA8cfFYQDB4"
				+ "rLWPGS9w+LaZpGNxwx89DQrGUZHxsHxA5OOONiOdbZnkuiSKP+TAtXnCCF4RQEjHnRagDuV9vAKOC5cZbycf4yuWOdyYKrJOphIg"
				+ "s4SC/eYxv01vL6BxATywWGRJnTkEfbvJ+GRIEaOmC4ifozIANowzJtIUMYjw+vRJHNJ0FHKPANdl2Ygy83ofkBUnIxNrya1SqfmN"
				+ "MOUUCeiAVE7hU2xrcm/yU42cujSLMOZwoIkugT2nA7rADqPnC4n+buQ35Hg3aqlJGB9eOUXRAGnhyvrQJaHdU4fSP0HJO8huYXkv"
				+ "0LB6AdrSxL2D3Qda16YumIhHVNbjJjQ+WD97C8kN5AA5BEd2Qkksqz4tXMWySUkWM9iZD513YZ0i9NxjdNTIIMnpoR0GoMsd1imm"
				+ "pYPoIHwdiCEucplnCYdsM5p2fzytRxkpyLL9mp4xa9qmBJJwXTwERKAjgByFEnMvTG628IcTnI7CRbY8ePFtSRfJXmChNHLL+Nif"
				+ "QIJXmTFO2H4dfBNJFifwrtjXEaM7tCZYbqLt/EhKCeuw0m+RsLxIU3oENYZqevo4TnvpjC2OE1+E8DBEgfX72umyHKHJWvaVImGF"
				+ "hB6S9w2upEhTKGTxCjzaNMlbI+r7h+vKeBXvFNJtpLglzxcMWrBA87+of8/EizKv4tExiV1HVN5cWUd4aQ9mEGCRXUJu9nAYjsW0"
				+ "7Gwj5EhpphYk5PxQ8fiOhbjB5GgjFxWLM5LZHp6/qLg+wC/Mm2JKW5g06tFLdLoM5phSmhrYJLAvYDnN6QnhAwL3SSAryBKN/nXH"
				+ "0A9jAmbH+gYNWEahsXon5N8gATvYGE9CK8cHE8C4PcLJBit4G13vN6ARfVPkuB9pitJ8HoE8gRhWJf2UsfiOkZFnyPBO1T/Q4IFd"
				+ "bziYIPDAtbRmeKXSOQNnRJGUnhF4r9JMIpjvk6CdTgssuPdMJT1X0iwmP8hEpm3JDqQuomkYXVdmnWi3GzY0sokzTAlBKzbKjcYd"
				+ "eTodhT7xP82AeXqjK3zSYLNP95RupoEndONJFhDwvTofSSYajHoANC54FUCLIovIfkyyWdJ/okEfpEG1o/QaWBxm4E9BK8rYBGc8"
				+ "4K08V7VfBJMCzHSwejqSyT8gir8YuQHs2lRHNNUTCcvIMEUDy+JoiNCWfDpEDozvCwKv/9Lglca8AvjMhJ01t8jQeeMBXj4geCe6"
				+ "+mw2aYDXed4dN2Ebm/zB6LcbMgwpYRvKLJcwLiy6Y1XeXMXTlO5licD28K1+eVX4mExwWFlHFE6YP9ADyupVFgJRh+wx+IzOmc9D"
				+ "tYh0i+mleynFBCW882Y8sh+2D+uGN1htIfOCp2lDIdRFNbF8C7YkyQyPizA40cHdF7IfynoeZRm3a0adKfhzbsY5cN7bI/nl19xM"
				+ "OwSgjgyRzNMCYGp8syNrtvW2ib1uGBmO+lmStNGlF9khN2lzkizzLS05/eidL96vBD4w4ug3LGVAsfLcTLQOU5pD/S0kAe0T4yQJ"
				+ "LDDpzsIj3UqHbxThrCldlZAz4s0l3pPJHrZdQxpxAXxSeSpkWmGKaGsRJseEN8UbQ2i3EZseyBYx9WkA6lLbH6S6CZsZTdhiwv2H"
				+ "E+UDrCehunnn0keJ+GPsl8mwTeKvyLBC6syrC2PsI9yY+LiiSJJGPbDZUxBoiAlxNtYZLnD4srDVeqmBhoQ3+TiGoR01/3a0+17k"
				+ "uQnruw29HC2e6T7w9oaflnE5znonPDawm0keD3iTBIsqjMcVo+DgX2UG2OLp1L3J4kfRwTNMiVMRvLmJH0mDRUVhh8IXOXDYbNPg"
				+ "ikeYNKRnyT+k5IkTJL08GsnFs/x8ucnSLCmiF818e0hT/lKyV9aktZxFalFMeufrE8JTaI/nIKS2iXHC3RdopslnDCuMhM2+ySY4"
				+ "gGl6jL/trKwPcJElVcnTT6AjF/qUUg/cTquafwnJa1/gSx+85L1KaEuAI1GmnuQB6na6R2u2M7mbrKX6IlLcxkN3Ro2bZxxZQRJ/"
				+ "DBx7nGkSQvY/Jt0XNP4T0pa/4JymkB2aJYpoam2e9vJg1QDpB/W9SsC9Y4rQPqVfnT/MHPi7CbjjWrotnhN8YA4e2DTyyVtemn1c"
				+ "qlkXCbKiD+qCTQPWe+wohp2dAuwn/zMDzqbpa5jCg90/0n9mUgSthK67V7adBMyXknSfHD8Nj8gTT5xlfaStPZJ0PPqSEnWOyxuI"
				+ "PIqG03aBmRq4FFxsF/4keFYN9kxWFzG2+km9ifB293ylzIberylgs9e8DY8sN3DJPfzgyR4ReFREuxhBXmYBG+u45MgvPhpI0n8S"
				+ "fLGOq749Ag7smK3B5t/ic2+kvTUWbdWqWpsbJphSsg1nbChhd7Nvtk2SWOGzmZEqrtJpDvnF3uZY79zhu0BdvLE3lbYTVTam3TEG"
				+ "+cHxOnYwdO0+R7D/nCNigtvbWOvKuyPdTMJOirsl4UPsLG7KD7fYaLiYbPUdaT9+SR4ex5Ie+yMiv3DsAEhxyUlKUn8RvmRbj3to"
				+ "1vTm4yVNHluOJphSigfWFx1nc0EvHLD8K+aey+StiKbv6LEQuL86tjCVkMH8n7o9wc6+9ftgYwLe3XhWz98b4h3rfCtID5D4V0jQ"
				+ "NI8MQjHYfX08Z0kRqS6PYODZBFvVDq2sNDZbxI/JiLcEFRGFUlUGg1PM04JdYSdaBQ9a1h6GFMcQNrb/ACbW+IWGQO+BcT2yBjJY"
				+ "CdOmZ4tDfjnXT0BwmBnUkw9+Vgv3kZZLyebk+gS3Q4fSONDaORDd0Nngj3esc0MhL93BDJ+qeMbRIzagM0PXwE/C7DDhobYNwzpS"
				+ "qT/cvSUIGgZwTNEljss08MZ0ylIZ2MDgQf2lFRnonTpX5qBtNPdANt9lATbt+D7uhdJMFrBNsN4Yxy7G3A47IKAFzKxJzq2ncFOC"
				+ "/CPnRDgB7sqYOcFnASNHUKxkwLeNEcHwGBrF8SBLWgA5wFg2ojPZ3DiDWB7EKejs8Ie8Qw6XWz6h/2tkB7KAoEffBgNEBaCPcBwp"
				+ "Bm2SP4/Evj5NgnWqFAOHDGGqR/igeDMRZkHdJhYX0M8+OQHYbC+hk6b0wAyTJQu/Zt0YNMN+M4lhs0OWe6wZI8jK1TaF/dKNl89w"
				+ "BYCn3E6iNOlf10ARhJ4u1sXfEvHsH98uoKtXLAlDDbuw7Yy6JDQMckjy7CTAUYrWETHmhGOz/owCdaT4IaFfrjjFGjsiY79pNB5y"
				+ "UMfHiDB9sp4wAHnF6DjQ6f1a99U7CZ1dATYPRSCQzOw4I6dRLG9MoPDJpBH7OOFvKBMmNqhk8V6FEaBDDo7TDGxyR9Gg7hP2CIHC"
				+ "/o4VQcdH75NRDoQ7PYgQQf7GRK8WY8jzXCOIjrMc0n43gFbeXRdN+ttA9h0A75ziWEdjQAq0SQ63W7eXHEuYcfFpnMJTUg33Z9JN"
				+ "/kxCToUNHI8fCaBGw4MNYWVgn3csfEdm3FUFsJiXylsIyz9YqHfFi8efCyUsxkHnsIvFtClP5xyg5Edfu2T9ixfJEE4XTDC+RHJA"
				+ "BJTOCnoKBGGD3CFYJSIERGfuajLchJ0vLo9tl5GXKhvmTbyjzz9WNjVXKgtrvbmLZbnEiaVTNIMi+58ZQHmCpW2OfZaBPtI0iiKY"
				+ "guvOrCXeZMCMB3DQ6QLOgmG/SMu/KqIb+6wXxQLRiFYi9HjxkiED0FlwWgHYMdQaQ9hWMeDjI4TG+cB2GPUhCklOh7Tt35SxxQNn"
				+ "QsEIyyM6N5Igg6W7xf8Y4tkuMkyYQQJeI2J48X2ybZ94206gykitqVhkH90WAD+TWGSUGq4EA4eGY10LDO9+qZZFt0ZaZa6oZJ9Z"
				+ "1Pl2+KQelIQP8KZhNFHVhC51xP7xwgBHwVjS2LsKgrByTU8bTLFLe0g2BMd4MRo3U0H61R4JeFsEv6FDb/w4fp9EkaGlTrWiLBWB"
				+ "sGhGDgW7CoSTP34CHroD5J8noTLBMEokdHriNPgewukH5s9iLJntyTI8LY4E8JJRyYvHSM9NjpZ77AkXJGmyjVUst++Sq38pOGkP"
				+ "1uDlvZRjR7rWtg3HQc3YJEd0zuMdrCfFIPwehxsB8HmfQC/DJr8AplnrPfgF8bTfVMwvcKUkM8MjMJ0j7CgDlAGgPjQGWIhHeVhw"
				+ "SsRDOIxxSXtkuiSJH6iMIUpJR6HRtZ/JeQHDo1FfwAND6PupRfSQ1Kdr1G6zcyY/DDQUT4s0GMdR/rDwy4Xy3V0u+fCK6ZpDMfDJ"
				+ "zvDzOHwaxwW3zGSwxmAmNphdCX9sC7tgMkdi/2ATwNBmtDxqx37AfIcRWkP2Mx2Jne+SnuJ7l8XYNOBzU8Z9AouLWx65sj6r4T8V"
				+ "40rUf8rp1WuDGKEPSCcSQdSB2w2uUs3XRiTG4SBjjzgFzVsHYy33/FWOn6twyI5OhGgh5VmFhxAihN0sA6G/cOxXnYSCQ4uxftPD"
				+ "PwC7JuOnUHfRoJfE/FKBU7IAewHcPwSvCOG0RkOucDJOFhAx0ukKAteLQCYdqKzfAcJzhjEr4SYOuJXP4keN5tl3eCHB3R0SAe//"
				+ "nHnCD8mpD3HwQL4ymkA6Gzm8OwG2I6vIIluQsZr0zNHM04JGZiL7Yq2l7HWOzyxY1xjgz/oujkOU1zAFhb2+EkeHQDev8KD/h0Sv"
				+ "FqAw1QB/LAAeWXB2hXerULnhG/90AHh10rs9HkdCZA3Bjqmhfi1Ea8R4FRmvDOl+2Gkjs9xMCKE4Nc7/IqHlzXxaQ7KAJAm3HEKD"
				+ "n6AQD4Gk+C1A0bGCdiMq3TDr6IwIx3EjyPIdD+MtDe5M7o/k5nR3ZgkOqEZi+G6BFLPHJF3IWPEltXrWDRN5bzwYYk8NacSoGEhT"
				+ "7YGhlEHpkT88Eow/UOnghcg5YuWCINRFjoa/AqIK747xCiGfz3DqAm/5mGaxacn6+CXOayDoQPD6Aqjt9Ek6CzQuTBcBpz/h7MB8"
				+ "esd/EeVDXnBCAf5wqsDEEz7kBe8OvEKCYcH+CEAozzcC4wA8coEwPbJ0FFGgJEl1uDYXdY3x4cOEethCIMOGS/aorNFnvABNMoLO"
				+ "N9IAx0wOk2JLJteTlO6QOqJcafmFJP6BjYQsqEAU8MpakRex2LqsHLcQVCHdQU+mLXdo6QN0JZe0vD1hp5vfDyMqSemh/J1Cwb+A"
				+ "cJIHcTdD5t7Er0cksRTjXR74TqsYpphShjVkIrd5MnPAaawaAjcQFkHNh3YdInJD67V0JkoXZol8p5gS5ZbSDDaw+GpJuCfw0gdS"
				+ "N2EzW8SvRySxBOXbmXyUlwLtvqS2OwzQbP8SghYtzck34W9GetdxlEJHVcWoOtMpXVc43TAZmknwQI4DjnFS6CYrjHsX4aN03Ffb"
				+ "LBfE9ItiZ4WDotrkviT+E9O8V2RJtv9irqPDU/WR1ioPG4oCSoSXkJvQSi9wQkPiXXGpLPfeheJvCdY45lDgjfjgX6vZXi+8n0E+"
				+ "j3VkfHJdG3IeGx6WjisKQ69vEDXTX4cJZL11xr4KhuLbPj2hyAIIcOxbgsPnc3SXsYh0e2j4mWS6tKsYwsn0eMw3QcAP2zGVS+Tj"
				+ "vQT5xdIPzb/SeKpFHp+kqRdXv5sNdSkZH1KyFcpQOo9JHutQW+0DHQ22wKb7G35KkcHbNYFmHQpjMkuCexfhjXpuB/SvlxkPEl0E"
				+ "3HhcLXpjNTLw28xlYuu0cn6CEvWtOwsTB0H2ZqtS8DWeE0tD4k2gqQB/lFWDit1YNPLRcYDne+3bh+Fza+um+I2YarzlMQl0Tw0w"
				+ "xoWX/mhYaQeNqpeVrKxsY5rnA50XfqTVyDdQZTOZpsOdLMNPUwlsd3rWlKNdDlOXG1ltOmVoNLxNRRZ77AYPIyoaNsDGjaCXlayc"
				+ "XB4ttN1xuZHwv5lOD0MXmbEx7942RGwX7hF6RxewvZA6gA7H2AzPKTHSHepm4hyjwubBlueUFbstooPsGFv8xen42rzU09E5Uuv9"
				+ "8yR9Q5Lb4CoUK5UqRswtgtTWNalAJNuEsBXwDq2IcZ3enjXCej+k+hMlB+8+Y3dNeWJOOwOpG5CupvuN8B2MXJLmFLAt4fYkRRv2"
				+ "8s08dY/dgvFLqKwt+VX2pt0PazUuVy4mnQdaW/zI7GlK3WJzT5JWg1N1hfdUbFSopGL7vaqly6s42rSQRI9K8h7LPWlJD8N1JLB3"
				+ "ux4SRWf4Eiwyd4NJNiATye+zpPB8eBq0nWkvc0PA3duCzZdovthpJ5ZmmXRHVcWRuohos7N1a/HB2xx6n5surwCqQPpx6SDtLpEb"
				+ "gZYaWxpVhJsaPhxEhw4kRZb/mqRb8ZWR6GOS1F2Yvxnm2ZYdEdF4mrugiRFPozeOZ5KCNCvQOpA+jHp2D74epLfkuDDY2zih22Gc"
				+ "QYf+wHQ30ICf9gpASMS7OQgj/di0C5wgAV2X8B3gtglAbsd8PSUwd7qSAvxQXCgxS9IsG87wFQQJ1hjQz6kg4MfIJi+oV5mk2B3B"
				+ "kx9V5AgDpQBu6diixyAKR827Hu7bwr2kud48GE0yoURHHYileCEnCtIsNsETpr+AwniwUfcDMLiHmB7HHAGCQ7BQD5wn3ga24edB"
				+ "LIoq7G5yfqUEKC2oUNkzfduBUXvYVnbIsclBfAV6O4mqRTYIwq7NGC3A+wjhU9ksAEfpmB4AJk3kWC7GaxZYecG+MeWxthmRQcn1"
				+ "WDbGOzqgLfYcQAC1o+weynebAcw49McLNbjxB485DjNBvHycfNYF8NaHDoW2GHPeHzIy+clYjsc7IqK03qwHzs6FuxAgf24sKUMQ"
				+ "Dh8VA2/AFs+Iw4Ib82M7xixzxWDfa/QcePjdeQH8e4m+RQJOmDsFMFg80Es2qNjw15e2M0C9xGfG6HTwu6rtnbTuw05HCWCxqQ3K"
				+ "Dbrjc4Xr0OcmjMv8tQcqZcLxyXTwBVH0aNjwyEP7CYF2HT8soiwV5OwPfZ7x3d/ePDZDoItdOAXHQvM6GSwLgT/3CFAMDLB9i0YD"
				+ "clwvJ0x+wO6jj2osJsp28cJjhrDVBU7QbAdtrBBeuhwgfSPwzR+GOoAnTD8YlTGdrhiNAp7TCE5LPaTR3kxYsPurOwfI0NT+Woq1"
				+ "A5Xh+3RnZpDZH1KyHAlogEyMRUrvXYjw7BergC+AqkD3cxIe4wKsIMmBB0LRhOAD5UA6JAwEsLmfhI+GYbBQasY1eDwVLl9Bc70Q"
				+ "4eH/aMAzAAn3WDaxkSVBfCNxRUCPyNIOP8QjIrQNrEHlqkibPcEwA1TOeQV01UJRm0oE0Z1gOPGfcFoTO4thjwA5ENPTy8DkPlMo"
				+ "qekjKAZohk6LDQ21DZENjy2s2B8JjiMTYDUgXTXpVyQSezKie1/+URjiL7hHOoZWwzDLQ7eAx6b8WErYpZvkWAdij90xvQS0y5MH"
				+ "9F5/YkE61E46cZ480LYDVd0LDg9B5v2yfxjJMRExQVM7igDNh3kDpf94D6hI+NXOGxxS3uTH7bDVepMEj0lZQTNEM3QYaFjSNaAi"
				+ "tawutFbStKWY+qUEFaGZ3fpz5gJQreHGQ88pjdYe8HmbnzOH3YMlcAvRM+7KS22w4gMnQ8L1oywq+gyEoBpGNbPsBCPKRg6g4+QY"
				+ "PqHtR8TMj3oS0gwosJLn5x3vLaABf6k6HHqZhNsb/Or60n8SdL6dySkWUZYfOUGY2445m8JpV8Zl0mAyZ6F0e10NxO6Pcy8EI3p2"
				+ "+MkfM4fn37DoAyY7sjTZoApLWydDLAnPEZZLFhkx5mHGKEgPoTFCAaL2PiVDr+0IX50aljg50Mr9PvHZujwj3xjMR87ayLvT5OgM"
				+ "2RkeAZ2JnsGJ/ngV0Ze/Ge/GGVimgx3E1HxSnvWZXn0sFIHujkFZQTNGM3QYUn4AcWV9XoFHQPAnlM2+BxB7rgAFtxNL2linQb7v"
				+ "eOXPwajKPxCJoE/nID8fhIsepuQ904+TXgnClM8wMeCwS/sh5FgrUuGRf4xfePFffxa+G+hMOwfcQBM52DH9jI+tsd+9uiY+FUI9"
				+ "oMfMNDm0ckCU1gWRrczufPVpvOV9SgMfpIEaw6aZUrID5V8uGL+bPnOuh+YKy2Ar4Dt8VM8RkqXkOCABIw8pJxIgkNLMVrA1OpmE"
				+ "oTBKwtYw8KJyQziw1oXOgR0SJhCYs0JDzbMEoxucNIy3qFCXFioxisOPyfBm+bvJAEYQeE9LRxLD3ccXY/pIN59QvryMFW8x4XRD"
				+ "UZReP0Bry0ArIPtR4J1MeQfh0KgvN8g0UFe8cvhf5OgnHjfC8h7x+C9NOQBv2j+LwnW3/AeFn4JRJni3ro31QdTKd2GwU+SYM0B/"
				+ "rJlFfmXja/6n6oic27qiSNpWvifoenuwtO3o5FLOI5yBNh0wGaMKNCx4Fc9TJtwogwE7whhhIAHH26/IUFHhBEF3DBtQweCERp+s"
				+ "scDivjwntO9JFg4xy998Is1J6SBjgDTMj6B5nYSxI93kDBtg3+cKPMACV4OxfQS7zLhxU/8wofOCGaExwup6JCwkM5gcZ6Pv8eUE"
				+ "x0U3tnCS6JrSRA/8ou1K6zJobyIC50qfsVEOHTMCIdfRPELHjo/5AVg6oc8I06AtNAp4ddSPv8Qdnj1AfHzlBM9AZ4BvLuGuGFGW"
				+ "gB/zJE33BfOO5NU555G6kD6iyQ39SRqjznU2UZqj3zUWhSyDJkjswUjuJFwGeMqMufNXThVeS3y1By8a8TxANnokiDTNhGVn3qFy"
				+ "yLviyynbq/r0i/QwwLWpV1fUmo+ys6/507NKSLrU0Ju9EDqQK9QMhvrWFrGNT7pzulBbOE4bpmGTU9LkjhLiR9l4fJIHZjsdZ2R9"
				+ "sCkSztJKWVIW9ZS7g3DYZH/cuIRVCiaBqcZ1rBko9EfCq0V2J6PbuAfntgj6yY7YNJ1AXwFNj0tSeIsJ34T8n6adFxL1ZNg8wt7L"
				+ "qsepymM7l/CZlylzkCXYW3xmNDjEVS6qhqTZuiwJGgE3BAMDajIaoZ32vnymzMgW43egmRgQ9xNge3+sI5rqbpE2tl0ie4nLkwS/"
				+ "9Le5A5suo0i/97chXgnDeuDjpAsd1iy0+CGgKtJDykynqFaB6zyOhZ/wDv6vXyfEKdNgEmPE8BXUG09jrg49Lji/EcRFVcU8Md+o"
				+ "8JExR8Xjt31MNJed2N0XZpj8eYuGObNW7yMuiz8yDK6hCgySzP8SghQ21rn1NsuN3rqVtV/yFbSXk9GvEc0ROVyb1MDhr0xN+XER"
				+ "wvP3I6f3RGmUgKkDnSd86nrTFo9jrg49Lji/POTBnOUjqvUgU0HJj0urCmMDZtfPRzMiB+wG19lura8deMd/+GW3MwzzlG5ll+Rc"
				+ "we1vfD5zK2iEPOp/eF1lqam103LEHrZuFGZKPLrzb1ojPL64V2kD5Fwp47w/6UK+cX5FUvWhGZTA0yrO4ppvnvTf4jyTj73FCo2v"
				+ "svEy7zMZpLPqp2vXp+/7Xr9I/U4cB8zR5Ybhq2jMGG8D17HosPprxwaEfZGIuCtsIOuy1S+c1l+5VX8NroNP0CgFumMzFc19VKpR"
				+ "ByNSk3K7s1deIDyWpZQcu8MkkOy/jt431J7916e/+NVcgeJNPgRZY2sN8buFkBE6VZyB52ucvu9/p+o48L3cnyCDaBRVuHiwvrVP"
				+ "ys88MtaNQ6kU+k6k3FWI35girecdJOEtflJklbS+IHNzZaG7+addsFg1a/9YmpXeNevvwiyUhUK8/MrrsRLv+XA+csUtpuaBWTZu"
				+ "DXIqyT2Pninnd9ftfanxpXDlro4uYW5kxrYBdTA9E9culughs2eSROu1LjqAZm3Sul1T+7Is73cqCn/Sh0VtpGWR6s9RbKg8OCv/"
				+ "7ew7nGUqVwqEUfd0TAVXQJJG7q0i6PgzVuMRoZ9n/6VJPz1MJcnpx+pfP5T+ZVL9b2o4tDzUCm9EtR7fNWk4nn15l18PEX7FYoWW"
				+ "z4TSEK9Rpcvqq49X83/8eo9vnU0SfPlR541GqXxlAqXT1Yy61yhJd0Dr2Px0eH6FvaEYrZStFeqPTuuyf/5q9jxoNIkbaylYrpP1"
				+ "SRtGib/1chnkjgTp+vNvWiy8vrho/B3UzAK4wfD95vfU/muS+mPHDYbrDTIX+aodEXXE7JspTRq+OdKl3q3nXfMB3Jq6Ph/oY4LJ"
				+ "yfjcATmWfK1sPDM7b8sPI2NCorSt+lRsL8k8STR64FS8g9gtvnRSeqvKninXzBQ9euPU34WkAwSWbhVFfLz8yuW3A9DheFEcM0cN"
				+ "a3AGiPLFtdYZQXbdBN+vPQXdCD9BUXDhMg9pG4lLxfkl1+JXQ5kPBwv58mUXj3puDoSkjvkzbnc+Fnvoj9k2PaH/pDx7fS3C1pYe"
				+ "O7uXxSexEYUVaU70SyR9YbI5eOHTj58XKFp7oGMBxTp3tyFNPRvwWhLngkYDP1V4dPUcWHoL8Mw7Jfjl0i7aukA5iid/deavkw7N"
				+ "eFSAU4rkmc4YqucK9Xe3Vfn/3g1b7pYbbj+MkXDNIQSsJWNHwD5QCbF1giK4qNGe3y4vhUurvpgz/Mv0FTgazQVwOJq0vQ5vyCNj"
				+ "isw+ak0UXkBcW7l6DpwY3ubHkcavz5ex6LxFORLVO/ix5hCnux+rPJdl+RXLsXeWqVgy0tcOXHNHKkqpcGQZTNVuskuCXqDkDrwz"
				+ "d7J53qq/1BsM4xfFOUWxqtVoXBR4Zk7fld4+raouOpJx9VhwDv1/P6qzX/dZTEZxcfyhbvozl2Qv/v796gt+slqVYXri+swU2S5I"
				+ "cqyyQeQqcmD6J1+4WDVrw3vboUvCHazgrIwn6aJeEGQ8yEbm24H+kp3aMS+ULz2kZ8VHrkJ97Cv6Mu0q0aWG6SpbFyJcJN6GvRwM"
				+ "Efpvn+aMkyhySIa9ztCe4BPMG6gKcPlNGWQWwpL4uIHRWkRJntbOGBziwsrdZDEnylMlB4XFki3OKLiTBRH8MmWdzUFOVUE2UEj5"
				+ "6tUoWtpfuUybKmcFlv6pdrjmjlMBc4KsmxcebIiWU97D6LCSLfe+tBxyjv2g2jkWJSVH7niINLPqt3brs/f+rW4j1w538Ck29MPi"
				+ "PIP2B7ofpoab87CMarFCz+Kx04K/m2i/3I/Dz+Kx2Eh9QLXYabIckOUZdMfQFDKwyj9l6x7p5znqfaBHyYjGj+fQgxWkbf5OPyCJ"
				+ "LQqPR2iUnpT4516XptqG4jDIHACNo4rY+6l24TXVnB6Ub3A9YZr5shygyz1wbP5j2oAsoEk0X28jsXDyZYeAv+kHpxQw9xMf7Evp"
				+ "L/YOPHG0RvcR1MdVZTchNkqN+uNb1a5HE67Pkgk+RJN/z6lXnvxh/l7fsTH4duoSV4NFLW1rNAXN7JWyLLplQc3tkt7D2Q42RjTN"
				+ "JCi9KnjOpAeiqtIf3Ng5YNXH65T+a7P51cuxbFWNvQ8VFqXwB7obuxfutviiEIPr2NKA+jpRekg1j/VycFkg6n7PN82AO9QXUOd1"
				+ "RX0x2Qr6VHxAWmv2wFTuErpmYQLmFVMlVlvBHkL1rc6SMVDMst3CdhAXj6jdmz+dv72G7BIb2ug1dSbBm/OglGqpd/lVPSPkVEed"
				+ "f9rGvUupI6KT7auNlH3P0mdQc8cWW6Q1SqbqSEgLbaXehy98uid+sl+qm0APSw5emjUqMDWBwefzs/f+e0/qm3+nm6ycUaR1B+Qf"
				+ "tOEqxa2PJSTN2MZvVPO66faB36cjJ8h65GBNZz9E7Tx+kmp39KUk9dy8DOfNfriRtYKWTZjIy0RW1zcQPS4belFxZPz5iwcqVpa6"
				+ "OFR/06Ck51DCjjp+SJ6gHh/77Tx20jiH/YgLi4bMryeHkgaL4fV4wNRccg0GWwZ9Aay/jLpBwsvOGn6MrV13Y35u76LkS3gsDIeP"
				+ "U6bm64DmJP4l7B9VLjMYrohWcFWNltF9xWRefA6Fh1M3RcepjMCG5/dqlC4VhW6vphfuQxrKfWO7Z6n1SsK3duDVA4dVe4skcwe0"
				+ "r8erB0uw+dUaUmSX5MfW5lZxxWk1TMFCpZVuGyy4ipR3ko3CplPU/4Kuakn5XJTT6CHSl1FXqYH1j4vU8f1afXa2u/n7/khPrI2x"
				+ "WXTmTR+M4E3Z8Fw1dJ6KannkshfZ29ShfyC/IolOB6+2lT7/iL+zJHJBhliKxs3FK7QNPfA1sikvUmXabGeFA6T806f36r6tX+Cd"
				+ "Dxs8oDNv5NckF9+hb/5VhXozoNvMutcLravO7xjP9iiho47h9TPUTb3EVl+jPT5+Tu/szzl+qAJ070B5cRZCly4TFG3jasCVLNsa"
				+ "RsfNx6E0RtS6nx6cxfso7xWeugUHr7wjetcgUZb/6NUflF+xdJ/wJ8jZOAI5Z34sdPoHn2F7tWh4pZvIvPlauuGG/J33Zj2GK2+Q"
				+ "LY7m87o7SwTpH5YGghZtrjKTYMtrqS6hO3jMMbnzVuMhw+vQZwOcwi2Zv6y6upckr/FP4ZMhm06vLmLpirP/4bz7YGNz166Ld8Mv"
				+ "uFchs+i+oJq14ve1jJBlhtyLcumNz42c6NJqgNbWN0dFHJHnJ3L7TOFHkZ/14CpgbXPC+R8idr56k/yt30Tb2PLONPC6TUM3mnzh"
				+ "6jWtkso658ko9wlY7kKtiemaWCmKbWu65qGa4gpqEbZuLOQjYHNnF6ahlKxPHqnfKK/ah9MD2eOHlK5L5P6Kz2gF9ADendozgryn"
				+ "nfjHfshTw0d8wFy+iJ5GSe8PElT5gWFR//vpsLah0OrTJOmHTYMFXtg6hDZgUgdwCz1pBgfEoHeSKLyAJKmrYe36l7HwnEq14KHF"
				+ "Q9tuPMluRUKP6HrxfkVV6Y9hqxhoCnyiVRm7PR6VGDj8yoV/wtq15av5//yjSTHaGUF2c4yQ9IHphGxlY0fcq7QNPdA7yB09HhNf"
				+ "nRs6cu0gJ62LS1f9zoWv0752zQX8BAHLsrfW3yJynddnV+5FHs2RcUBdHNdQmXdl3K4hLJ5NmWZ8upnt4v0G6msl+VXLsNLoM0G1"
				+ "12mqOuGWCbVKpvtAS9Hrwq5mWfmcpMOO5s6LhyMsV9g6/MPGnEtounR/9D0iPPRcHinnz9I9RuwkNQLSeRpRX+i8uG4d3xW06w0b"
				+ "L1GUbWHpQ6QZUPlsZn1UjsMGa7cRpE27ZLwTjt/gGodsIByu1DlCoN6BiHqNnqwccz+fb6pQcgdfKZHHfG7ScPhpJMCW59nqDwLC"
				+ "8/c8avwPMh6x9QuK0W5bbMuqckD00ckLVupDSVJOG408GfTS4HTlnmI1WnqNIk0eshz7wnsfCf8gvh9Vej6dH7FUj4tQYavK7yOR"
				+ "ceonIep7rGhFcDnSVeozp3X5P90ba2O0ap3UIeZoy4bZYUotWwIZ6tsfpDZndOQD7jJj03vE6jjOjZY31LHBDY+W0i+pHZvvzZ/6"
				+ "1d3B1b1g9excKLKteAEovfC6Fsqhc72h3S5JL98SZqjaWR9ZRVuZ5kiy5Umy1bNBspxy47IpAM2VysvcXSn7R33oZwaMuZ9ZEQnM"
				+ "BF2ofPTdL2o8PQdv6mHaZV36icHqLaB8ylPiyhvg0NrcEf4usa9obkRkW3BppcK4sgcffXg1IJqlM3UCGQjAzCnaSwm/zJOXTelk"
				+ "1bvxpuzYLBqaV1MTtQp5AYEtvCWuwV2+eVXYh8uhK0p4Qff7yQVx73vL7LwvCoUFhdeuO/nhVXLe5XH0U0m703NG2INsZXNfxoDt"
				+ "UhPCjcEhLPpwJYO+2PYvk+hKdf+NOVC54BOgvOET1i+o7q6Lsvfssz/KrgW0JT1iHDKenJg44PPjJapPTuuyv/5Wv0YLXl/GwVbn"
				+ "m3tJi16O8sEjVbJaahm2UppDMgPh2O9L++/TD/I19BxOe+YD54UdhZHCi+bSf+82rnluvxt36jaR8Jex6KxKud9gdQPUnotYdqUi"
				+ "cLPVD5/cX7l0jWwyBB6HZj0UkEcmaPcm1LPVLtsUY2K3bjRJNElaf1L0vrvhXfqeS2qbRA6jS+ScWxPNLkn6Hph4d6f3lzYVLkj+"
				+ "LyTz21X/YecR/F/iuIfGtj6ad5DyZ6fv+26v6pdjbBPYV2Rut4bAbSKrGIrm//khVeQ5h4kbQQcvylumX6atGuOd/r8oapfG3UiO"
				+ "epMVHtg6/N7FRxDtio0l0Ru7Ixc7tC3vYVGdDhGa1pg6/OiKhQ+VVi36seFh34bd4yWw0zSttpQ1PUDUyallo07EyB1E2kbBcdXD"
				+ "/fdVEZd96Gp2jSaqqFTeWtg40NTw8L1au+ez+X/eHXqLVq8uYtmKw/Hvas5gQ0oYGucr6jOPVfm/3Q1PiNqJirdLrgeM0U9PDjVw"
				+ "lQ22ShKaSAchhtDVHjpJ06vd3JqwDDlnfRxdC7UyeRmB9bIfu4Vun5G7XztW/nbrufDGqxQRzVaebnPkvoRkn7hbaCIcr+kURuO0"
				+ "XoO/kL8BAK1SG8U+jL/SC9zNFoDSINeNm4wUQ3H5ibtuSFwXEDXgS0uJs69LvFe//5+avgE6mz8Tmd0YOvzCBVpfv7Wr69Uu3sPj"
				+ "rzjzmlTQ0bjGK3LyDgisPW5P3yf6i+huVLY6qdZyGR5G+6BSYFetnI7CNnoS2kMMjzrpvyUm8+kyLwAmW5sHrw5C0aoln7U+eT+g"
				+ "4ziGDL1O+qALqIOaLVvCrYnPpP84eSfGb5dwDpK5lK1Y/N387ffkLV1qlrVYRRcv5mir29qNalm2ZI0yKgGg7CN1KCsZfU6Fs9Q/"
				+ "lFZBXRKoW0B+059lWZ6vyC3z5A9uXWDz36+pro6v5i/5apSjtFyJMN1WA2GrWyys0nS8ehwGG4QJj1JnKWkXSoyj1WBOq4zg46ra"
				+ "BSl8zuVzy/Ir1zyVGiuFVUvfx2SyfLW6oHpC2xlkx1FuZ1G2kaRJE+1Qk8zbR6kf1/3jv9wqxq8T3jce9E61SM02pqfv+OGlTQFD"
				+ "K16gTiAngebfaXoVY5ALcJmH4ceN6hWOXQ4vUxRq5vXF9Rb2UyNnu30hh2l48okDQN0PQ0cTgI7YzzenItGq5aWz5KXd1BH9Xm1f"
				+ "eO38nd+J/YXxCbAes+qQK3ScTgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwO"
				+ "BwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4"
				+ "XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh8PhcDgcDofD4XA4HA6Hw+FwOBwOh"
				+ "8PhcDgcDofD4XA4HBlCqf8P28KrZRw/Y0QAAAAASUVORK5CYII=";
	}

}
