package io.openems.edge.app.evcs;

import java.util.EnumMap;

import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

import com.google.common.collect.Lists;
import com.google.gson.JsonElement;
import com.google.gson.JsonPrimitive;

import io.openems.common.exceptions.OpenemsError.OpenemsNamedException;
import io.openems.common.function.ThrowingTriFunction;
import io.openems.common.session.Language;
import io.openems.common.utils.EnumUtils;
import io.openems.common.utils.JsonUtils;
import io.openems.edge.app.evcs.IesKeywattEvcs.Property;
import io.openems.edge.common.component.ComponentManager;
import io.openems.edge.core.appmanager.AbstractOpenemsApp;
import io.openems.edge.core.appmanager.AppAssistant;
import io.openems.edge.core.appmanager.AppConfiguration;
import io.openems.edge.core.appmanager.AppDescriptor;
import io.openems.edge.core.appmanager.ComponentUtil;
import io.openems.edge.core.appmanager.ConfigurationTarget;
import io.openems.edge.core.appmanager.DefaultEnum;
import io.openems.edge.core.appmanager.JsonFormlyUtil;
import io.openems.edge.core.appmanager.JsonFormlyUtil.InputBuilder.Type;
import io.openems.edge.core.appmanager.OpenemsApp;
import io.openems.edge.core.appmanager.OpenemsAppCardinality;

/**
 * Describes a IES Keywatt evcs App.
 *
 * <pre>
  {
    "appId":"App.Evcs.IesKeywatt",
    "alias":"IES Keywatt Ladestation",
    "instanceId": UUID,
    "image": base64,
    "properties":{
      "EVCS_ID": "evcs0",
      "CTRL_EVCS_ID": "ctrlEvcs0",
      "OCCP_CHARGE_POINT_IDENTIFIER":"IES 1",
      "OCCP_CONNECTOR_IDENTIFIER": "1"
    },
    "appDescriptor": {
    	"websiteUrl": <a href=
"https://fenecon.de/fems-2-2/fems-app-ies-keywatt-ladestation-2/">https://fenecon.de/fems-2-2/fems-app-ies-keywatt-ladestation-2//</a>
    }
  }
 * </pre>
 */
@Component(name = "App.Evcs.IesKeywatt")
public class IesKeywattEvcs extends AbstractEvcsApp<Property> implements OpenemsApp {

	public static enum Property implements DefaultEnum {
		ALIAS("IES Keywatt Ladestation"), //
		EVCS_ID("evcs0"), //
		CTRL_EVCS_ID("ctrlEvcs0"), //
		OCCP_CHARGE_POINT_IDENTIFIER("IES1"), //
		OCCP_CONNECTOR_IDENTIFIER("1"), //
		;

		private final String defaultValue;

		private Property(String defaultValue) {
			this.defaultValue = defaultValue;
		}

		@Override
		public String getDefaultValue() {
			return this.defaultValue;
		}

	}

	@Activate
	public IesKeywattEvcs(@Reference ComponentManager componentManager, ComponentContext componentContext,
			@Reference ConfigurationAdmin cm, @Reference ComponentUtil componentUtil) {
		super(componentManager, componentContext, cm, componentUtil);
	}

	@Override
	protected ThrowingTriFunction<ConfigurationTarget, EnumMap<Property, JsonElement>, Language, AppConfiguration, OpenemsNamedException> appConfigurationFactory() {
		return (t, p, l) -> {
			// values the user enters
			var alias = this.getValueOrDefault(p, Property.ALIAS, this.getName(l));

			// values which are being auto generated by the appmanager
			var evcsId = this.getId(t, p, Property.EVCS_ID);
			var ctrlEvcsId = this.getId(t, p, Property.CTRL_EVCS_ID);
			var ocppId = this.getValueOrDefault(p, Property.OCCP_CHARGE_POINT_IDENTIFIER);

			var connectorId = EnumUtils.getAsInt(p, Property.OCCP_CONNECTOR_IDENTIFIER);

			var factoryId = "Evcs.Ocpp.IesKeywattSingle";
			var components = this.getComponents(evcsId, alias, factoryId, null, ctrlEvcsId);
			var evcs = AbstractOpenemsApp.getComponentWithFactoryId(components, factoryId);
			evcs.getProperties().put("ocpp.id", new JsonPrimitive(ocppId));
			evcs.getProperties().put("connectorId", new JsonPrimitive(connectorId));

			return new AppConfiguration(components, Lists.newArrayList(ctrlEvcsId, "ctrlBalancing0"));
		};
	}

	@Override
	public AppAssistant getAppAssistant(Language language) {
		var bundle = AbstractOpenemsApp.getTranslationBundle(language);
		return AppAssistant.create(this.getName(language)) //
				.fields(JsonUtils.buildJsonArray() //
						.add(JsonFormlyUtil.buildInput(Property.OCCP_CHARGE_POINT_IDENTIFIER) //
								.setLabel(bundle.getString(this.getAppId() + ".chargepoint.label")) //
								.setDescription(bundle.getString(this.getAppId() + ".chargepoint.description")) //
								.setDefaultValue(Property.OCCP_CHARGE_POINT_IDENTIFIER.getDefaultValue()) //
								.isRequired(true) //
								.build()) //
						.add(JsonFormlyUtil.buildInput(Property.OCCP_CONNECTOR_IDENTIFIER) //
								.setLabel(bundle.getString(this.getAppId() + ".connector.label")) //
								.setDescription(bundle.getString(this.getAppId() + ".connector.description")) //
								.setDefaultValue(Property.OCCP_CONNECTOR_IDENTIFIER.getDefaultValue()) //
								.isRequired(true) //
								.setInputType(Type.NUMBER) //
								.setMin(0) //
								.build()) //
						.build()) //
				.build();
	}

	@Override
	public AppDescriptor getAppDescriptor() {
		return AppDescriptor.create() //
				.setWebsiteUrl("https://fenecon.de/fems-2-2/fems-app-ies-keywatt-ladestation-2/") //
				.build();
	}

	@Override
	protected Class<Property> getPropertyClass() {
		return Property.class;
	}

	@Override
	public OpenemsAppCardinality getCardinality() {
		return OpenemsAppCardinality.MULTIPLE;
	}

	@Override
	public String getImage() {
		return "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8Y"
				+ "QUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAFCpSURBVHhe7b0HnB3Fle9/7sxoZpQjQlkgssjJ5CiNMMZhvctzWKe117vrgDEKI4NtW"
				+ "JywQUiAbf624dms1/bz867TenmsLQnbmGQwweSchBAggUA5ztz/+XXfM/fcmqoON82dvvXV50yfOnUqdVWXuvp2II/H4/F4PB6Px"
				+ "+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8H"
				+ "o/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+Pxe"
				+ "Dwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px1NjcoVtVknbvjxLXBrtU"
				+ "4meXU47r4U6hn2UtXO5yV+me352J61fFcb1p5b7CnkA5GPLW8cDmw+I07EFUXq52MoDLl2QsjNFJTuy0XF1ZlxHRyGDwJafjkuqY"
				+ "6vRNlu8IHFmfkB0Wz6mDsw47aOJyqeoz+s+jYPLWD+qYOL43E8p33MRrVj6Igwscflo4vzLTQdMHSBcSVqg4wSbrZZInTJFPXdgv"
				+ "XENJqGcAaTzculA523qQNKIXeOyDzRSL7M9oT5v8Uz+ewULn1VJfInrFtaXUM/uJXTzsm0wsOh8AMJaB+Ln8onSsQWmDuJ8KtEBw"
				+ "i69Hkh5maJeO28gsLWtmgMI6XVaHTbjBoJa1qGYd1f3cMrlLmRtAcvQwMbRo6dMonH7zKA19z9KOzbzXFVkFZ90XUjrnv4Z/fVXy"
				+ "GegabR+A9WoRyPs26rTCJ1TKwa6bWkHnXngAFvYla+ZBrh8bdjKdOm84Du3lcbv/QGerC7j0NTAxnSOGkEzjj+Kxu49PUjRu7uHX"
				+ "vnro7SGpWf37oJXwO2U751PK668pxCWMnQ9tA7MeiTVsQU2H8FMB6L8Ndrf1KPyEF+g/XUewAwDnZ+OFz2T6B2QNaTz0rbRHAi13"
				+ "kdSRjXKMusOzDxNnyRlSl4h8xafwJarOOVxBQu1DmmjqUceQnsefhC1tLYWrEV2bt5Kq++6n9Y99VzBEtDLWf87V+HztPyKlws2A"
				+ "fUy6yfh0voUfUy7xuWj8xfER5fl0jU2uy3/emCr36BnoHZmPZDBU682mmXVs+z6MHfRNGpp+To37e+5aUHb8HeP/WfRtLccSUOGd"
				+ "8ICs5PNr6yjF+64hzavfb1gCdjEeX6denuuopXLdhRscaTd32n7Q/tDB670aesiuPzKzU+DNJkj7U4YTEjbpONq3da0g8rmn9Zmb"
				+ "k2S+MEGTD8Q6nMuGEat7YtYX8yh4ZQL3UZN2oNmnHgMDZ84Hr6MJBMtF2QQBFSp+Xye1vOZ1io+49q5ZWvBGhT1LP9ZTFvf/CXdd"
				+ "n1gZSR1MfMQ06ZK6Gc30wLtD2w+Glf+UUgaV/li135iN8vTYRNbPpkkaicMdqTjhTRtjRogOk50Kce0AzMOiA3Y0lSDyvM74Mwcz"
				+ "Tj6PXwadTmHZkiWHSOGBdepxu0zk4PlF9Gzaxe9fP8j9PIDj/HJVU/BGvBHLms+LV/yQCEs6P0GULjYtC6YNpc/dAE2W15xuNJI3"
				+ "ma5tjKB9hNM/yRIPpki7U4YTKBt0tHldHjzMmoS0XEfOpono6s4dHJoJGpta6UpRxxMk46YTS1tbQVr5ezYtJle/PP99PozLxQsA"
				+ "ZjBvs8z2cW0cuk61s0+jOrbpDYXadOnyduFzkP0tPmaeWSOSndyIzPY2iYDTAYqKEcHCIvdtNkoxs1dNIlaWr7G2kdYWgIbM2Hfv"
				+ "Wj68bhONSw8qcrzn8LSMLw3FF5hFljyiR6egBXDWguShZkF1k1rXqUX7riXtqx7XRKCDez4Fdq97dv0h2/vLNjSUiw2GfAXXOl0n"
				+ "tof2NKIT5p6VIJZp0xQr503ENSqbeZA1TpA2KZrxG5ukwJ/YKaJKg+4/edc0Emt7RewdhHLqMDGjJg4nmaeeAyNmLRHwVItUKxUq"
				+ "wgmu9cef4ZW3/1X2rlte8Ea8CTle7vp3v+4kdavsrWxWkTtw2rYgY4zdRPEid2VxqbLNlPYdlBWqEXbMAh0vma4HKqRRxLs5exzE"
				+ "tGsE9/NZzRLODQrNBK1DxtK0487ksbvv3dwFmRLnKTi5TauZ+dOWnPvw/TKw4/zqrC3YAX55dSbX0grr3ykYBjMyK7BbgJm2AZ8t"
				+ "L/LNyqPQUs5Y2mwENc2dGil7U+bR5S/DDAzPq0dJKtXV/fhPBstY/czxB33UE0+/CCacuTB1DJkCFt46RbEhL/4Bcs9VhAKY8TOW"
				+ "pCF+PfFBJqAWEkbWksnQ4kPdI7YsXETvXjnvbT++dVBbOCZp928+S717r6UVi5bHzh7TKQbMkVxJGWPWrZNjjF9rJnYfGy63pq47"
				+ "CAqLpp53RM5+ZdZ+zhn0RpmRTR+1gyafvxR1DFqOIdCW3lIk6rHxtUvB9e3tq5/s2AJ4Mkqfyltfu17dMcNuwo2T0h5Y6PBqe6oa"
				+ "iyq1Tbz6JOBAJvWk6IHUj33f57O+EwHDen8NBd7MYfHhGai4RPGBtepRk7Zs2BJgLlX6kC+t5fWPfY0rf7LA7Rru76/NP8o/1nIk"
				+ "9bvePIKTYMHcxzp8SG4fFz+wGUf1KDBWWUg24bB4irfjJOwtkfpQPyBxGl0GqI9DyA6/J3nsGkpR+0vUUOGdtL0txxOEw7cN7hOJ"
				+ "ZQmNiiu/WIcFS4/0x6ELc6GffeOHbTmnofolUeepDyubxXdb+RZbRGtuPLJQriZwQ7LHLZhlBVq1TZ9REXpAOE4u95Wn3ndB/Nfn"
				+ "qhyZ4WTDVFLSytNOvRAmnL0IdTajutUuno2vTHZ/sYGWnXnvfTGqjUFS8BObue3qXf3V+nmq0rWj01GbcbTANPYI7Iy6t021xFu2"
				+ "iVc2xlhzvzx1Np2CRfxCQ5hVgoYt9c0mn7CUdQ5uu/OhVToSrv0KJKlsceItTSPPG3kCQvXt7a9ubFgDVjLcgm9ufr7dPf/KbmNv"
				+ "knAbsoc9vGSDcyxbVI67u1IHoKZV1T+NiQvnUby0Hlpvyi9v/8Zn22lIR2YpC5lkYf8aNi40cF1qlHTJrFz+DtdaXKbXiSw9kWFv"
				+ "wTacgn/MDCyrlaaJVEBhcRi11rfL4XQ+Q/uU0Uox0qog+IvjtSTp1cfeYJeuvchXjKW3F/6AC8TF9Bt1/+Btm0omAaUoEmhWlOKO"
				+ "zND1GPHDRS1apsMBDN/PRC1T5xdb4HWXdj953XP4+AyDh0czi58atXZSdOOOYz2mL0frwVxeBeLxC0K4YQS/GGKWUpcOCXUgrAO1"
				+ "Wb3tu300j0P0quPPhW0QfFLyvcsphVL8YB1M1DS+KxQm7HYGPQ/Ct1oH5feuMxduD+1tF7J2ttDA1e4pYUmHbw/TTn6UGrr7ChYq"
				+ "wj2TBX2SkXZRCTe9vqb9MKd99CG1a8ULAHbeRa7mieur9PKZVg/1rpfbTV01bpKe7QP5Jc5at1hAw3aJx0numkD5mDRftpeL3QdN"
				+ "aX2uQtGU0sbblE4j6U9sDFjpk+hGSceTUPHji5pgNkYCZv2+tG/5FKLDtlqGV1znGG9+fxqWnXnfbR94yZYWAJ/vCzwC7Rj8w/pl"
				+ "v9P30YP4ABHwQwL5dp1PHSQxu7SgfgDicsU0rgsY2tjuR3bGPvrxI+10ogJH2PtKywTAxszdMwomnnC0TR6xhSuqW5enG5H33XeC"
				+ "JTWOL5dUv98Tw+98tDjwaM+u3eV3F96L89qF9BdP7qdNvadicVnXNSxBWl0bMslTXopN1NUsvMaHWmbHjBAd3rUAEgzOOpDxwiiU"
				+ "z95Ok9G+IzWEaGRqK2jnabx0m/iIQcES8Hq0Xi7IKDMau3auo1W3/0ArXviGX19C8rPqLf3Qlp5pfPjiYwudaB2jKtcmx22zDEQO"
				+ "72eoH3ScdJW6Vxtd9mAmW5g6Fq0N89GeED53SxBPXCz58SD9qVpxx5ObUPxeuL+6Eq7GpCmYdXaCcgHlJuX1KO4LZ4N6jhglrF13"
				+ "frgNc0bX8adD33g1adXUu/uK2jlspLP/DjQRWji7GbV0uiaKDuwxQ16pHFZRDp0cLdxzgUjqbX9Qm7KfG5K36w0euokmonrVOPHF"
				+ "iy1x7UzK9nJOq1Nd8UDMywkmbxwhvXGs6to1Z/vox2bSuan1Rx7Ib2x+qf0l5+a17eqga3KSXHtDpsuTc4Uley8Rkd3IJBONDt2o"
				+ "JF6lXLw21po6sEf5mi8TG9yaMRntEbSjBPwGa1pHKp29Wu0SxplT1sIPkP2AD5D9gj17Cr5DNmdPKvNpxVL7i6EGwHX+LXp2GaOB"
				+ "h1GVUN3XJQOzI622cVWW7q6Typcpzo2NOAzWkNo6tGH0J6HHmj9jFYSKmmATls8gym9LF/q4yqr3FoU04VaWDbA37S5an/ktHvLN"
				+ "nrxrvvptSefC+IK4Azrx5Tv/TytuPKl0NSHFGsSZ0+SLonelGAHZBXdNnSydLY5AASJGzjmLpzBs9E3WHsvS1AX/Ni3xwH70LS3H"
				+ "EFDhhU+rFwXLLsj0R4a+N1YCVtefS24vrWJt4rNfLZ1OU9cS2nlUnxmPwo0XsaXRuxpd065O9RWh0HP4B1Z8ei2SaebnSg2236w2"
				+ "XUeaXU3Z3x2OA3p6GYNn9IaFtiYUZMnBo/TDNtjXMHS6KCpaLLWBiH5PL3+9PPBhzF29H2GLOB5jltMz9/9C3rqlvh+rT6u3WqzD"
				+ "0T9as6gHVNlgLZKJybRNWLHtnocNDdH0498H2eLs6rpoTFPHSMLn3ufNSP4JTApZgVHt7fSxM4hgb2XD8LduJFyRw9t3BU+Czysr"
				+ "YWmDGvva9zu3jxt7+mlV7aF9yqN5fRjO9poyy62bYet9GL2dE7b3pqjV9l/8+7w+jRiZ43soBkjOmhISy7Ib/2O3fT8ph20hX2w/"
				+ "CruThDmOJ7LQX1f376b3tyFF4pi0RcSeHMgfFRII3mFiCZWnR5o71JdL2yL9HI9Xv7rI7TmgUeDa12KPxWub91XCGt00Rqxm1sgh"
				+ "ZvpbL5NjeyoLGJ2dmO1tWvRsZRrwWe0TgwN4efeg89o4XPvFX5G69TJo+irx04PJrzd6p3oK1/aQF+7/yU6YHQnXXvKLOpsbaFdK"
				+ "n4bTypv++3jgf7NE/eio/cYQTs4/uz/eYy3xWNmxvB2+lnXAYQp6D+efo2ueTi88fKTs/ekjxwwkdbzxLOVD/IWLr+dJ66fss9PW"
				+ "EyQI+4c+znnNbqjlZ54cxt9+rbnkvVYnXp156Yt9OJd99FrT/f7DNkNPHF9kSeuV0NTgIw3F+Z4jNMlr7T2TCKNzSJmRzYGcxdMo"
				+ "ZbWy7hKH+RQcJcnKjdhv71p2vFHUvvwvhVhRSw5biaNGNJC593+HF5k0I/PHDyJzpw6mt678knayWdW/WDT90/fhx5Zv5XOmTmWL"
				+ "vnLi3T7q3i8JeSD+02gOZz+DT57eo0np8vueyk4A/rdOQfRjc+/Qd98pOQZvkhmjxlK3zttFn36T8/Rd06dRe/kCfN1zreqRI0CV"
				+ "1xgL0TyZvMra4PrW5vXlbxGfiNPWl+l7Ru/Rbd+r+Q1qCyuEquFLsMsD+HMUc3bohsNdJh0mtYFM95FVFxyTv/UUJq3+PN86sSnL"
				+ "7kPsyXY9yP3nEAHv/utNGvOSdQ+bFhJYUW9fxVgMa3hciuE5yp6ZeuuksmqJJ6Xclh+YbKSvCQ22PLQ72SfzXyWdNerm+mUySPZH"
				+ "nrg76mTRtGtL28MzshwloZXvvCJFC8zW+npjdsDn0CwliuA9AhLnPzFxHnfui304Btb6aUtO+k0PjsU4DGM8+/gzJESy9Qjxw/jp"
				+ "Wz4iq8gT/43gpe3WILCf8+hQwIfLDPDEtiP6yY6KNFxmNsiYZc5gDcjJk+k2X97Nu1z+gnBV4UKjOKZ+goaOvohmtf9zuArRGEOk"
				+ "qstZ9MehS29iWlPmvegI8sTVmGkBVsRAR2qwwA26WjXNg1h/pNn53ggn0vtIx7m0FdZRsDcwWdS+555Eh30N2fRcJ60AjiFrlRR1"
				+ "9YQ/MdvWoPrMH01LV4DCuCJonidBjFFHZoICLd5GsqTDyak217ZSCfzBNVaiMFEcDBPCLe9silYJuJaGGIwOb6+fRcdNWF4MLCCP"
				+ "NU1OJSPcGDvs4QT1i1rwpfv3cKT4JxpowMdIP6zh06mTx8yib545DT6+bwD6LK3zAy2795rXJAD/l1x/Ez6wL4TaClvf3LmfnQ5b"
				+ "3911oF04sRgdwf5hGWG9NNdkQao/4QD96HD3vdOmoovCxVvMdmXY3/NE9Zy7u9DOax3P/SS7mCkFNNPsOlII7qO1zXW9syR5QlLs"
				+ "HWgdLzegqgBYcsnijx1LTqSDn377zn5f3B4b+TQwpMAnvs7lAe8fPOvLFzJlP3QccPowiOmhnLkVPrc4VOoLYgPm7P3qA669uRZL"
				+ "Hv3yZHj8cUckAvOsHAGdgcvBXHx/aCx4VnFSXuOpHXbdtGTG7bTtp7wDEu44Yl19DZeQv7qrAPo4qOm0jnTx9C4dvf1uIN4OTiJz"
				+ "5Zu5UkR++eWNRvoCJ7wMCkWydM7Z46jFzfvpHNueiy4nvbzZ16nfz5oz74BjBO59/OEhYnvrJsepbPZ765XN9LH2SeWJD2rfVjHq"
				+ "6WnHXckHfaet9O4vQu/l4TM5X13H59NX0tzFuDrs9Ij2IY7PsTIsQ/oNp8kpPUfdGR5wrINArNDJWxuTVx2O10LJ/KAvY5yLXdz0"
				+ "tMKVhq/70w6/L38P/Oxh1PLkPCA1BlDt1VE7FFxoKiHGiaTtdt2FmRXINofF8Z//dz6ElmzdWdffAdPRFt39dKbO3voofVb6BQ+y"
				+ "wK4oH/7y+H1rO18BoYzLOFXz79OH7j5KfrFs6/zpDOEFvIk+au3HkAn8yQnyzcgOs6unuaJr4cnxnE8SWEZu3HHbjp9SliW1OWed"
				+ "Zvph0+tpe29+IEgT79b/SaN6WgNJjvhplVv0G9WrQ/O9Hp4BsMPDPuN7iSed/vyCbViKECmlBKkpgW0j9I7Ro+k/eadRrPfMZeGF"
				+ "x+TQud+ilrbnuBxcD7NmS+v/jEKLgmbcSaIFx8zXVzazJDlCcscYiKC6HobpUvYzWmfauflwCLKtT7BoY+zBN/8GzFhHM1+1zzat"
				+ "+sUah8ZnsHozAVdiM1eElcYov3sAaEVE8EP+IwH8v0n1tINT64ruaa1gSei5XxQr1CCWxSQGgc5ft2TC/JY/p3KkwjOuo7lZVZwR"
				+ "sTgtoVONWFhefbcph30o6deowvufJ7exmdDf31tC33swIlBHP4hR9ExYe3PZ1k3nTOb5SC68W0H0djOIYE9zK8I/MMLTjnayHXH2"
				+ "emIIeGSTE5UA5+CBp92XP9iCaxBU8L08RRzioUdR06dRAf/3dm096lvoSFD+16YiBnsamod8gB1dZ8dmpzo4kQ3q2Crki1dZsnyh"
				+ "AXQgUk60dXpyQbAiAk5HpDvoI4RD3GSK9gSHG3twzppn9OPp9k8kEdOnljd/wYdNXM3pBhy+WhwAbuNBdewwG18RrX3yE5667Qxw"
				+ "dnLfTwJAUxYQ9WS0GQ7z5B/fnUzTRne937BvjLx6+Bktv/D75+ieTc+2ieLeaIrXRaqWhbU9sJrdHDvGMCS0GwLJivcf4aztwBXY"
				+ "6sEXu0zcfb+dPj73kWTDzuIWoqv+jmQZ9T/x2dbN/E4ObBgE2y1QoVhly3QYVuapiDLExY6VwSY2yRoX3u6rkWH0Ikf+x0Pof/i0"
				+ "H4wtfCBgvupDuOBO9745p8JMrVVTNuBK05vtV3QNu2DM63h+ClR2QTomBBQ7x28BEP4+c07aNXm7TSfl3h3rd3cZ8eENJTPsErTh"
				+ "8upUPI8WQ2hrTzxSRjgL86inuOzwMdZNuzqCQQ3teKa2RbeYlko3uYePHT8UNrFE9EaXkIKqG/oH+aPa3hrOX6HTFgW3DGlaD/or"
				+ "nSwt3a0B298PfQ9b6exM6eGESFncyUf5LPwq3nikvWjZGVmadr1VvuaeqYnsyw3zta2anQo0ufpzAsm8Kn+pTwA/5nDfVeIcQEWd"
				+ "6nj2kb5VF7Nq0/YK7hH6kv3rS5YSjmel3XLTtwrWDZichBwxjT/zheCWwP+660H0r/c8gw9sD58PAW3FIxpb6O123cFd7+jiu+YO"
				+ "ZYWHjaFzvjvR4Ja48L+nsOG9N1kirOkQ8YPox/xcvQ7jxbvr0TrfjHvAPrdi2/S9x7T912GXHr0NNqD64CbSC86YirNmz6aXubJB"
				+ "zeWYoGH5enK1W8GN8GCa0/amw4cO5Re5IkVt1UMb2sNfK575FX64VPrAp+BYsOLa2gVPrP/RslXe3AX7SW0c+v19MdvSwfojq9Uz"
				+ "yTSwKxitk93ahL6D4gTPzqEl4CfZPUSDvc95Dds3BiaedIxNGrqpIJlYMGtBTt50nj4jZJn4UrYd1RncFEaDcTCD8srLAFxgygup"
				+ "ONWhrvWbgquddnJ0+Rh7XTw2GHBBW5w3B4jaNaoDhrFExuug+HC/+NvbKM/81mZPopwX9VpU0bT/a9tpnXb+98kOn1EO+0/eijdz"
				+ "Pliwhrb0UrXP7aW3sIT7SieOPGozwqesHYHmeZ5wppFT2zYFvxKeCS3HdfVHuOJ9pZX5GZXd9e7Y+JInhKf2V/7yJO0+p4Hzc+QP"
				+ "cTr2QV0149upo2vxGWo46P0zJJsbw9OzLbFDYZoxk0nOvp9b+UzqqUcOig04jNaHcEbP/c4iJd+ltcTV1ZohQxo4dUDE9b4zjZa9"
				+ "OeSR2NKwBnWUzxhXV14RKimVLBfd2/fUfgM2ZM8iZXMLf9FvT3dtHLp04VwpZRknhWyfA3LRIaY7sgknYr7qQ6gY95/I09WN3Ewm"
				+ "KxwQXXyYQfSYe9/F008eH8YAleheBVHkKs3Ra1oSUIa3wIZmKwakgr2Kz65NvPkY+nQc8+hMdP63ssI3kUtrbhb/nKacwHu6SgdP"
				+ "EXS6pki60M6afvQwXpCC/U5C8aEn3unT7H0/cw1dsbU4KJqx5iR7Bi66gzMUKaoctPC7KIzPWr8sODWhDt5WenilEkjg6Xrg+vx6"
				+ "6XkVU5la9l3Zt74DNlLtOrOe2nbhuJzmmzn08TcxbTltRvo9h/IehwJkQEQvTSz/uHMoRuYNcpv20kfb6Xh4/6J+/xLHNojHAo5G"
				+ "jZ2NM2Qz2gNCswx7GlE8j299OrDj4ef2d+J61t9fXYf4TU2d95wK23u/6aLGPyENcgw2xZ/9I6YQHTCR8/kyQmvJz4sNBY+o3XMY"
				+ "cHSr7qf0UqGrngSXYNlZ4pbID0DyC58Zv/uv9Lax/t9huznbFhMK5a4L+L1py+DLNEMI9l+HJfaw3D4Ka1nQhMb+Kxqz9n70dRjD"
				+ "6O2zvCDNTqhS++fvZA+RWMSVdu4lrj2Qa33QD3LspG8zK2vrQ9ug9iwpuR2j0dp+RWHFHRkBpBhnJ4pmumiu8YcORIuPHqfD54LO"
				+ "/R/nUMzTjmWWnmyiuv90gzN7AVtT5aiXqQb3VG1jWuJax/Ueg/Usywb7jLNfT9swjg68J1dtP+8U6m1+CJHfawiM8nQpWeSLE9Yr"
				+ "s7T48NxnOaCR2k6x41mTS+oSpPaR0bxN8B4PYKCQz8/Zddxbl2H3GR6lDceuJC+jXsGF6aeY3mI9Tt5Fbic++uXvBz8IS8Brx07a"
				+ "8bludaWkrcFKlxdnmmaYZwmb2PXItxM9STUyYccQDNO7vvKVh+4tiCP2mAyCKYzHi75nFwrCqeI/nrgVtBK9b5Q36bC606lmVcJy"
				+ "RRbILqrIFectrvyBFE+QOzApafFmQ+uhONrOfiZEj/nbebYzRwbhHlMbOIxwXp+Mw+PwJaDHvjkOL6XbblNVNj27tqxbcszj+587"
				+ "OKP4X5dFILCQH993uKneLsvy+O8JJwd2ELEF1sb4pcpXI3NAunbNnfBvtTSFjlheQYFJZNL3zaf30w5njj6dLbzBMNHNiafcCLiy"
				+ "Yd9OJzf1NvTw2nZrze/4/Xbf9vz7LcuZpc6M28xxqOesJLiJ6xBRvq2GWdY03nCqvUOivov0iT6v9PiWZn202eEyUhTo4pBYXh6G"
				+ "c8P6QkGE0VBxwTDk4aOz/NZDdGW0Ifje3liwQTE8dvXPL/5wQv+zvUsURy1bnz6/P2EVULdRuYAEdc+PYBwR/t+4YSVp0mHHBjck"
				+ "dx/jNnHXInV7hKRU6jpeEcWqcGv46nmq0jyPBHkcPaCuzOLE0ipXphgcuHZCtu4+GCCCbZYFmHC4Ukm37N7y7ZVT29/5MIPhm/lK"
				+ "za5FrtCU4s8k5KunX7CKmGgOq0eoG3SabqdtkESbnGGRTxhsSUjS0Jce8EkggkGk0f/CSZcJmEbhnnJVLjmEtoKEwz8enZu37b1+"
				+ "cd3P3bxP9oOBtt+BdXWsQVROrClBVG6AJsZBq60Llz+yfV53Txh5dJOWEibSWTnZBHdNj0Q3Kgl4SSesMIzrCKlo6B/lnqk9Uf7h"
				+ "7pKDQPOMvquvbABEwXr+fD6Sg7XV2gTny0Fdo7fxPbQN1gO4aJvLy+PeILJtWzq3b5188ZH/rLztT/dlF9/x3J2qyv9G+spD3+GV"
				+ "UIzDKSoNpYeTP0mrGNYU8mxvkI4F0wuOHuRpVFhAuGJA2cjalKReE7Mem5zrnCxtxdbXNQNJhjatGPtmm0Pnv83Vf4YXyRomAzqJ"
				+ "Dq2ZhwQO3DpmiR20bEFSXUgaUESPQ7xxRbYdFu+UTqQtMDUQZim/xmWzisKyS9TJGn4YKW045PQtZAnrNZgwhoxcfxvZ7/7rOs4K"
				+ "ZZFWziXTfmeXTiT2bR7y8atGx+6e9czV19kezC1mui6J29H/XDVr5Y6tsDUQVxaoPVKSJKPyyd5HaInLJcOEM4cyXba4MTsPITNT"
				+ "i1FTVjseg0tXzI/1BMh+YMkuscTj18SlpDlO93RYXqi0FvB6FQVXRqTpPO1TxJ9oNH7wqVr4tqEralH2UQE0bU9iQ4q0ZNippewK"
				+ "98o3RRB6wUspiKRkVmkGR7NiRoQxsHp7H/bQew6sKtJVN0rxZW3qxxpL+JtOjB1W5y2yzYuH8Gmu+qTNE8N0ghaB2Z6CbvyFd2sB"
				+ "0BYi2D62TDr1VQ0w8PPGAToZLOjdbigq/ESqhafPsxwOcTlkXYw1wNXnRpZT0ql6W2Y+aTMt5+7K33UWM0MzbQkFBEcuk7i9K8Wt"
				+ "cizXpgHiBkWtG6SJE2SvFx2AfFxPnG46pEkXylfpFq4xudgHleRNMvbGmSQ6MHiGDiRfR03KFzxcenqQbXKlf2G/LSeBHP/S7pyd"
				+ "EHbgRlnApvYTV2w6boMl+4CPlo8ZZL1M6woLAMnLkngIOm0DqDrwa0zc+n1pFrlmm0Wqq2jvml1gLCpY5tEB1oHWh84UKtotEe89"
				+ "yAl69ewpONk0EUNPvbVY7YPs/N1OIneLJTT5qh95po0ytWRf9q0mgHqUy42eCC0EHSTpA2DnmZbEkaRozxuYA9VRa0GwgAdAJFU0"
				+ "tZy9o2kwb7QuuDSo0iSJmlemnLaVx0GruSGo1mWhMm6PKd2R/AYTj/KGeguGnEYSvuwrWZb49D7Ik7X9bLp8EujA603GKgqxIqrD"
				+ "Q3cnsrI+hlWOnSK6r2TJQmNNvDq2viUlPRSYQugy/5KqgvaXkukDF1WjI6NNvczuPRMkvVrWOnolSUhsPa9HuQ2zINAcOlCGt9qU"
				+ "0nZ5k6q9gETlZ+OEx111rqQpF1J2lspUkaSuhV0bLS5xBClZ5JmWRImQy8J7cTlaTuIgEtvBGx1w9ZVzyi7HChmelcaweZr2sw8d"
				+ "Fn6AIVuphVcusZlrybVqh90CZt6Jsn6klB3nEsHrg62pTEPDqEc3VXuQKPraZK0ba44GzZfnYfWTWx2bUuia1z2WmAbX0D0cFuM0"
				+ "fai1a1njqwvCZMOykJY9XWoaj/RkwyUpLqrfgOFrb0mug3ADNeLqP3a6Mi+xTZKzxm3NBTt8ZJJsj5hyeA1t8AysAdlP1vaUTZR+"
				+ "8cWp7flCLDpSQSYumDGN4oItji7lP74Y/exSybJ+oSlMf/n0XrYwfpWhnCg6I4fiEGQpPySEV1DpBxsTb1cATa9XAE2vVFEo206z"
				+ "qVr0vpnhmZZEsZ1ZBivvcLJS1vi8jBxpU2TZxrfcim3bp7yse1nbG26xuXj0jNHM5xhuc5SLGcsqp8rvw8rSbmWOtSduLphW0sBN"
				+ "nsaATa9UgHV1uMEKF2bSwJJ9MyR5QlLOk3PPKZudGzD9bOu0EBVDvuplgJs9jQCbHqlAqqtR8UJWmf6goa9j4i02SLLE5Z0nBzo5"
				+ "jYpAzVRgEYciEn2h/ZJqzcDrn616Nj07R4oNn9tN30yRdbPsHTnmVtgdKy1n61GByhPSKLXm3Lqh7AWYNpMAbIFSfU4AWn0cgTUS"
				+ "08g2JQMQYkDWgdazyTNctG9XujykuhxVHswllM/hMsVkEaPE5BGL0dArXXgijN0UQMcPgEYH1rPJM2wJAQJO7Dh+lm3QesDSWYPh"
				+ "jri6tck/W3zwdamZ46sn2EJ0oH6YLMceLqf/XGZANf+jNIlrHWg9XJx5Zc276T+tcrX46AZJiwMEhHMSHrQWAaQxVREIrE19ag4o"
				+ "HWg9aSUk6ZaSNl6H5ajQ4BsBTNsInkA6DosSFkQU68FtcrXQJrhaYYJC4NKJEGvyxi0jkUdKfmJLoiuDxRTLxddTj3QdbW1EaTVN"
				+ "S67DTO/qDwlLsovinLSJCFNvsq3pBk6jyR6pmi2MyxB9NKO7XtFMtDuTqIGjISj9Dhsda4WSfJDHaP8zPqZYcGlJyFN2rR5a8pJm"
				+ "yZN2vxd/tqeRM8UWZ+wzI4zJ4nS+JL3YQWuZnqEowSk1aPQ9U0ywaUhaX7ip+tr0838kuQfl6crHmgf0VGmK02UDomrr05jIyp/Y"
				+ "NYtBUhWZtKMkfUJC4NEix48dkrHhk5jovOQ/IFNRx5iE13sQhJdE+UvAsytiWnX/jpO6g9El3YIWte4fGw6yqyGD0iq6zDQ7RZMH"
				+ "xCVp+DSU4BkqZKWWU7j0wxLQpOIAcTjNBgbJePV5m+z6UTQdVins6UFSXQN7FKO6ED8zXRR+Wh0eh0n+UuZoBIdxOkoP40/tloXT"
				+ "F37aN2FjovTsY3Ta029yqk7WZ6w9EARzIPTALuD3ZEi+qs5gUeoluhAdCnL5SvbStCTim6bS682UWXG1UG3H7rN32U3bTpsQ+IlP"
				+ "4grbxtmemyBLY0rT5tvAlCUSCISOw5GsjxhyQDB1taJlgGEi+5sDt7UYIl2o51tCZNkpuvo0jVixzYq7RCW0SwjWAozcp+P6GYYa"
				+ "B1IG7B1tdfWTjM+zj8JqJek1XUEYrflbSvb5mciZcBXl62x5Q1cegqQLHHSMssYHDTDktA1wDRhfMkL/Arb0rTQbQJkC6J0m7+uo"
				+ "+jjWB5luZhF8zaW21ieZnmqsH2c5X6Wa1kkn79hQfqtLG+wbGDZxrKa5SssAL4iANsJLEh3YSEMUCfI/2JB3AdYgNgFm659tA5qq"
				+ "WNbrg60biNpWlPXYRNLHLogKkm//DNNMywJgeiuzsWpVT74lVAmrXCLPy4BleqCTAxA9DaWA1kmBaGQPVh+zrIPy/+w3FiQ37L8k"
				+ "eVBFoDJ7icse7JcyTK/IJ9n+Q7LfSwupNyJQSgEdZrJ8j2W11n+LwuA3VZ3tM1m15g2m79p03abDmy6+Ei9MOHezDKlEAbi83aW3"
				+ "7McwCKID4Au+Zi6DdPu8gNRcS50mnLSDyqaZUmodRuhTzBJFVzCF/jpdFo0OuzS04BK6K2A8L4snSzLWM5nkYlI5Lss4EiWoSxXs"
				+ "FzEck1BlrJ8jeXXLDp/syxB7K0s/17YfoSlhyWKpPtEh211gE18XPXVelRZQGyYfM9gwb40mcqCuFFBKMQsL2k5Ji67iS6PSZos+"
				+ "zTDkhAYAyDAPgrix4aZF8Ji03G2Ml3E+Uq81G5LYQt0WokfXtiuLWzhY7YMYZ2vrQ6SZjHLqSyfZXkWBgOcjZ3GMo/lCBacpQmoC"
				+ "66hAV0P6PAbw4KJA37QzXriGpz4mGBSwbU5AT77sZzEchYL6oS0GuSPPAHSI17qp+NGsiAOoo8Ts37lYNvXGqOMOPc+EjsOVpphS"
				+ "ag70aWHlAwTa99bjUylg1inF9202XyA1oWXCtujC9skac18pK3HslzK8guWf4NB0c7yQ5Y1LH9gwdIUy80XWOawAJzh4RoazvpQh"
				+ "uQLfSHLepYTWXDNDDrOIgX4YHm2juUhGArAjmXvayw4a0Sen2TZzPIEy60sWDKjTqjbe1ngM51lFwvaA3DdD2VimTueBXHfZAFYM"
				+ "iIOopfHLlxjQ6PbnhBJkiT7NPkOTppxSah7vnQUlISsfW81KnS86esu106Uz+ksONvRch6LlIkD8RGWT7H8F8s/s+CajKv+trKwb"
				+ "Pp7lh+zvMryCRYTlPshFlwXk+ttOKvZwYKJDEtITHLIH3kBXYf3szzHcgvLb2BgcGYk4CznLSxYzmIi25tFmMuCMzSkQ57/r2A7n"
				+ "AV1xyRzHAsmo6+zwAdnnCezyNL5XBZMlrDhRwlssYwGH2NBHAR5xOHat5okPgZIIuLJMrqntQDZgmJc16L9aN7ifEGuLokrCkirA"
				+ "5uufcx4HHA40PHLn4ADCjYcXK8YsooFE4TkOYPlP1nwKyHSQHDmhXZhCaTL1TomHfEXkQPelLtZXmbBxKHtuE6GdNMK4T+x4NdJX"
				+ "b9DWOAjZzv4zxM++BFBfLDExA8i+JFhJ8uHWWAHP2DZxIJrdeJvE0ycyEOXjR8fUPYsZRP5FxbE4czSjKu/zFv8VDgeux+zxrslk"
				+ "2R9SWgTdCa21ULyBaauMcMaGWB6sOlBJ3bJAwfcZENwVqGf3n6R5T0sWOrgjAwTAyY2nBXhAjowy9B8lQUT0U9Z5BqWIPXAWQ9uq"
				+ "UAYYwmCiQFnW6gLJhRwAwsuZuPsS8DZFXwwoUjb/psFPnK9Cjpu28B1Myw1pQ4oB5PZcpbtLEiL5enHWa5iwaQscgyL2TaNtAVUo"
				+ "ichrT8jSaKa0DxkecJCD5sCMAJ0uIj97naT/ulKba54m11jFq7DiSrmAPde4Qznyyw4a1jBgp/ux7JEgYvgmFA+w4IlIc5o5AK3t"
				+ "GUYCyYRXDsSwQ8Cf8uC2yo2sgDcioHJS+7fQnpcV8KtGM/DUAATFsrAmSRA3rgeBdCGU0KVDmXBBCjLSOSHM9HrWBCH2zkguA0EE"
				+ "xlw7X9thy5h0y649CSk9WeQpJLuzxZZnrA0th7vbyv5FmEQrX1EN7dRI0r7ah/TH2Ep3IwDUQPdla/oun7Y3sWCfsdyzZVWg+s3W"
				+ "Cbh+pFc3xEwCT3J8g4l57Dg2tE/sAiYyDBpYSLD2ROuS2GZJxfxpWxcJEeeuI6FpR4mWNwkCzBx4RdAnE0ifjfLTSyS9myWe1lwH"
				+ "QtnbxBMkJjokoK8XPuhGpSZd1T3NxdZn7D0ADEHS8QoYNfQW/uILhOAhLVuYksPTH9bnOmjkZ/egStfly4/82Mp5fLRwI7rSljWY"
				+ "eLqYpF9ieUgbr78Mwt+VVtZ2P6FRXwEpEfZuFMfF+BxHe6XLEDKRp2wzMOEhEmtg0XOsO5gwRkfzr7eynInC34llLRYvuKMTpeLS"
				+ "Q+THDDrAzD+Tbvk59oftnyS4sozgkqKyx5Zn7DMwYetHjSOAeQwh6PHNcBtiC98dDrRbTbBDANcNMdBi7MXnD3gGpUWfY3nXSy4z"
				+ "gMbllJnsuBXQ1y4xoGOX+fSgFsQcF3sf7PIpIdfEHEvE7Y4q8KFfpyJHcVyPIvmdhacjeHGUzzi8x8s+EHABMu8g1lwNoZbEuS+L"
				+ "9xegF8+cbvECSz49VODpSWuV+EsD5PdApaHWXArA9D9JPen4XoeJj/4A/hg+QuwrxCHe7o0Uf1dLYp9n69HcZ5GAD0tvS16tNT/V"
				+ "0Jg88dW/0qo7YtY5ExCC+4hwn1Q8MG1G/yqZvpAcEBiMtN5al1+JcTd9NoOsNzChImzJdhwgX0JC66TmeVggtLpIai7xGPSETsQH"
				+ "c8yYgmpyxEfLEmRFrdN4IK/2AHOvNA2yR8THSZn3LqAsP6VEBMu7usSX9y7JXnhrAxnbxKHe8AkXZQAm10LsNkhoL99XvdTLBiPS"
				+ "X8lBLLNHJltGIO2YcCZW6B1EO6HrkX7Uq4FZwHgGlp+xQUFPYwPkbxMtD1KBwi78tHggjEegzEfhcHBp+/8xmSFAxx+UgaWUzi7w"
				+ "K+E8EU8Dj786obrP1G4ygWyHEWZUhbOsvDLIC7C46I7brHQd9kDaSuWfLhgLrc12MDyDmeJugyAPFA+2oI42Y8AOuqNemACRTvhh"
				+ "30FgT8Qf+Qjv2bizFF+0QTI6yAW1AFxWL4CpJV2VKInZ143j8ccT875x2n5ktkFaxJQXuZoxiWhiX0Qhd2NODPe7l9qd/kAV5xtg"
				+ "OEsyTZpwIaJQQR+mIR0HjgLwUGLi+y4MRPXgvC/dNxkBVzlAhz4cvCjLRAc7LhuhXLuYZHJCogPeDcLztLwQHbUAYU6yhmiBmFpq"
				+ "+Sp80ccHgDHWyzgC7tMboL4Iw8sGfH2CT1ZAaSFHfEyWQEpB1Sip6DMZBklyxOW7YCw2RQS7XRDhHZKogtRuvavVIBNt4XjBJi6D"
				+ "Zc/gI7HaL7Bgnu6fsWCe69MH8HUJZxEBzZd+8TpWgQdNu1ClL9NBy7dAFHBxFVG2myR5QlL/9ekO9T9v16fF5tLYwRYIfCM00Gcr"
				+ "v2rJcCm2wTY7CLA1Pv2EiO6xAPx13G4qRU3r+K5Qtx/hbMeM41g6joch+xPoHWQRAcSNn1cdsHlD6BLfUy7oHWDvqgy0maLrC8JB"
				+ "elQbDFw5GCSbX/sN5GaaSGSt6mbfkC2QOsDRTkDXadx6UCH8WwjfjXEXehJlqQ2kJ/kGaUL5egS1vZKqUWeTUvWJyxz0pCwffDoG"
				+ "0dLbiLtQw8+ex5FdLzLF3Zdt0YWodF0UEl6lw4kjK0Zl5Ry0xVIlFw7VVheY9MsF90F1yTi6mSb3ZWHWVYSkD/SDQaxoe210E1sB"
				+ "6Zpk/SmLrh8gOmPsPhovzh0eWaeKZEqRKLrlqaeg45mWRIC6Uhb5yqbDI5gW27nJ02n/VyjUttNXcJJdCBhl03HaV1T7j4pB10Wd"
				+ "AlH6YKpx/lokvhEYUtTTj4FKkiaMbI8YekDDj1uHoC2g1FhHSQ6j6S6bKN0W9hmB1oHSXUdBjabYEsrNlMXony0AJtuCpAtMO02H"
				+ "UjYjI+za3TY9JM4lw5cPmXgTKYjXHrmyPKEhRlHZh3pRHMWiuhca5TkiUibDrQOJGyL13Gm4OZKfDEHj7zY4qsleEEdHkzGi+9s8"
				+ "RAgW6B1QfsCU3fFCaaPENFHffwrC15SKL6Sj61vBG3TdkGXKz7aV7ZSBoAuYUkvcUBssgUJdKg6KkDn69IzRzMuCQWES236IxTuf"
				+ "tdOehTZdPhBN8NxwAcTFl4Jg0dYBJ3W1CUcp2sbwFsb/o5FHgUStK53hkvXmD64pQHPENrSYmvabXF42R7ed4X9ou0Yw3jOUfIXu"
				+ "9aBtgta1+i0Lh9g+tnCghknJNCh6qh+uPotczTDkjB5B9p/GTQxB5WETbugfYDWga6nrq9sgWm36SCJLphpBW0X3eYHtN2mS1pMN"
				+ "Hgm0rQD0U2bCd5Pfz0LHk/Rfrin6wsseBe75GGm12EzzobOQ3QtwKZLWNBhMy4hGC6xSaPGV6ZoliWhJmIQ9XOPGilJB2BEeQFST"
				+ "5sItrhqCQ54wRYvIug2aLtN1zYB6WGHaB2YW9v+0ojft1l+Fqol+Qk6bMa5ED/JT4tg6joMXL6eMmmGJWHUQCmNy+PYLTlGbGnhI"
				+ "Aea6MClA5euifOBTexax9dm8CK7B1jwTnS8OgZvH7iMBQ8RA/HHhxVwEycegsZD3nhVMj7LZYJ0n2PBc4F4AwLe2463L+B9WHrMd"
				+ "LOgXDw7iHLx0DPCeHMoOIwFj+PgFTd4GBsfioDIRyBw3ez/sOBdV8+wIB+U9TsWvKJG9j/e2oA3PQB8tRp54B1d8s7477N8qaALe"
				+ "LD5Ryx4nhJ1w9sb8EobfL1Hg/fVY0mJNuO1PXiJIOqBffhRFhe6LK0LNlt6gl7uy0r6HGhd47JngmZYEgqiuwdSsCSMHGc6j2ro2"
				+ "IoAUxeidAgOdjyjh1fCYKLCwYmJTD6oAPBaZLzLCm80wPIMrzCGjovVguSHV+vgQMZkhQeVcYc63oCAr+Pgc1oAd65fzoLJD88J4"
				+ "nob/DBByVs+cVc7Jgv5EAbqBcEbEBDGA9aIw4PZqBs+XoFXMeOHBrRHxuebLHgfFsCEJvngoWbkg2tkeDspdIBX5CBPvBsLkyfeT"
				+ "48fFvCBVNQNbzsV0I4PsuDhbZSPt5bilTkoG1+6xquWAfKW/EGcHuWfnFxJMowdQesal90zCDA7OFr63ofVnaeubhy0QOJBqX8yA"
				+ "XG6TfBSOYxWvOLGFh8leKcT3taAyUNsOGBhw8GsfeWbfXiTKMJ4VQz88O538QE4A5HvD8KGd00hHQ548QGSRgsmR7xVQoBNMH0hm"
				+ "AiR917Khpf+wYaXEmpfgMkL3yEUGyZr+OIlgNoXZ3qwY4IVG94rjzed4joYXo8jdkzM8MV7tsQGtA4k7BJgsyeT4Ks5qd6HJZJJs"
				+ "nyGJZ1mdiAGoaB1RoLsHqbQ6UR3pYcuYW3XeWhMuytfjcsHv6BhghPBhxhw9oFlmIC3eOKVKfhyjmArB34488KEJaCuOBvCRIY4g"
				+ "OUn+CcWeZmeq62C9pEtPjqBC+q6/vgeIdDv/HLlbbMjP6zvMYlpsKzF62Kw3NRgKYszU5xFCvI2VJ2/qbvqpEni46bkl2tP1peEs"
				+ "tUCtF6k5IFn5yDREaYuYVdimz2+XtE+uAaE6zR4SyauBYnI5+rFH98ixNIK6Dx0XtDlazp4KymWZyJYWuGMR5Z7ODPBr3a4nQDXw"
				+ "3D2ha9D4ys7+tP0Zv6yheAzXlgeYjmm6y4fbbWljUJ88DobvLUUZ05A7JjEsETFSw1duMoRO7YuXdB6ZST75bppyPoZlh44uufto"
				+ "yBXtd3hGry2gYy62ERji4fgovb7WHDxHGcqOCPBchBnVvJSOvHF9ST9mmAtAnR5mwJ8UV8RXIjG9xBxcRvAhmtk+IoNXsyHOkDHd"
				+ "SxMQKiLLX/ZQvC9Q9QVZ3XwhyD8RZZykPxxNoj6C7oOWNpGvTFC+2q0Hbr0pctfED9PFcjyhAVkMMkAMwedUBhU/caeHmyiYxunA"
				+ "1PXfnoLdDzQullPicNWzoZwVoIlDA5Eebum2be4WC0fZBB0OYIs9XDG9o+G4NoPloUanLHggxC4boS75nGGhSUiPggRB+qPJaq8C"
				+ "RWCyUZew+zqrzhwtoczTLwfXoMJEdfwEF8uUg9sXfVz6dWg2vkNKrI+YQk4MNHR+gDVemEQ6FuSAsyBJ/kAUxdcPhrx1+nMNG8Eo"
				+ "XASwFkTbOgvCHSIfKgUP+FLevzChk9tIY2APDGpYUmHi9ZSLi6049qNBj/n45oOvsqDa2O6jjbMeBlTsEscJjmcOeFFfhqcBeKDG"
				+ "bJEwwSGiQ+3SwCdtyzv9mfRdlOHYLkK8FUcDS6kox54lbOJpG1ASqoVVUcZA5kl6xOW7lzocqADrVuwjgtbWtG1AJtuEyBbIDquS"
				+ "+E7f/jqC35hw5mHFkwoeH85ll/4JRHvMcdZFA5G/JKHL+gIyBM3V+KCM+5hwr1SuBUC15xwO4EGs/Z5LPi1EGc++EQ88rybBb/GY"
				+ "UIBOFP5KwsmQsTjgja+U4g7zjHhIZ20BWViiYZrXbgNArdVANw/hV/m0FaUhbMtPCaEszQTlINJ/Fss+Lgr6q/3G0AYgl9HcVsDf"
				+ "vlDmZjA8YPDUha0HeWaSFobMhiwtekm2u7y0ehyLXq/asXVM7O4Gp4V0rVv7sJ9qaUVA5y7Pn8NrVgyP9BLwaCQfEWXgWLqwOYPt"
				+ "O4Cv8jhjEgvbTCh4NcsfLwUF6xx7epDLDgbwnIOHyeFHd/TQ3pMXgI+KoqbI3FRGu3EBXtMILgPCb8KYsIT8H1BTB7YYrLBZCGT6"
				+ "AssuLCOWxvwIVVMOljGYVmKieQ/WbBU1OCL0LitAGdKWG7KhIp64qvNAF95xld10CbckoC2yFkkOIAFH2FFu9BW3ICKyRuTOiZj/"
				+ "csm6oM88CwmJl9chMfkjts79K+B+PYg6i8fdRWwrMUtDbgpV39Uo9qYY6ZUn7cY/YS6PE7Lr8BjSdH+RbSeGdDIrCIdaHaktFnii"
				+ "ugJi3jCWt5vwqrFIND1BFE6EH+QJI1Nrxf1KLOSMlxpB2Jf2QkmrDxPWDmZsJKCNmSOrC8JMehk8MUPwOAnZOlnq7vkUw0B5hZE6"
				+ "do/yk9w6fXCLFMfRNU6oCppl6t+SetdrTZ4EpLlCUsPPugQPRD7D/RkN+lJXlqAbIEZb5NmJHr/DzyuOrnqXac2NOKuGhiyPGFJL"
				+ "5uTg4T7Txzx40L8TU93ntHodIJLN0mSJip9NalH+UnLsJUZ5S+kzdMzAGR9SShggoHogSc2B9YxqtOIXqkA2QKXbhKVRioflb5c9"
				+ "I6xlePSBUmDrS0vYNNd7TLLkLDOw4X2sdVVMOMkHbZaF5LonjJohgkLgw0DBaIHntgUOto6fiWNS4DWgY43pVZYK18lYndSDJIGW"
				+ "1deSfQ4KskvrhyJx1brQhLdUwbNMGFhYkg2gIIpROaRvvnEHGRJBx0y6MukANLq9P0KY5LowAyXgyuPJHVIogtiS5MGlOMjYa27M"
				+ "P0FM50rzvQT0vp7EtIsZ1iylQFjHziBp55PArSvzssmwGYXEUybGSe4dGCGy8GVR1wdsE+i7NjKfjP3n4RdOojTsXX5aHS9BNNXf"
				+ "IDOV+vAput6R/kDM5wCM+vmpVmuYQkyOLHVA9VCTHRzo3eO7UjS+1frII2ObZw9SheS6jYBLh3E+dhsUVh8kibNPs2yJJSDSh9cM"
				+ "f9lBdGmD8LVFiBbYNptPhqXXaN9XLomiY+gjyTRk+SbBO2vy0mbTxS2vEybDldLd2H4IJgkWXPQTEtCkOK/qcDV9Ee4UgFaB6Zu8"
				+ "9M+Gpddo31cukbsOFK0bkPbRUca6FoEm659tA5sdskfmL4uuw3TbkvjSpuEKuTn6iInldS34cn6hCWdpwe4YI6EXOkL/PrQfnBII"
				+ "4JpEz31aKwzun6im+2wIXZb+3Q+gq0cQcLY2vxMm8tuQ/sDnVbrGps/iNOxFUlJqiRl5D94yPqEhc7TB48+SMyDjcOmKUAb4waDj"
				+ "pfyIK50krcuw6WnJUme5eSPtkh7tA5sdlMXtB3YdG3TlNOGtG0tZ98Ikhb1ryQfj0GzLAn1ABIsg0lHW8cZjHASR9FtNmDTTQGyB"
				+ "S49LUnyrCR/G3qn2XRsy9WT4PKFXdpq5mlLY/prJIyt1gXoOq0rHxtmPh6DZpiwNBgEMhBiBkTuQDrjfPkYgqAPcK0DP9jc+0d0b"
				+ "MvVNdrm0jWmT1yaJP7abosHLt1Fqf/chXgd0Jgw6AFZnrD0pCEDAVubXqAkeBYN6XyMuro/Qse+X/YT8nQJsOlxAmQLaq3HEZeHm"
				+ "VecfxRReUUBP/GNShOVf1w6iTfTaLsZJ5i6Dsczd8Fomte9hHItD3FoQtrkWUa/qD9r6NkHPW5MThbbhFmbqHPEJjbjU1N4//dIy"
				+ "uX+hoaOfhvNOuERevYOvDQOaaolQOvA1KWepi6k1eOIy8PMK85fjjaEo3RstQ5cOrDpcWltaVy4fM10CCN/IHGy1eW66lbkxI+20"
				+ "kFdH6dc6y85uovHXuH4zD1G+fwCHn94OWJT03+nZQezbTKobJT6zl0wkVravsJJPsZRhUGDnxBz/5fyvRfSiivly8W2AZhW95TSf"
				+ "PumcyTRqZ/AJ8+u4qYfERoD3uDd8SXatuE7dOt18nGRpGA/Zo4sDwzXRGHDvh+6Fh3B/8thEGEwCXgN8BLq3b2EVi7TXzO2gXylT"
				+ "K0LrjpWWy+XauQxWKlP2+cu3JtaWvCl63PD4lBs8PWg62j3rkvp91ebr5pOSpBR1sj6YOwbAUyU7mb/04lmHvt37HUFu+L95gKfZ"
				+ "eUvorVP/5T++qt6DQ6UU+0+03nWIn9gy7eScpOkdfkkKStp/sAV5yojjDvj/BHU1nkR5fLzOYjLDxK1ks/iF/BZ/MOhrWykfpkir"
				+ "uMGM7ptMoD0VhO/H874TCcNGYp3vF/Ego8kCHfwanE+rViCDxxopCwTl11Ik67cvBoBXbdq6Y3PUee20Pi9P8Rn7l/jqk9RVX+aw"
				+ "4vogd/8N736BNpUKdXIo+EYPB2dnrjBLbq2xZGned34SsxlnARfqpFfD/Elmx9Rb+8XaOWVL4WmxJh1qJZeDRo9v1pS/brO6z6Rs"
				+ "8SXsY8Nswe5Dfwf3teoZ+c36ffX7CwYo0haLykgUwyWwVMu0j7dyaL3jZjCNh1d3ceG17eCD50Kmzjbb9DOrVfTH6/Vn5KqFkkHa"
				+ "7nY9lMtSVuGzb8W9UySZ/Jy5y6cTi0tX2ft/ZykkCbfw/oN1NtzMa1c+mpoqyqoX+aodkc3Erpt5Qxq+Euna71oO+6DORo1+X08B"
				+ "vEJd/0Z+OfYazE9e/sv6Bl8X7SkfJcehfglySeJ3giUU3+AsMvHJKlfbTjz/GHU1oGvWC9iGa6qfktwm8KKJfdzoNpIO7HNHPXtw"
				+ "Pqi2xY3WHUHu3QbYb5zFwyjljYMTAg+yincwi7zafkSfCFZ5yP5Sp1s5TWSjq0nKYeck6PJs9/L/5Fdzruv8B9ZsCuf5z+L6fm//"
				+ "JyelK/p1wzpw0yR9YEo7ZODTh98+qBMis4HlOrBqX8rzrbeF4RD8GXiG9jtizxx4dRfpxHEV/LXaFutdIBwlC7+9WYgy05PcKmAl"
				+ "rGGL1ozwe7bzNtv0O6dy+j3V+PL1/VA+i9TDJ6BkB5X2+QA0AdkUlyDoDS/ru4TC9e3jg1NAfiU+lcp3/stWnElLq4mLV/qC9Lo2"
				+ "AKbT7WJqguIi6tEN0Gc2F16HGl8Q7oWTeYkl3GqD/G2pVDFXtZ/TL09n6eVS9cEfulx1cXVNtGDCmSNdJ0yuNBts3W6zZYEc0BoH"
				+ "YThUz/RQp2jPsz6ZSw8mPt4ivL5bnr2jt/QM7dH5dVIOrYeG6d/ppPag9tdLmTRD8vfGdzucteP7qaNrxRMdUH6S/owU2R5IOq26"
				+ "QNQqM+BeOYFI6htyEVcFAZ1pyp2BesLeJmIGwSlHnqwmTYwULrHxHpDMXYZbiimi2jNIz+lh28KDAPEQJZdM7I8IG1tk05EnNbTY"
				+ "KZDOEoP/bsWzeKVAg/u/N+yWXzwCMb3eMlwKS8ZXg9N/YjLH5SWZbe70gFXXFxarYMkfrY0UXpcWqDj4ojKM1ke4SNbuE7FsxYIk"
				+ "m3lM6orKd9zBa1chse30uIqv1w7tpnD1uCsoNsmnac7UvS0+yAqjY7rr4+aRHT8h3iQB4NdP+S6nuVLtGPLd+iWa+MecpV6A5vuL"
				+ "j8kyh+IHZg+zc2cBROpVT8UH+wa/pP/GU9WeCh+VejYEEgfZoosD0TdNvMABOUcjNq/fP2081qoY+g/cpAHP00MbCGPsdsCeuaO3"
				+ "xXu3wLll1M9vbk5/dPt1D7sM6x9kWV0YAvI3cO7Cbet9HVWAyD9hm3myPKALPfAc/lHDQA9QJLoIV3dY9jKB0EOB0N7aAy4iZcWC"
				+ "2nF0icKYU8p2I+2PqouUw4hOvjsd/DybwkXuX+xC3Mv8xnVF2jDmn+nu3+Cx7KiqE9d+1M61jLCQOzIeqHbZnaejDyQdh/odHowp"
				+ "hkgpeV3de/HB8WVrL8jNAXg1odrqbfnK7Ry6ZuhyYpZh2rrGtiBGSf+Ot6VRxRmehNbGcAsL0oH8f5d3bP5L5bu8wJrCO6huponq"
				+ "6/z8m8T61H5AW03bcCWrlp6JpEGZhVbZzYaYd3C61tdrPJBkj84jEKV8+v4z7/S1jevp9uux0V6W5tqrTcPc+aPp9a2S1n7F5a2w"
				+ "Bbui1/xRLWYJ6pnQ1PNidr/SfoMeubI8oCsVdtsAwFliV3rcfSv4+nntVH7UD5YcjhoxofGgAdZFtAdP/g9bQ7e6aYHZxRJ/YD2T"
				+ "ZOuVrjqUEnd7G087dNt1DHskxz8VzaPC81B9AO8xe0nfwj80lNJXSsB5WaOgdiR9UK3zT5Iy8OVlwwQM29XeVH55GjOwnHU2soHD"
				+ "32CZQgiCvyaXbr5AJL3e6fN30USf9hBXF4udHqzPJA0X0lr5gei8tBlCnhl0FvZvJTV2SqrtaxfQpvWfp/u/Dec2QJJq/Mx83TFm"
				+ "TpAOIm/RuxR6TKLbYdkBVfbXB09UETXoWvRbMq18MFEZynXHbw8uYbyPV+jlctwLaXRce3ztHp16Vq0P+UwUdE5YREoKrh2+O3w2"
				+ "uEyPE6VliT1tfm42iw6tiCtninQsKwibdMdV432VntQ6Hra6penfU7KsfBBRbgwf0BgDXmFJ64v0oaX/43u/jEesrbl5dKFNL7ZY"
				+ "M6CMXz2ejE379Mc0r/O3kj53kW04sonC+FaUuv9i/wzRzYHZIirbTJQpEPT7APXINN2m67LEj0pkiZHZ352CLV1nMc6H2wlH9i8l"
				+ "2U+Lb/i1jBYdYp1CLHp0i6xNx7Hf7iVRu35ca7il7m6exSsTO5RDi+gO25YnvL6oI24/VQvpD8yReMOrsqpZdvSDj4ZPEhjDqT09"
				+ "Zw7fw9qaeODLscHX761kEWez7b+kzef4zOEFwI/T8iwsUQnf/wM3k9X8f45TO3y9Ry+lDa99j2684a0n9EaCPS4c+mCOc4ygdnIL"
				+ "KHbFte5aXDllVTXiD0Oe37zFvPBF9wrdGYQDsGrmZdSz67L6ear8Bkynbb5mLtoH2rJ4QHldxcsABfRv0u9uy+llcvwWNRAUOt+M"
				+ "cdaJsjyQK5n28zBJ2EZNEl14EprxoM8HXlujvbYmw9GHJS0T2gOWM3Rn6dtG35Ct16Hu7F1nmmR8gYPZ5w/koZ0fp61z3KzO1UTl"
				+ "vOZKF5PzMvATFNuXzc0g28gJqcWbZPJQg8GCUt5aQZK9ep42ic7qWMEH5w5HKT6vUx/pnzvfF4m3lUIZwW9z4sc/5EWGjXxIxz1N"
				+ "Q5NUm5P8kS1iB75nxtpTaWf/BsUpBmHg4bqHTCNh55AtA4Q1npSdF42zEESVQeQtGwzvVvvWjSJci04WPmg7fsMGa5v/YS3F/GZR"
				+ "drPkA0e5nWfzH/xpe6jQ0MAHmv6Km3f+G3603eTfEYrK+hxlhmSHjCDEVfb5CCXDk2zD8wJwsTM1+Zj4ipflwXMsl1lhXpX9zEUv"
				+ "qYZB7GwmeVy6u1ZRiuX4p1NUXkAM9yYdHXP4Bric+/v4apKXXu4+t+n3t2X0Mqr1hZszYT0XaZo7IFYGbVqm+sAr0SvDQedlaNph"
				+ "72Hj2F8GGNmaAx4gc+4PsfLo//k5ZHUY/Bx5vnDqa1jMWsLeTcWvlaE5uT+UPjc+wOhrSkZvP0aQe0OloFHty0YxaHap0uHpt0HO"
				+ "l2lgyJt2eVxxmeG0pChi7i2i7nE4X17gOhWnrjwmf37gtBgYfZZLTwR46Ok+DjptNAY8Cy3ZzE9e8cv1fvEGpliT5Tq1aDSsdmQ1"
				+ "OeAGRiStq3cgZIknQwa+Ln0cpCydR3i9a7uaXy2hYP87/ts4Wf2/43PSL7IZyTytQSdvrHoWnQc5Vqw1D0+NIA8Hk/6Ou3afjX94"
				+ "Vv1+oxWo4M+zByNOSirQ7ltQzpXZ8uBLPFShj7AbT4ufWDo6j6+cH3ruNAQsJHlMtqx5Rq65dodoamB6Fo0let8Ge+2D3BIfkzgy"
				+ "Tb/77z9PC1fkubTNLq/soqMs0yR5U7TbavlAJW89URk04GEa1WXOIpln/CRHI3c84Os4TNkUwNbyDPs1k3P3PHrhlhWnX7eUGoft"
				+ "oC1z7GMCGwhtxeWs/cUwoMRPRZcerkgj8wxUAdOPahF22yDQA8ygHCawWLz13mauq2ctHqROReMoNb2CzmKJ4Xc0NAIt9zNgW35E"
				+ "ryHC2nrS/DA94nnsnY5F79XaAxYxRPVhbT6/p/RYyv7t8cjZHLf1H8g1g9X24KjMVRL9KTIQEA6lw5c5YifIPaBpWvhXpRrxa0Bm"
				+ "CSkTniE5X9Tz+5L6OZlwVPBdaFr0ZHhdar8qWFVgt23hbdLaOe2K+mP3zY/o6X372DBVWdzrJTbLqTNHIOtk9NQy7aVMxhQH0kn+"
				+ "kDuf11+WK9Rk3J03IdOKVzfOiqwhbzB8hXatvFauvW7tXtIuGvRnlz2V7la/8BVKj7UTfRT6u25iFYuxUdKs4TZBza9XMI+zRiV7"
				+ "pRGptZtixpUEieDJomuSeuvSevfn9M/3Urtw3nSINwxv2dgC3mCs1tI9/zsJlpfxU/wnfqJDuoceT5rX+AqjwqNIH831/4CniT/T"
				+ "NsHw3sKG4r0/T4IwIDOKq62oSPNgzopSQeB5G/LW5efpuz6c+ZnR1FbOyYRTCYdapf9lvK9C2nFlY8VDOWx5wE5Ouyd7+SzqiUc2"
				+ "lftkpcIn9F69fEf04P/HfcZLY8d6axM0dgHTGWU2zaZTIDWbaQdFJJfI+x3WxtNPaRr0b6Ua8Gk8q7QAPK8NMx9h3bv+DL9/pr0r"
				+ "2iZu/BQamnFq3HmhAaQx6txrqJdO79Bf7gGjxE1E9UeF9KPmaIRDpxaYWubHhTlDBBJI4MhKr32idMbnRwNHU10yj9jcuFJJndoa"
				+ "A6q/zrLv9K2DdfRrdfJxxrczF00gVpyX2Ltnzgf9Rmt/C+Cu9RXXPl8wQZQgOxjrQ8WBrL+KC9zDLYBkAazbTJgogaOK07bZSBIX"
				+ "sDUgSsvIS6+MXnLB9pozBRMNph0JoTGgIe5SQvolu+spB2Wk6MTPtpOIyfgM1qXcGhsaAy4v/D6mz8VwtXC1T/NQibbO/gOmOSYb"
				+ "at0gtCDvpzBoNOLbqtPpfVMiq4L0OXG12HO/LHU2saTT+5THNKfIfsNT0DdPAE9FYTC1xOfzX74Os2BgS3kVS7mYtr65g/otuuzd"
				+ "p2qXn0YhfRvphjonVpLatm2JAMyasAg7WAaUO62dnUfSMGnsvKYlArGPN479U1e4v2cci34MKmKox0c/hb17P4a3XxVOZ/R8iTDT"
				+ "1iDDFfb9GSTZOIxkTQyIGx6kjzLKbtcdB1rQ1f32VwKT1w5fRZlkP8N9fYuopVLny4Y6kXt2994ZLK99TpgBgJX2/REUemkkXZQJ"
				+ "KlTvTDLTFsH7R/qJ/7DEBqxR+Fz7/o6Vf5hyucW0O3Xr6StuAfVCvIAZh1c9mrRvx39cdnjMPMGtWqHiZSXKeq18waCRmubbdCLz"
				+ "RzYUTq2QtI0wNTTIOk0sNnzmTN/ArW2fYld/paXhV+hLa9dR3fcEP8LYvZx77PqU69yPB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px"
				+ "+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8H"
				+ "o/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+Pxe"
				+ "Dwej8fj8Xg8Ho/H4/F4PB6Px+PxeDwej8fj8Xg8Ho/H4/F4PB6Px+PxeDweT4Yg+v8Bclnz6qOeCPAAAAAASUVORK5CYII=";
	}

}
