#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 8080" \
        s6-setuidgid abc \
             /usr/bin/java -jar -Dfelix.cm.dir=/var/opt/openems/config -Dopenems.data.dir=/var/opt/openems/data /opt/openems/openems-edge.jar
