= Battery

A battery that is connected to a battery inverter.

== Battery Coolable 

 * Declares an OpenEMS Battery Component as being able to get cooled.
 * Cooling channel gives current status of cooling valve state.
 * It is required in order to activate and deactivate the external cooling system in accordance with the cooling valve's actual condition.

== Battery Heatable

 * Declares an OpenEMS Battery Component as being able to get heated.


== Battery Inhibitable

 * Declares an OpenEMS Battery Component as being able inhibitable. 
 * It indicates whether the battery main contactor can be unlocked or not.

 
== Battery Balancable
 
 * To get the necessary data from each balance-able battery, read channels are needed. 
 * The acquired data must be used to make a choice before each battery balancing application is launched. 
 * Batteries must meet all prerequisites in order for the balancing to be activated. 
 * To turn on and off battery balancing, the set channels must be written on each battery.
	 
