= ESS Time-of-Use Tariff Discharge

This Controller optimizes the behaviour of an energy storage system in combination with a Time-Of-Use (ToU) Tariff. 

The general estimation is, that during the day a local PV system can provide enough energy to supply the consumption. This Controller than evaluates the predicted consumed energy during the night (using production and consumption predictors) and tries to move Buy-From-Grid periods to cheap hours.

This implementation works for AC, DC and Hybrid ESS. It is currently limited to the ToU tariff by aWATTar.

1. At 14:00, controller collects the Hourly prices from the aWATTar API and also the predicions of production and consumption from prediction service in OpenEMS.

2. It calculates the boundary hours to differentiate day and night, so that the controller can get defined set of hours to work on.

3. During the start of the boundary hours, based on current State-of-Charge and hourly prices already calculated, it determines the set of cheapest hours.

4. During those set of hours (Cheap Hours), the discharging is blocked. consumption is covered from the grid.

This Controller applies to the legislation of Germany.

TODO

Time of Use (ToU) pricing API service is currently under implementation in OpenEMS. This service will eventually act as generalised service for all the variable pricing providers.

Once the ToU service is implemented, the test cases can be uncommented and tested with custom hourly prices. Currently only way to test it is by using the actual API provided by Awattar.
