package io.openems.edge.battery.soltaro.cluster.versionc;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.battery.soltaro.ModuleType;
import io.openems.edge.common.startstop.StartStopConfig;

@ObjectClassDefinition( //
		name = "BMS Soltaro Cluster Version C", //
		description = "Implements the Soltaro multi rack battery system.")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "bms0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige; ! Soltaro Cluster needs baudrate of 57600 !")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 0;

	@AttributeDefinition(name = "Number of slaves", description = "The number of slaves in this battery rack (max. 20)", min = "1", max = "20")
	int numberOfSlaves() default 20;

	@AttributeDefinition(name = "Module type", description = "The type of modules in the rack")
	ModuleType moduleType() default ModuleType.MODULE_3_KWH;

	@AttributeDefinition(name = "Use Rack #1", description = "Is Rack #1 used?")
	boolean isRack1Used() default true;

	@AttributeDefinition(name = "Use Rack #2", description = "Is Rack #1 used?")
	boolean isRack2Used() default true;

	@AttributeDefinition(name = "Use Rack #3", description = "Is Rack #1 used?")
	boolean isRack3Used() default true;

	@AttributeDefinition(name = "Use Rack #4", description = "Is Rack #1 used?")
	boolean isRack4Used() default true;

	@AttributeDefinition(name = "Use Rack #5", description = "Is Rack #1 used?")
	boolean isRack5Used() default true;

	@AttributeDefinition(name = "Watchdog", description = "Watchdog timeout in seconds")
	int watchdog() default 60;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "BMS Soltaro Cluster Version C [{id}]";
}