#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/keys \
    /config/site-confs \
    /log/nginx \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx
