package io.openems.edge.system.fenecon.masterbox2v0.relay;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "IO Fenecon MasterBox2V0 Relay", //
		description = "Implements the Relay of the MasterBox2V0.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "io0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "The id of the Master Box", description = "The id of the Master box component")
	String ioc_id() default "ioc0";

	@AttributeDefinition(name = "Ioc target filter", description = "This is auto-generated by 'Ioc-ID'.")
	String ioc_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "IO Fenecon MasterBox2V0 Relay [{id}]";
}