package com.ed.openems.centurio.vectis;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "KACO blueplanet hy-switch", //
		description = "Implements the KACO blueplanet hy-switch component.")
@interface Config {
	String service_pid();

	String id() default "meter0";

	boolean enabled() default true;

	@AttributeDefinition(name = "bpCom-ID", description = "ID of bpCom Interface.")
	String datasource_id() default "bpcom0";
	
	@AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
	String datasource_target() default "";

	String webconsole_configurationFactory_nameHint() default "KACO Centurio blueplanet hy-switch [{id}]";
}
