package com.ed.openems.centurio.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "KACO blueplanet 10.0 TL3 hybrid Ess", //
		description = "Implements the blueplanet 10.0 TL3 hybrid ess component.")
@interface Config {
	String service_pid();

	String id() default "ess0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readonly() default false;
	
	@AttributeDefinition(name = "bpCom-ID", description = "ID of bpCom Interface.")
	String datasource_id() default "bpcom0";
	
	@AttributeDefinition(name = "max Power", description = "The maximum power (W) of the blueplanet hy-bat battery")
	int maxP() default 4000;
	
	@AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
	String datasource_target() default "";

	String webconsole_configurationFactory_nameHint() default "KACO blueplanet 10.0 TL3 hybrid ess [{id}]";
}
