package io.openems.edge.scheduler.fixedorder;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.scheduler.api.Scheduler;

@ObjectClassDefinition( //
		name = "Scheduler Fixed Order", //
		description = "This Scheduler takes a list of Component IDs and returns the Controllers statically sorted by this order.")
@interface Config {
	String id() default "scheduler0";

	boolean enabled() default true;

	int cycleTime() default Scheduler.DEFAULT_CYCLE_TIME;

	@AttributeDefinition(name = "Controller-IDs", description = "IDs of Controllers. Controller execution is going to be sorted in the order of the IDs.")
	String[] controllers_ids() default {};

	@AttributeDefinition(name = "Controller target filter", description = "This is auto-generated by 'Controller-IDs'.")
	String Controller_target() default "";

	String webconsole_configurationFactory_nameHint() default "Scheduler Fixed Order [{id}]";
}