package io.openems.edge.ess.cluster;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "ESS Cluster", //
		description = "Combines several energy storage systems to one.")
@interface Config {
	String id() default "ess0";

	boolean enabled() default true;

	@AttributeDefinition(name = "ESS-IDs", description = "IDs of Ess devices.")
	String[] ess_ids();

	@AttributeDefinition(name = "ESS target filter", description = "This is auto-generated by 'ESS-IDs'.")
	String esss_target() default "";

	String webconsole_configurationFactory_nameHint() default "ESS Cluster [{id}]";
}