package io.openems.edge.chp.ecpower.control;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "CHP EC Power Control", //
		description = "Control (modbus writes) part for EC Power XGRI CHP")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "io.openems.edge.chp.ecpower.control0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Total active power", description = "Sum of active power over all CHPs")
	int maxActivePower() default 40000;	
	
	@AttributeDefinition(name = "Regulation steps", description = "Number of control levels, for example, 2 if two CHP units are to operate in full-load mode. Use 0 for stepless (continuous) control.")
	int regulationSteps() default 2;	
	
	@AttributeDefinition(name = "Hysteresis [s]", description = "Hysteresis between transition steps. No effect if stepless control is configured.")
	int hysteresis() default 3600;	
	
	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "Debug Mode?", description = "Enable anhanced debugging")
	boolean debugMode() default true;	

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "CHP EC Power Control [{id}]";

}