#!/usr/bin/with-contenv bash
# shellcheck shell=bash

CONF_DIR="/var/opt/openems/config"
CONF_DIR_DEFAULT="/var/lib/openems-default-config"

if [ ! -d "$CONF_DIR" ] || [ -z "$(ls -A "$CONF_DIR" 2>/dev/null)" ]; then
    echo "Copying default configuration files to $CONF_DIR"

    if [ -d "$CONF_DIR_DEFAULT" ]; then
        mkdir -p "$CONF_DIR"
        rsync -av "${CONF_DIR_DEFAULT}/" "${CONF_DIR}/"
    else
        echo "No default configuration files found in $CONF_DIR_DEFAULT"
    fi
fi