package io.openems.edge.ess.stabl;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import io.openems.edge.ess.stabl.enums.EssState;

@ObjectClassDefinition(//
		name = "ESS Stabl", //
		description = "")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Use external sorting?", description = "If true, module ranks are fetched from the external solver. If false, internal fallback ranks are used.")
	boolean useExternalSorting() default true;

	@AttributeDefinition(name = "Number of strings", description = "Number of active strings (1, 2, or 3). Controls how many SOC/temp values are sent in the solver observation.")
	int numberOfStrings() default 3;

	@AttributeDefinition(name = "Solver URL", description = "URL of the external Flask solver (e.g. http://lcoalhost:8090/pdist-calculator-stabl).")
	String solverUrl();

	@AttributeDefinition(name = "Debug logging", description = "Log power distribution per cycle.")
	boolean debugLogging() default false;

	@AttributeDefinition(name = "Ess state", description = "Switches the ess into the given state, if auto is used, ess state is set automatically.")
	EssState essState() default EssState.AUTO;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Ess Stabl [{id}]";

}