package io.openems.edge.deye.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.deye.enums.EmsPowerMode;

@ObjectClassDefinition(//
		name = "Deye.BatteryInverter", //
		description = "Implements the Deye Battery Inverter")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readOnlyMode() default false;
	
	@AttributeDefinition(name = "Debug mode", description = "Enables Debug mode")
	boolean debugMode() default false;	
	
	@AttributeDefinition(name = "Extended Debug mode", description = "Enables extended Debug mode")
	boolean extendedDebugMode() default false;		

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus-Unit-ID", description = "Unit ID of Modbus bridge.")
	int unit_id() default 1;
	
	@AttributeDefinition(name = "Battery-ID", description = "ID of connected battery. Leave empty for no battery")
	String battery_id() default "";	
	
	@AttributeDefinition(name = "DC-Charger-ID", description = "ID of the DC Charger component. Leave empty if not used.")
	String dccharger_id() default "";	

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";
	
	@AttributeDefinition(name = "EMS Power Mode", description = "Power control mode of Deye EMS")
	EmsPowerMode emsPowerMode() default EmsPowerMode.AUTO;	

	@AttributeDefinition(name = "Max. Power to grid", description = "Max power to grid. Includes PV limitation")
	int maxSellToGridPower() default 10000;		

	@AttributeDefinition(name = "Max. Apparent Power", description = "Inverter´s apparent power limit")
	int maxApparentPower() default 10000;	
	
	@AttributeDefinition(name = "Min battery capacity [Ah]", description = "Value is stored to hardware")
	int minBatteryCapacity() default 5; // Ah	
	

	String webconsole_configurationFactory_nameHint() default "Deye Battery Inverter [{id}]";
}
