package io.openems.edge.controller.symmetric.powervoltagecharacteristic;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Controller Power Voltage Characteristic Symmetric", //
		description = "Defines a power voltage characteristic for storage system.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlPwrVltgChrctrstc0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id();

	@AttributeDefinition(name = "Meter-ID", description = "ID of Meter.")
	String meter_id();

	@AttributeDefinition(name = "Active-Power-Characteristic", description = "Active Power Characteristic Option.")
	boolean activeCharacteristic_enabled() default false;

	@AttributeDefinition(name = "Active Power by  Voltage characteristic ", description = "The graph values for power and percentage")
	String powerV() default "[{ \"voltageRatio\" : 0.9,\"power\" : -4000 }, { \"voltageRatio\":0.93,\"power\": -1000},{ \\\"voltageRatio\\\":0.0,\\\"power\\\": 0},{\"voltageRatio\":1.07 ,\"power\": 1000 },{\"voltageRatio\": 1.1 ,\"percent\": 4000 }]";

	@AttributeDefinition(name = "Reactive-Power-Characteristic", description = "Reactive Power Characteristic Option.")
	boolean reactiveCharacteristic_enabled() default false;

	@AttributeDefinition(name = "Q by U characteristic ", description = "The graph values for power and percentage")
	String percentQ() default "[{ \"voltageRatio\" : 0.9,\"percent\" : 60 }, { \"voltageRatio\":0.93,\"percent\": 0},{\"voltageRatio\":1.07 ,\"percent\": 0 },{\"voltageRatio\": 1.1 ,\"percent\": -60 }]";

	@AttributeDefinition(name = "Nominal Voltage [V]", description = "The nominal voltage of the grid")
	float nominalVoltage() default 230f;

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "";

	@AttributeDefinition(name = "Meter target filter", description = "This is auto-generated by 'Meter-ID'.")
	String meter_target() default "";

	String webconsole_configurationFactory_nameHint() default "Controller Power Voltage Characteristic Symmetric [{id}]";
}