package io.openems.edge.bridge.modbus.tester;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Bridge Modbus Tester", //
		description = "A minimal Modbus device for testing and debugging a physical Modbus communication channel.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "modbusTester0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge (e.g. 'modbus0', 'modbusAscii0').")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID (slave address) of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Register Address", description = "Start address of the register to read (0-based).")
	int registerAddress() default 0;

	@AttributeDefinition(name = "Register Type", description = "Modbus function code to use for reading.")
	RegisterType registerType() default RegisterType.FC3_READ_HOLDING_REGISTERS;

	@AttributeDefinition(name = "Register Count", description = "Number of consecutive 16-bit registers to read.")
	int registerCount() default 1;

	@AttributeDefinition(name = "Modbus Protocol Type", description = "Transport protocol of the connected bridge. Required for correct Message channel reconstruction.")
	ModbusProtocolType modbusProtocolType() default ModbusProtocolType.ASCII;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Bridge Modbus Tester [{id}]";

}
