package io.openems.edge.goodwe.et.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Goodwe ET Charger", //
		description = "Implements the Goodwe-ET Charger.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "GoodweET-ID", description = "ID of GoodweET device.")
	String ess_id();

	@AttributeDefinition(name = "GoodweET target filter", description = "This is auto-generated by 'GoodweET'.")
	String Ess_target() default "";

	String webconsole_configurationFactory_nameHint() default "Goodwe ET Charger [{id}]";
}