package io.openems.edge.controller.ess.chargedischargelimiter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller ESS Charge Discharge Limiter", //
		description = "Limits total charge and discharge for an Ess. Sets ESS into balancing mode after a configured amount of charged energy")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "chargeDischargeLimiter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id();

	@AttributeDefinition(name = "Min SoC [%]", description = "Discharging is blocked while State of Charge is below Min-SoC.")
	int minSoc() default 15;

	@AttributeDefinition(name = "Max SoC [%]", description = "Charging is blocked while State of Charge is above Max-SoC.")
	int maxSoc() default 85;

	@AttributeDefinition(name = "Force-Charge SoC [%]", description = "Charging is forced while State of Charge is below Force-Charge-SoC.")
	int forceChargeSoc() default 95;

	@AttributeDefinition(name = "Auto Discharge", description = "Discharges battery with 5% of max discharge power if SoC is beyond maximum. Especially after balancing process. Hint: Set to false if ESS is working in a cluster")
	boolean autoDischarge() default false;

	@AttributeDefinition(name = "Charge energy between balancing [kWh]", description = "Charged energy to the next balancing cycle. Set to 0 if balancing is not desired")
	int energyBetweenBalancingCycles() default 100;

	@AttributeDefinition(name = "Maximum Price [ct/kWh]", description = "If grid purchase power above that value battery will NOT process balaning. Leave 0 if price should not be considered")
	int maxPrice() default 0;

	@AttributeDefinition(name = "Force-Charge Power [W]", description = "The charge power during force-charging. Attention! Includes charging from grid")
	int forceChargePower() default 500;

	@AttributeDefinition(name = "Balancing hysteresis [s]", description = "Time for balancing out battery cells. 1 hour as default")
	int balancingHysteresis() default 3600; // 1hour. Depends on battery´s capacity?? Maybe it should be calculated
	// dynamically

	@AttributeDefinition(name = "Debug Mode", description = "Extends debugging")
	boolean debugMode() default true;

	@AttributeDefinition(name = "Mode", description = "Set controller ON or OFF")
	boolean isChargeDischargeLimiterEnabled() default true;

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller ESS Charge/Discharge limiter [{id}]";

}