= Run the prebuilt OpenEMS UI
:sectnums:
:sectnumlevels: 4
:toclevels: 4
:experimental:
:keywords: AsciiDoc
:source-highlighter: highlight.js
:icons: font

This chapter explains how to run a prebuilt OpenEMS UI.

== General

. Go to the https://github.com/OpenEMS/openems/releases/[OpenEMS release page] on GitHub and download the latest `openems-ui.tar.xz`.

. Extract it to a local directory on your machine.

. Set up a web server serving this directory on port 4200 and start it. Any web server can be used. The next section describes how to set up the nginx web server under Linux.

== Set up the nginx webserver on Linux

We assume that the UI directory is /home/user/openems/openems-ui

=== Setup

. Install nginx (e.g. `apt install nginx` on Debian / Ubuntu and derivatives)
 
. Create a file /etc/nginx/conf.d/openems_nginx.conf with the following contents:
+
```
server {
    listen 4200;
    server_name openems;
    # OpenEMS Web-Interface
    location / {
       root    /home/user/openems/openems-ui;
       index    index.html index.htm;

       error_page    404    300    /index.html;
    }
}
```

. Start nginx. See `man nginx` and the documentation on https://nginx.org for more information.

=== Troubleshooting

. If there are error messages saying that port 80 is already used, e.g. by another webserver already running on your machine: Remove /etc/nginx/sites-enabled/default. This is a link to /etc/nginx/sites-available/default where port 80 is configured to be used.

. If the browser shows “403 forbidden”, this may be due to missing permissions. nginx needs read and execute permissions on all directories on the path to the openems-ui directory. You can check this with the command `namei -l /home/user/openems/openems-ui`. For example, /home/user might have “rwx” permissions only for user. In that case, the command `chmod a+rx /home/user` changes the permissions, so that nginx can run openems-ui.
