package io.openems.edge.solaredge.ess.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;


@ObjectClassDefinition(name = "SolarEdge Charger Timo", //
		description = "Implements the SolarEdge Charger.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "SolarEdge ESS-Inverter", description = "ID of SolarEdge Energy Storage System.")
	String essInverter_id() default "ess0";
	
	@AttributeDefinition(name = "SolarEdge ESS-Inverter target filter", description = "This is auto-generated by 'SolarEdge ESS-Inverter'.")
	String essInverter_target() default "(enabled=true)";	

	String webconsole_configurationFactory_nameHint() default "Charger SolarEdge [{id}]";

}
