package io.openems.edge.solaredge.ess.charger;

import io.openems.common.channel.PersistencePriority;
import io.openems.common.channel.Unit;
import io.openems.common.types.OpenemsType;
import io.openems.edge.common.channel.Doc;
import io.openems.edge.common.channel.IntegerReadChannel;
import io.openems.edge.common.channel.value.Value;
import io.openems.edge.common.component.OpenemsComponent;
import io.openems.edge.ess.dccharger.api.EssDcCharger;

public interface SolarEdgeCharger extends EssDcCharger, OpenemsComponent {

	public enum ChannelId implements io.openems.edge.common.channel.ChannelId {
		
		/**
		 * DC Inverter Power (includes power generated by the PV system and battery charge/discharge).
		 *
		 * <ul>
		 * <li>Interface: SolarEdgeCharger
		 * <li>Type: Integer
		 * <li>Unit: W
		 * <li>Range: positive values for feed power to AC; negative for charge from AC
		 * </ul>
		 */
		INVERTER_POWER(Doc.of(OpenemsType.INTEGER) //
				.unit(Unit.WATT) //
				.persistencePriority(PersistencePriority.HIGH)),

		/**
		 * DC Charge/Discharge Power.
		 *
		 * <ul>
		 * <li>Interface: SolarEdgeCharger
		 * <li>Type: Integer
		 * <li>Unit: W
		 * <li>Range: positive values for Charge; negative for Discharge
		 * <li>This is the instantaneous power to or from the battery
		 * </ul>
		 */
		CHARGE_POWER(Doc.of(OpenemsType.INTEGER) //
				.unit(Unit.WATT) //
				.persistencePriority(PersistencePriority.HIGH)),

		/**
		 * DC Charge/Discharge Current.
		 *
		 * <ul>
		 * <li>Interface: SolarEdgeCharger
		 * <li>Type: Integer
		 * <li>Unit: mA
		 * <li>Range: positive values for Charge; negative for Discharge
		 * <li>This is the instantaneous current to or from the battery
		 * </ul>
		 */
		CHARGE_CURRENT(Doc.of(OpenemsType.INTEGER) //
				.unit(Unit.MILLIAMPERE) //
				.persistencePriority(PersistencePriority.HIGH)),	
		
		;
		private final Doc doc;

		private ChannelId(Doc doc) {
			this.doc = doc;
		}

		@Override
		public Doc doc() {
			return this.doc;
		}
	}
	
	/**
	 * Gets the Channel for {@link ChannelId#INVERTER_POWER}.
	 *
	 * @return the Channel
	 */
	public default IntegerReadChannel getInverterPowerChannel() {
		return this.channel(ChannelId.INVERTER_POWER);
	}
	
	/**
	 * Gets the DC Inverter power (Actual PV and charge/discharge DC Power) in [W]. See {@link ChannelId#DC_POWER}.
	 *
	 * @return the Channel {@link Value}
	 */
	public default Value<Integer> getInverterPower() {
		return this.getInverterPowerChannel().value();
	}

	/**
	 * Gets the Channel for {@link ChannelId#DC_DISCHARGE_POWER}.
	 *
	 * @return the Channel
	 */
	public default IntegerReadChannel getChargePowerChannel() {
		return this.channel(ChannelId.CHARGE_POWER);
	}
	
	/**
	 * Gets the Actual DC Charge/Discharge Power in [W]. See {@link ChannelId#DC_DISCHARGE_POWER}.
	 *
	 * @return the Channel {@link Value}
	 */
	public default Value<Integer> getChargePower() {
		return this.getChargePowerChannel().value();
	}
	
	/**
	 * Gets the Channel for {@link ChannelId#DC_DISCHARGE_POWER}.
	 *
	 * @return the Channel
	 */
	public default IntegerReadChannel getChargeCurrentChannel() {
		return this.channel(ChannelId.CHARGE_CURRENT);
	}
	
	/**
	 * Gets the Actual DC Charge/Discharge Current in [mA]. See {@link ChannelId#DC_DISCHARGE_POWER}.
	 *
	 * @return the Channel {@link Value}
	 */
	public default Value<Integer> getChargeCurrent() {
		return this.getChargeCurrentChannel().value();
	}	
}
