variables:
  - &sftp-settings
    server: 10.0.0.40
    username: user
    password: pass
    ignore_branch: true
    port: 2222
    path: /cache
    mount:
      - cache

  - &when
    when:
      - branch: [main, develop]
      - evaluate: 'CI_COMMIT_MESSAGE contains "[DEBIAN]"'

steps:
  restore-cache:
    <<: *when
    image: appleboy/drone-sftp-cache
    settings:
      restore: true
      <<: *sftp-settings

  build-debian-package:
    <<: *when
    image: openems-build:latest
    commands:
      - export CACHE=$CI_WORKSPACE/cache
      - mkdir -p $CACHE
      - export GRADLE_USER_HOME=$CACHE/gradle
      - export npm_config_cache=$CACHE/npm
      - export NG_CLI_CACHE_PATH=$CACHE/angular-cli
      - export NODE_MODULES_CACHE=$CACHE/node_modules
      - export MAVEN_OPTS=-Dmaven.repo.local=$CACHE/maven
      - tools/build-debian-package.sh

  rebuild-cache:
    <<: *when
    image: appleboy/drone-sftp-cache
    settings:
      rebuild: true
      <<: *sftp-settings

  refresh-dev:
    <<: *when
    image: appleboy/drone-scp:latest
    settings:
      host: 10.0.0.40
      user: fenecon-docs
      key:
        from_secret: ssh_key_intranet
      #rm: true
      source:
        - ./*.deb
      target: /opt/gitea/data/openems-ui-dev/html/${CI_COMMIT_BRANCH}
