package io.openems.edge.ess.fenecon.commercial40;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "ESS FENECON Commercial 40", //
		description = "Implements the FENECON Commercial 40 energy storage system.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readOnlyMode() default false;

	@AttributeDefinition(name = "Feed surplus power to the Grid", description = "Feeds surplus power to the grid. Only applies if Read-Only mode is deactivated.")
	boolean activateSurplusFeedIn() default false;

	@AttributeDefinition(name = "Surplus Allowed-Charge-Power limit", description = "Allowed to start surplus after Charge-Power limit. (Needs to set negative)")
	int surplusAllowedChargePowerLimit() default -8000;

	@AttributeDefinition(name = "Surplus Off Time", description = "The time to stop grid feed in.")
	String surplusOffTime() default "17:00:00";

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "ESS FENECON Commercial 40 [{id}]";
}
