package io.openems.edge.evse.chargepoint.alfen;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.type.Phase.SingleOrThreePhase;
import io.openems.edge.meter.api.PhaseRotation;

@ObjectClassDefinition(//
		name = "EVSE Charge-Point Alfen", //
		description = "Implementation for the Alfen NG910 single-socket charging station (Eve Single S-line, Eve Single Pro-line)")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "evseChargePoint0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read only", description = "Defines that this charge point is read only.", required = true)
	boolean readOnly() default false;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	@AttributeDefinition(name = "Phase Rotation", description = "Apply standard or rotated wiring")
	PhaseRotation phaseRotation() default PhaseRotation.L1_L2_L3;

	// Physical wiring of the charge point. SINGLE_PHASE wiring can never do phase
	// switching; it is also used as fallback when Modbus register 1215 ("Charge
	// using 1 or 3 phases") is not available.
	@AttributeDefinition(name = "Wiring", description = "Is the charge point wired with one or three phases?")
	SingleOrThreePhase wiring() default SingleOrThreePhase.THREE_PHASE;

	@AttributeDefinition(name = "Minimum current", description = "Minimum charging current in mA.", required = true)
	int minCurrent() default 6000;

	@AttributeDefinition(name = "Maximum current", description = "Maximum charging current in mA.", required = true)
	int maxCurrent() default 32000;

	String webconsole_configurationFactory_nameHint() default "EVSE Charge-Point Alfen [{id}]";

}
