#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /etc/nginx/keys \
    /etc/nginx/site-confs \
    /var/log/nginx \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx
