package io.openems.edge.evse.chargepoint.hardybarth.common;

public class Constants {

	public static final String API_RESPONSE = """
			{
			   "device":{
			      "product":"2310007",
			      "modelname":"Salia PLCC Slave",
			      "hardware_version":"1.0",
			      "software_version":"1.50.0",
			      "vcs_version":"V0R5e",
			      "hostname":"salia",
			      "mac_address":"00:01:87:13:12:34",
			      "serial":"101249323",
			      "uuid":"5491ad62-022a-4356-a32c-00018713102x",
			      "internal_id":"412009"
			   },
			   "secc":{
			      "port0":{
			         "ci":{
			            "evse":{
			               "basic":{
			                  "grid_current_limit":{
			                     "actual":"16"
			                  },
			                  "phase_count":"3",
			                  "physical_current_limit":"16",
			                  "offered_current_limit":"6.0"
			               },
			               "phase":{
			                  "actual":"3"
			               }
			            },
			            "charge":{
			               "cp":{
			                  "status":"C"
			               },
			               "plug":{
			                  "status":"locked"
			               },
			               "contactor":{
			                  "status":"closed"
			               },
			               "pwm":{
			                  "status":"10.00"
			               }
			            }
			         },
			         "salia":{
			            "chargemode":"power",
			            "thermal":"52893",
			            "mem":"392276",
			            "uptime":" 1:04",
			            "load":"0.37",
			            "chargedata":"3813|3192|3.46|",
			            "authmode":"free",
			            "firmwarestate":"idle",
			            "firmwareprogress":"0",
			            "heartbeat":"off",
			            "pausecharging":"0"
			         },
			         "session":{
			            "authorization_status":""
			         },
			         "contactor":{
			            "state":{
			               "hlc_target":"0",
			               "actual":"1",
			               "target":"1"
			            },
			            "error":"0"
			         },
			         "metering":{
			            "meter":{
			               "serialnumber":"21031835",
			               "type":"klefr",
			               "available":"1"
			            },
			            "eichrecht_protocol":"none",
			            "power":{
			               "active":{
			                  "ac":{
			                     "l1":{
			                        "actual":"10750"
			                     },
			                     "l2":{
			                        "actual":"10730"
			                     },
			                     "l3":{
			                        "actual":"10440"
			                     }
			                  }
			               },
			               "active_total":{
			                  "actual":"31920"
			               }
			            },
			            "current":{
			               "ac":{
			                  "l1":{
			                     "actual":"5000"
			                  },
			                  "l2":{
			                     "actual":"5000"
			                  },
			                  "l3":{
			                     "actual":"4770"
			                  }
			               }
			            },
			            "energy":{
			               "active_total":{
			                  "actual":"4658050"
			               },
			               "active_export":{
			                  "actual":"0"
			               },
			               "active_import":{
			                  "actual":"4658050"
			               }
			            }
			         },
			         "emergency_shutdown":"0",
			         "rcd":{
			            "feedback":{
			               "available":"1"
			            },
			            "state":{
			               "actual":"1"
			            },
			            "recloser":{
			               "available":"0"
			            }
			         },
			         "plug_lock":{
			            "state":{
			               "actual":"1",
			               "target":"1"
			            },
			            "error":"0"
			         },
			         "availability":{
			            "actual":"operative"
			         },
			         "cp":{
			            "pwm_state":{
			               "actual":"1"
			            },
			            "state":"C",
			            "duty_cycle":"10.00"
			         },
			         "rfid":{
			            "available":"0",
			            "authorizereq":""
			         },
			         "diode_present":"1",
			         "cable_current_limit":"-1",
			         "ready_for_slac":"0",
			         "ev_present":"1",
			         "ventilation":{
			            "state":{
			               "actual":"0"
			            },
			            "available":"0"
			         },
			         "charging":"1",
			         "grid_current_limit":"6"
			      }
			   }
			}
			""";

	public static final String EMPTY_API_RESPONSE = """
			{
			   "device":{
			      "product":null,
			      "modelname":null,
			      "hardware_version":null,
			      "software_version":null,
			      "vcs_version":null,
			      "hostname":null,
			      "mac_address":null,
			      "serial":null,
			      "uuid":null,
			      "internal_id":null
			   },
			   "secc":{
			      "port0":{
			         "ci":{
			            "evse":{
			               "basic":{
			                  "grid_current_limit":{
			                     "actual":null
			                  },
			                  "phase_count":null,
			                  "physical_current_limit":null,
			                  "offered_current_limit":null
			               },
			               "phase":{
			                  "actual":null
			               }
			            },
			            "charge":{
			               "cp":{
			                  "status":null
			               },
			               "plug":{
			                  "status":null
			               },
			               "contactor":{
			                  "status":null
			               },
			               "pwm":{
			                  "status":null
			               }
			            }
			         },
			         "salia":{
			            "chargemode":null,
			            "thermal":null,
			            "mem":null,
			            "uptime":null,
			            "load":null,
			            "chargedata":null,
			            "authmode":null,
			            "firmwarestate":null,
			            "firmwareprogress":null,
			            "heartbeat":null,
			            "pausecharging":null
			         },
			         "session":{
			            "authorization_status":null
			         },
			         "contactor":{
			            "state":{
			               "hlc_target":null,
			               "actual":null,
			               "target":null
			            },
			            "error":null
			         },
			         "metering":{
			            "meter":{
			               "serialnumber":null,
			               "type":null,
			               "available":null
			            },
			            "eichrecht_protocol":null,
			            "power":{
			               "active":{
			                  "ac":{
			                     "l1":{
			                        "actual":null
			                     },
			                     "l2":{
			                        "actual":null
			                     },
			                     "l3":{
			                        "actual":null
			                     }
			                  }
			               },
			               "active_total":{
			                  "actual":null
			               }
			            },
			            "current":{
			               "ac":{
			                  "l1":{
			                     "actual":null
			                  },
			                  "l2":{
			                     "actual":null
			                  },
			                  "l3":{
			                     "actual":null
			                  }
			               }
			            },
			            "energy":{
			               "active_total":{
			                  "actual":null
			               },
			               "active_export":{
			                  "actual":null
			               },
			               "active_import":{
			                  "actual":null
			               }
			            }
			         },
			         "emergency_shutdown":null,
			         "rcd":{
			            "feedback":{
			               "available":null
			            },
			            "state":{
			               "actual":null
			            },
			            "recloser":{
			               "available":null
			            }
			         },
			         "plug_lock":{
			            "state":{
			               "actual":null,
			               "target":null
			            },
			            "error":null
			         },
			         "availability":{
			            "actual":null
			         },
			         "cp":{
			            "pwm_state":{
			               "actual":null
			            },
			            "state":null,
			            "duty_cycle":null
			         },
			         "rfid":{
			            "available":null,
			            "authorizereq":null
			         },
			         "diode_present":null,
			         "cable_current_limit":null,
			         "ready_for_slac":null,
			         "ev_present":null,
			         "ventilation":{
			            "state":{
			               "actual":null
			            },
			            "available":null
			         },
			         "charging":null,
			         "grid_current_limit":null
			      }
			   }
			}
			""";

}
