package io.openems.edge.simulator.controller.ess.csvactivepower;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.type.Phase.SingleOrAllPhase;
import io.openems.edge.ess.power.api.Relationship;

@ObjectClassDefinition(//
		name = "Simulator Controller Ess CSV Active Power", //
		description = "Defines active power values read from a CSV data source to control a  energy storage system.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlCsvActivePower0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id();

	@AttributeDefinition(name = "Datasource-ID", description = "ID of CSV Datasource component.")
	String datasource_id();

	@AttributeDefinition(name = "Power Column Name", description = "Name of the column in CSV containing power values")
	String powerColumnName() default "power";

	@AttributeDefinition(name = "Scale Factor", description = "Multiplier applied to power values from CSV")
	int scaleFactor() default 1;

	@AttributeDefinition(name = "Ramp Rate", description = "Maximum power change per second in Watts")
	int rampRate() default 500;

	@AttributeDefinition(name = "Power Relationship", description = "Target power must be equal, less-than or greater-than the configured power value")
	Relationship relationship() default Relationship.EQUALS;

	@AttributeDefinition(name = "Phase", description = "Apply target power to L1, L2, L3 or sum of all phases")
	SingleOrAllPhase phase() default SingleOrAllPhase.ALL;

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Datasource target filter", description = "This is auto-generated by 'Datasource-ID'.")
	String datasource_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Simulator Controller Ess CSV Active Power [{id}]";

}