package io.openems.edge.controller.ess.fastfrequencyreserve;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.controller.ess.fastfrequencyreserve.enums.Mode;

@ObjectClassDefinition(//
		name = "Controller Ess Fast Frequency Reserve", //
		description = "")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlFastFreqReserve0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Mode", description = "Set the type of mode. if smart mode choosen please set the default schedule json")
	Mode mode() default Mode.MANUAL_OFF;

	@AttributeDefinition(name = "Activation Schdule", description = "Schdeule for the activation.")
	String activationScheduleJson() default "[{\n" //
			+ "	\"startTimestamp\": \"1542464697\",\n"//
			+ "	\"duration\": \"900\",\n"//
			+ "	\"dischargePowerSetPoint\": \"92000\",\n"//
			+ "	\"frequencyLimit\": \"49500\",\n"//
			+ "	\"activationRunTime\": \"LONG_ACTIVATION_RUN\",\n"//
			+ "	\"supportDuration\": \"LONG_SUPPORT_DURATION\"\n"//
			+ "}]";//

	@AttributeDefinition(name = "Ess-ID", description = "ID of Ess device.")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "Grid-Meter-Id", description = "ID of the Grid-Meter.")
	String meter_id() default "meter0";

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Meter target filter", description = "This is auto-generated by 'Grid-Meter-ID'.")
	String meter_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Ess Fast Frequency Reserve [{id}]";

}
