package io.openems.edge.mqtt.component.publish;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.mqtt.component.enums.TimeIntervalSeconds;

@ObjectClassDefinition(//
		name = "Mqtt Generic Publish", //
		description = "A Generic Publish Component, formatting in a Payload style." //
)
@interface GenericPublishConfig {

	@AttributeDefinition(name = "Id", description = "Unique ID of this component.")
	String id() default "genericPublish0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Mqtt-ID", description = "ID of Mqtt bridge.")
	String mqtt_id() default "mqttBridge0";

	@AttributeDefinition(name = "Reference-ID", description = "ID of Referenced OpenEms Component.")
	String referencedComponent_id();

	@AttributeDefinition(name = "Device-ID Broker", description = "Representable Component Id within the Broker.")
	String deviceId() default "pv-1";

	@AttributeDefinition(name = "Referenced Component Channels", description = "This is auto-generated after first save.")
	String[] channels();

	@AttributeDefinition(name = "Topic", description = "Where to publish the data.")
	String topic();

	@AttributeDefinition(name = "Publish Interval", description = "How often to publish Data.")
	TimeIntervalSeconds publishIntervalSeconds() default TimeIntervalSeconds.QUARTER_HOUR;

	@AttributeDefinition(name = "KeyToChannel Config", description = "Configure here what Channel you want to Publish."
			+ "Each entry should contains a \"key\" word e.g. \"consumption\" and a ChannelId e.g. \"ActivePower\"")
	String[] keyToChannel();

	@AttributeDefinition(name = "Referenced Component target filter", description = "This is auto-generated by 'referencedComponent-ID'.")
	String ReferencedComponent_target() default "(enabled=true)";

	@AttributeDefinition(name = "Mqtt target filter", description = "This is auto-generated by 'Mqtt-ID'.")
	String Mqtt_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Mqtt Generic Publish Consolinno {id}";
}
