package io.openems.edge.solaredge.pvinverter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.pvinverter.sunspec.Phase;

@ObjectClassDefinition(name = "PV-Inverter SolarEdge", //
		description = "Implements the SolarEdge PV inverter. Can be configured as an hybrid system in connection with a SolarEdge Home Battery")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "pvInverter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "Is Hybrid System?", description = "Is this inverter part of an hybrid system?")
	boolean hybrid() default false;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device. ")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Phase", description = "On which phase is the inverter connected?")
	Phase phase() default Phase.ALL;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "PV-Inverter SolarEdge [{id}]";

}
