name: Build OpenEMS Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    tags:
      - "*.*.*"
    
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: [edge, backend, ui-edge, ui-backend, backend-edge]
        include:
          - image: edge
            dockerfile: tools/docker/edge/Dockerfile
          - image: ui-edge
            dockerfile: tools/docker/ui/Dockerfile.edge
          - image: backend
            dockerfile: tools/docker/backend/Dockerfile
          - image: ui-backend
            dockerfile: tools/docker/ui/Dockerfile.backend
          - image: backend-edge
            dockerfile: tools/docker/backend-edge/Dockerfile
    permissions:
        packages: write
        contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        
      - name: Get cleaned branch name
        id: clean_name
        run: |
          REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\///' -e 's/release\/v//')
          echo "branch=${REF_NAME}-test" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            openems/${{ matrix.image }}
            ghcr.io/openems/${{ matrix.image }}
          labels: |
            org.opencontainers.image.authors=OpenEMS
            org.opencontainers.image.title=OpenEMS ${{ matrix.image }}
            org.opencontainers.image.vendor=OpenEMS <openems.io>
          tags: |
            type=semver,pattern={{raw}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}

      - name: Build and push Docker images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
