package io.openems.edge.meter.artemes.am2;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.meter.api.MeterType;

@ObjectClassDefinition(name = "Meter Artemes AM-2", description = "Implements the Artemes AM-2 meter.")
@interface Config {

	String id() default "meter0";

	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "Grid, Production (=default), Consumption")
	MeterType type() default MeterType.PRODUCTION;

	@AttributeDefinition(name = "Modbus-ID", description = "Id of the modbus bridge")
	String modbus_id();

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device")
	int modbusUnitId();

	@AttributeDefinition(name = "Modbus target filter", description = " This is auto-generated by 'Modbus-ID'")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "Meter Artemes AM-2 [{id}]";

}